## Copyright (c) 2018-2019 Advanced Micro Devices, Inc. All rights reserved.
cmake_minimum_required(VERSION 3.5.1)

set(DEPTH "../../")

set(GPA_PROJECT_NAME GPUPerfAPICounterGenerator-GL)
set(ProjectName ${GPA_PROJECT_NAME})

set(CMAKE_INCLUDE_CURRENT_DIR ON)
include(${GPA_CMAKE_MODULES_DIR}/Common.cmake)
include(${CMAKE_COMMON_LIB_GLOBAL_EXT_OPENGL})

set(COUNTER_GENERATOR_HEADERS_GL
    GPACounterGeneratorGL.h)

set(GL_SRC  GLEntryPoints.h
            GLFunctions.h
            GLFuncTypes.h
            GLEntryPoints.cpp)

set(COUNTER_GENERATOR_SRC_GL
    GPACounterGeneratorGL.cpp)

set(COUNTER_SCHEDULER_HEADERS_GL
    GPACounterSchedulerGL.h)

set(COUNTER_SCHEDULER_SRC_GL
    GPACounterSchedulerGL.cpp)

if(EXISTS ${GPA_AUTOGEN_SRC_COUNTER_GENERATOR})
    include(${GPA_AUTOGEN_SRC_COUNTER_GENERATOR}/GPAHWCounterGL.cmake)
    include(${GPA_AUTOGEN_SRC_COUNTER_GENERATOR}/PublicCounterDefsGL.cmake)

    set(API_HEADER_FILES ${HW_COUNTER_HEADERS_GL} ${PUBLIC_COUNTER_DEF_HEADERS_GL} ${ADDITIONAL_COUNTER_DEF_HEADERS_GL})
    set(API_SOURCE_FILES ${HW_COUNTER_SRC_GL} ${PUBLIC_COUNTER_DEF_SRC_GL} ${ADDITIONAL_COUNTER_DEF_SRC_GL})

    if(WIN32)
        source_group("Source Files\\${HARDWARE_COUNTER_VS_FILTER}\\AutoGenerated" FILES ${HW_COUNTER_HEADERS_GL} ${HW_COUNTER_SRC_GL})
        source_group("Source Files\\${DERIVED_COUNTER_VS_FILTER}\\AutoGenerated" FILES ${PUBLIC_COUNTER_DEF_HEADERS_GL}
                                                                                       ${ADDITIONAL_COUNTER_DEF_HEADERS_GL}
                                                                                       ${PUBLIC_COUNTER_DEF_SRC_GL}
                                                                                       ${ADDITIONAL_COUNTER_DEF_SRC_GL})
    endif()
endif()

set(SOURCES ${COUNTER_GENERATOR_HEADERS_GL}
            ${COUNTER_GENERATOR_SRC_GL}
            ${COUNTER_SCHEDULER_HEADERS_GL}
            ${COUNTER_SCHEDULER_SRC_GL}
            ${GL_SRC}
            ${API_HEADER_FILES}
            ${API_SOURCE_FILES}
            ${ADDITIONAL_COUNTERS_GL})

if(WIN32)
    add_compile_options(/bigobj)
else()
    add_compile_options(-Wno-write-strings)
endif()

ADD_STATIC_LIBRARY(${GPA_PROJECT_NAME})
ADD_LINKER_FLAGS()
target_link_libraries(${GPA_PROJECT_NAME} GPUPerfAPICounterGenerator-Common)
target_include_directories(${GPA_PROJECT_NAME} PUBLIC ${ADDITIONAL_INCLUDE_DIRECTORIES})

if(WIN32)
    source_group("Source Files\\" FILES ${GL_SRC})
    source_group("Source Files\\${COUNTER_GENERATOR_VS_FILTER}" FILES ${COUNTER_GENERATOR_HEADERS_GL} ${COUNTER_GENERATOR_SRC_GL})
    source_group("Source Files\\${COUNTER_SCHEDULER_VS_FILTER}" FILES ${COUNTER_SCHEDULER_HEADERS_GL} ${COUNTER_SCHEDULER_SRC_GL})
endif()

