//==============================================================================
// Copyright (c) 2010-2018 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  CL internal counter definitions for GFX8
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project

#ifndef _GPA_INTERNAL_COUNTERS_CL_GFX8_H_
#define _GPA_INTERNAL_COUNTERS_CL_GFX8_H_

#include <set>

struct GPA_HardwareCounterDesc;
struct GPA_CounterGroupDesc;
struct GPA_SQCounterGroupDesc;

extern GPA_HardwareCounterDesc* CLCounterGroupArrayGfx8[]; ///< Array of hardware counter groups for CL for Gfx8 family
extern GPA_CounterGroupDesc HWCLGroupsGfx8[]; ///< Array of counter groups for CL for Gfx8 family
extern GPA_SQCounterGroupDesc HWCLSQGroupsGfx8[]; ///< Array of SQ groups for CL for Gfx8 family
extern unsigned int HWCLSQIsolatedGroupsGfx8[]; ///< Array of counter groups isolated from SQ counter groups for CL for Gfx8 family
extern const std::set<unsigned int> HWCLTimestampBlockIdsGfx8; ///< Timestamp block id's for CL for Gfx8 family
extern const std::set<unsigned int> HWCLTimeCounterIndicesGfx8; ///< Timestamp counter indices for CL for Gfx8 family
extern const unsigned int HWCLGroupCountGfx8; ///< Hardware Group Count for CL for Gfx8 family
extern const unsigned int HWCLSQGroupCountGfx8; ///< Hardware SQ Group Count for CL for Gfx8 family
extern const unsigned int HWCLSQIsolatedGroupCountGfx8; ///< Hardware Isolated Group Count for CL for Gfx8 family

#endif // _GPA_INTERNAL_COUNTERS_CL_GFX8_H_
