//==============================================================================
// Copyright (c) 2010-2017 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  DX12 internal counter definitions for GFX8
//==============================================================================

#ifndef _GPA_INTERNAL_COUNTERS_DX12_GFX8_H_
#define _GPA_INTERNAL_COUNTERS_DX12_GFX8_H_
// This file is autogenerated by the ConvertHWEnums project

#include <windows.h>
#pragma warning (push)
#pragma warning (disable: 4201)
#include <AmdExtGpaInterface.h>
#pragma warning (pop)

extern GPA_HardwareCounterDesc* DX12CounterGroupArrayGfx8[]; ///< Array of hardware counter groups for DX12 for Gfx8 family
extern GPA_CounterGroupDesc HWDX12GroupsGfx8[]; ///< Array of counter groups for DX12 for Gfx8 family
extern GPA_SQCounterGroupDesc HWDX12SQGroupsGfx8[]; ///< Array of SQ groups for DX12 for Gfx8 family
extern unsigned int HWDX12SQIsolatedGroupsGfx8[]; ///< Array of counter groups isolated from SQ counter groups for DX12 for Gfx8 family
extern AmdExtGpuBlock HWDX12DriverEnumGfx8[]; ///< Array of driver enum values per group for DX12 for Gfx8 family
extern const unsigned int HWDX12GPUTimeIndexGfx8; ///< Index of GPUTime Group for DX12 for Gfx8 family
extern const unsigned int HWDX12GroupCountGfx8; ///< Hardware Group Count for DX12 for Gfx8 family
extern const unsigned int HWDX12SQGroupCountGfx8; ///< Hardware SQ Group Count for DX12 for Gfx8 family
extern const unsigned int HWDX12SQIsolatedGroupCountGfx8; ///< Hardware Isolated Group Count for DX12 for Gfx8 family

#endif // _GPA_INTERNAL_COUNTERS_DX12_GFX8_H_
