//==============================================================================
// Copyright (c) 2010-2018 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  GL internal counter definitions for GFX9
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project

#ifndef _GPA_INTERNAL_COUNTERS_GL_GFX9_H_
#define _GPA_INTERNAL_COUNTERS_GL_GFX9_H_

#include <set>

struct GPA_HardwareCounterDesc;
struct GPA_CounterGroupDesc;
struct GPA_SQCounterGroupDesc;

extern GPA_HardwareCounterDesc* GLCounterGroupArrayGfx9[]; ///< Array of hardware counter groups for GL for Gfx9 family
extern GPA_CounterGroupDesc HWGLGroupsGfx9[]; ///< Array of counter groups for GL for Gfx9 family
extern GPA_SQCounterGroupDesc HWGLSQGroupsGfx9[]; ///< Array of SQ groups for GL for Gfx9 family
extern unsigned int HWGLSQIsolatedGroupsGfx9[]; ///< Array of counter groups isolated from SQ counter groups for GL for Gfx9 family
extern const unsigned int HWGLGputimeBottomToBottomDurationIndexGfx9; ///< Index of delta between the previous command reaching bottom of pipe and the current command reaching bottom of pipe, will not include latency of first data to travel through pipeline, best for large data sets. for GL for Gfx9 family
extern const unsigned int HWGLGputimeBottomToBottomStartIndexGfx9; ///< Index of time of the previous command reaching bottom of pipe for GL for Gfx9 family
extern const unsigned int HWGLGputimeBottomToBottomEndIndexGfx9; ///< Index of time of the current command reaching bottom of pipe for GL for Gfx9 family
extern const unsigned int HWGLGputimeTopToBottomDurationIndexGfx9; ///< Index of execution duration of the current command from top of pipe to bottom of pipe, may include overhead of time in queue for GL for Gfx9 family
extern const unsigned int HWGLGputimeTopToBottomStartIndexGfx9; ///< Index of time that the current command reaches the top of pipe for GL for Gfx9 family
extern const unsigned int HWGLGputimeTopToBottomEndIndexGfx9; ///< Index of time that the current command reaches the bottom of pipe for GL for Gfx9 family
extern const std::set<unsigned int> HWGLTimestampBlockIdsGfx9; ///< Timestamp block id's for GL for Gfx9 family
extern const std::set<unsigned int> HWGLTimeCounterIndicesGfx9; ///< Timestamp counter indices for GL for Gfx9 family
extern const unsigned int HWGLGroupCountGfx9; ///< Hardware Group Count for GL for Gfx9 family
extern const unsigned int HWGLSQGroupCountGfx9; ///< Hardware SQ Group Count for GL for Gfx9 family
extern const unsigned int HWGLSQIsolatedGroupCountGfx9; ///< Hardware Isolated Group Count for GL for Gfx9 family

#endif // _GPA_INTERNAL_COUNTERS_GL_GFX9_H_
