//==============================================================================
// Copyright (c) 2010-2018 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  DX11 internal counter definitions for GFX7
//==============================================================================

#ifndef _GPA_INTERNAL_COUNTERS_DX11_GFX7_H_
#define _GPA_INTERNAL_COUNTERS_DX11_GFX7_H_
// This file is autogenerated by the ConvertHWEnums project

#include <windows.h>
#include <AmdDxExtPerfProfile.h>

extern GPA_HardwareCounterDesc* DX11CounterGroupArrayGfx7[]; ///< Array of hardware counter groups for DX11 for Gfx7 family
extern GPA_CounterGroupDesc HWDX11GroupsGfx7[]; ///< Array of counter groups for DX11 for Gfx7 family
extern GPA_SQCounterGroupDesc HWDX11SQGroupsGfx7[]; ///< Array of SQ groups for DX11 for Gfx7 family
extern unsigned int HWDX11SQIsolatedGroupsGfx7[]; ///< Array of counter groups isolated from SQ counter groups for DX11 for Gfx7 family
extern PE_BLOCK_ID HWDX11DriverEnumGfx7[]; ///< Array of driver enum values per group for DX11 for Gfx7 family
extern const unsigned int HWDX11GPUTimeBottomToBottomIndexGfx7; ///< Index of EOP to EOP counter for DX11 for Gfx7 family
extern const unsigned int HWDX11GPUTimeTopToBottomIndexGfx7; ///< Index of TOP to EOP counter for DX11 for Gfx7 family
extern const std::set<unsigned int> HWDX11TimestampBlockIdsGfx7; ///< Timestamp block id's for DX11 for Gfx7 family
extern const std::set<unsigned int> HWDX11TimeCounterIndicesGfx7; ///< Timestamp counter indices for DX11 for Gfx7 family
extern const unsigned int HWDX11GroupCountGfx7; ///< Hardware Group Count for DX11 for Gfx7 family
extern const unsigned int HWDX11SQGroupCountGfx7; ///< Hardware SQ Group Count for DX11 for Gfx7 family
extern const unsigned int HWDX11SQIsolatedGroupCountGfx7; ///< Hardware Isolated Group Count for DX11 for Gfx7 family

#endif // _GPA_INTERNAL_COUNTERS_DX11_GFX7_H_
