//==============================================================================
// Copyright (c) 2010-2018 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  HSA internal counter definitions for GFX9
//==============================================================================

#include "GPAInternalCounter.h"
#include "GPAInternalCountersGfx9.h"
#include "InternalCountersHSAGfx9.h"

// This file is autogenerated by the ConvertHWEnums project

GPA_HardwareCounterDesc* HSACounterGroupArrayGfx9[] =
{
    CPCcountersGfx9,
    CPFcountersGfx9,
    GDScountersGfx9,
    GRBMcountersGfx9,
    GRBMSE0countersGfx9,
    SPI0countersGfx9,
    SQ0countersGfx9,
    SQ_CS0countersGfx9,
    SX0countersGfx9,
    TA0countersGfx9,
    TA1countersGfx9,
    TA2countersGfx9,
    TA3countersGfx9,
    TA4countersGfx9,
    TA5countersGfx9,
    TA6countersGfx9,
    TA7countersGfx9,
    TA8countersGfx9,
    TA9countersGfx9,
    TA10countersGfx9,
    TA11countersGfx9,
    TA12countersGfx9,
    TA13countersGfx9,
    TA14countersGfx9,
    TA15countersGfx9,
    TCA0countersGfx9,
    TCA1countersGfx9,
    TCC0countersGfx9,
    TCC1countersGfx9,
    TCC2countersGfx9,
    TCC3countersGfx9,
    TCC4countersGfx9,
    TCC5countersGfx9,
    TCC6countersGfx9,
    TCC7countersGfx9,
    TCC8countersGfx9,
    TCC9countersGfx9,
    TCC10countersGfx9,
    TCC11countersGfx9,
    TCC12countersGfx9,
    TCC13countersGfx9,
    TCC14countersGfx9,
    TCC15countersGfx9,
    TCP0countersGfx9,
    TCP1countersGfx9,
    TCP2countersGfx9,
    TCP3countersGfx9,
    TCP4countersGfx9,
    TCP5countersGfx9,
    TCP6countersGfx9,
    TCP7countersGfx9,
    TCP8countersGfx9,
    TCP9countersGfx9,
    TCP10countersGfx9,
    TCP11countersGfx9,
    TCP12countersGfx9,
    TCP13countersGfx9,
    TCP14countersGfx9,
    TCP15countersGfx9,
    TD0countersGfx9,
    TD1countersGfx9,
    TD2countersGfx9,
    TD3countersGfx9,
    TD4countersGfx9,
    TD5countersGfx9,
    TD6countersGfx9,
    TD7countersGfx9,
    TD8countersGfx9,
    TD9countersGfx9,
    TD10countersGfx9,
    TD11countersGfx9,
    TD12countersGfx9,
    TD13countersGfx9,
    TD14countersGfx9,
    TD15countersGfx9,
    MCVML2countersGfx9,
    ATCcountersGfx9,
    ATCL2countersGfx9,
    GCEA0countersGfx9,
    GCEA1countersGfx9,
    GCEA2countersGfx9,
    GCEA3countersGfx9,
    GCEA4countersGfx9,
    GCEA5countersGfx9,
    GCEA6countersGfx9,
    GCEA7countersGfx9,
    GCEA8countersGfx9,
    GCEA9countersGfx9,
    GCEA10countersGfx9,
    GCEA11countersGfx9,
    GCEA12countersGfx9,
    GCEA13countersGfx9,
    GCEA14countersGfx9,
    GCEA15countersGfx9,
    RPBcountersGfx9,
};

GPA_CounterGroupDesc HWHSAGroupsGfx9[] =
{
    {0, "CPC", 0, 35, 2},
    {1, "CPF", 0, 32, 2},
    {2, "GDS", 0, 121, 4},
    {3, "GRBM", 0, 38, 2},
    {4, "GRBMSE", 0, 16, 4},
    {5, "SPI", 0, 196, 6},
    {6, "SQ", 0, 374, 16},
    {7, "SQ_CS", 0, 374, 16},
    {8, "SX", 0, 208, 4},
    {9, "TA0", 0, 119, 2},
    {10, "TA1", 1, 119, 2},
    {11, "TA2", 2, 119, 2},
    {12, "TA3", 3, 119, 2},
    {13, "TA4", 4, 119, 2},
    {14, "TA5", 5, 119, 2},
    {15, "TA6", 6, 119, 2},
    {16, "TA7", 7, 119, 2},
    {17, "TA8", 8, 119, 2},
    {18, "TA9", 9, 119, 2},
    {19, "TA10", 10, 119, 2},
    {20, "TA11", 11, 119, 2},
    {21, "TA12", 12, 119, 2},
    {22, "TA13", 13, 119, 2},
    {23, "TA14", 14, 119, 2},
    {24, "TA15", 15, 119, 2},
    {25, "TCA0", 0, 35, 4},
    {26, "TCA1", 1, 35, 4},
    {27, "TCC0", 0, 282, 4},
    {28, "TCC1", 1, 282, 4},
    {29, "TCC2", 2, 282, 4},
    {30, "TCC3", 3, 282, 4},
    {31, "TCC4", 4, 282, 4},
    {32, "TCC5", 5, 282, 4},
    {33, "TCC6", 6, 282, 4},
    {34, "TCC7", 7, 282, 4},
    {35, "TCC8", 8, 282, 4},
    {36, "TCC9", 9, 282, 4},
    {37, "TCC10", 10, 282, 4},
    {38, "TCC11", 11, 282, 4},
    {39, "TCC12", 12, 282, 4},
    {40, "TCC13", 13, 282, 4},
    {41, "TCC14", 14, 282, 4},
    {42, "TCC15", 15, 282, 4},
    {43, "TCP0", 0, 85, 4},
    {44, "TCP1", 1, 85, 4},
    {45, "TCP2", 2, 85, 4},
    {46, "TCP3", 3, 85, 4},
    {47, "TCP4", 4, 85, 4},
    {48, "TCP5", 5, 85, 4},
    {49, "TCP6", 6, 85, 4},
    {50, "TCP7", 7, 85, 4},
    {51, "TCP8", 8, 85, 4},
    {52, "TCP9", 9, 85, 4},
    {53, "TCP10", 10, 85, 4},
    {54, "TCP11", 11, 85, 4},
    {55, "TCP12", 12, 85, 4},
    {56, "TCP13", 13, 85, 4},
    {57, "TCP14", 14, 85, 4},
    {58, "TCP15", 15, 85, 4},
    {59, "TD0", 0, 57, 2},
    {60, "TD1", 1, 57, 2},
    {61, "TD2", 2, 57, 2},
    {62, "TD3", 3, 57, 2},
    {63, "TD4", 4, 57, 2},
    {64, "TD5", 5, 57, 2},
    {65, "TD6", 6, 57, 2},
    {66, "TD7", 7, 57, 2},
    {67, "TD8", 8, 57, 2},
    {68, "TD9", 9, 57, 2},
    {69, "TD10", 10, 57, 2},
    {70, "TD11", 11, 57, 2},
    {71, "TD12", 12, 57, 2},
    {72, "TD13", 13, 57, 2},
    {73, "TD14", 14, 57, 2},
    {74, "TD15", 15, 57, 2},
    {75, "MCVML2", 0, 21, 8},
    {76, "ATC", 0, 24, 4},
    {77, "ATCL2", 0, 8, 2},
    {78, "GCEA0", 0, 83, 2},
    {79, "GCEA1", 1, 83, 2},
    {80, "GCEA2", 2, 83, 2},
    {81, "GCEA3", 3, 83, 2},
    {82, "GCEA4", 4, 83, 2},
    {83, "GCEA5", 5, 83, 2},
    {84, "GCEA6", 6, 83, 2},
    {85, "GCEA7", 7, 83, 2},
    {86, "GCEA8", 8, 83, 2},
    {87, "GCEA9", 9, 83, 2},
    {88, "GCEA10", 10, 83, 2},
    {89, "GCEA11", 11, 83, 2},
    {90, "GCEA12", 12, 83, 2},
    {91, "GCEA13", 13, 83, 2},
    {92, "GCEA14", 14, 83, 2},
    {93, "GCEA15", 15, 83, 2},
    {94, "RPB", 0, 95, 4},
};

GPA_SQCounterGroupDesc HWHSASQGroupsGfx9[] =
{
    {6, 0, SQ_ALL},
    {7, 0, SQ_CS},
};


unsigned int HWHSASQIsolatedGroupsGfx9[] =
{
    9, // Ta
    10, // Ta
    11, // Ta
    12, // Ta
    13, // Ta
    14, // Ta
    15, // Ta
    16, // Ta
    17, // Ta
    18, // Ta
    19, // Ta
    20, // Ta
    21, // Ta
    22, // Ta
    23, // Ta
    24, // Ta
    25, // Tca
    26, // Tca
    27, // Tcc
    28, // Tcc
    29, // Tcc
    30, // Tcc
    31, // Tcc
    32, // Tcc
    33, // Tcc
    34, // Tcc
    35, // Tcc
    36, // Tcc
    37, // Tcc
    38, // Tcc
    39, // Tcc
    40, // Tcc
    41, // Tcc
    42, // Tcc
    43, // Tcp
    44, // Tcp
    45, // Tcp
    46, // Tcp
    47, // Tcp
    48, // Tcp
    49, // Tcp
    50, // Tcp
    51, // Tcp
    52, // Tcp
    53, // Tcp
    54, // Tcp
    55, // Tcp
    56, // Tcp
    57, // Tcp
    58, // Tcp
    59, // Td
    60, // Td
    61, // Td
    62, // Td
    63, // Td
    64, // Td
    65, // Td
    66, // Td
    67, // Td
    68, // Td
    69, // Td
    70, // Td
    71, // Td
    72, // Td
    73, // Td
    74, // Td
};

const std::set<unsigned int> HWHSATimestampBlockIdsGfx9 = {  }; ///< Timestamp block id's for HSA for Gfx9 family
const std::set<unsigned int> HWHSATimeCounterIndicesGfx9 = {  }; ///< Timestamp counter indices for HSA for Gfx9 family
const unsigned int HWHSAGroupCountGfx9 = sizeof(HWHSAGroupsGfx9) / sizeof(GPA_CounterGroupDesc);
const unsigned int HWHSASQGroupCountGfx9 = sizeof(HWHSASQGroupsGfx9) / sizeof(GPA_SQCounterGroupDesc);
const unsigned int HWHSASQIsolatedGroupCountGfx9 = sizeof(HWHSASQIsolatedGroupsGfx9) / sizeof(unsigned int);
