//==============================================================================
// Copyright (c) 2010-2018 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  VK internal counter definitions for GFX9
//==============================================================================

#ifndef _GPA_INTERNAL_COUNTERS_VK_GFX9_H_
#define _GPA_INTERNAL_COUNTERS_VK_GFX9_H_
// This file is autogenerated by the ConvertHWEnums project

#include <vulkan/vulkan.h>
#include <vk_amd_gpa_interface.h>

extern GPA_HardwareCounterDesc* VKCounterGroupArrayGfx9[]; ///< Array of hardware counter groups for VK for Gfx9 family
extern GPA_CounterGroupDesc HWVKGroupsGfx9[]; ///< Array of counter groups for VK for Gfx9 family
extern GPA_SQCounterGroupDesc HWVKSQGroupsGfx9[]; ///< Array of SQ groups for VK for Gfx9 family
extern unsigned int HWVKSQIsolatedGroupsGfx9[]; ///< Array of counter groups isolated from SQ counter groups for VK for Gfx9 family
extern VkGpaPerfBlockAMD HWVKDriverEnumGfx9[]; ///< Array of driver enum values per group for VK for Gfx9 family
extern const unsigned int HWVKGPUTimeBottomToBottomIndexGfx9; ///< Index of EOP to EOP counter for VK for Gfx9 family
extern const unsigned int HWVKGPUTimeTopToBottomIndexGfx9; ///< Index of TOP to EOP counter for VK for Gfx9 family
extern const std::set<unsigned int> HWVKTimestampBlockIdsGfx9; ///< Timestamp block id's for VK for Gfx9 family
extern const std::set<unsigned int> HWVKTimeCounterIndicesGfx9; ///< Timestamp counter indices for VK for Gfx9 family
extern const unsigned int HWVKGroupCountGfx9; ///< Hardware Group Count for VK for Gfx9 family
extern const unsigned int HWVKSQGroupCountGfx9; ///< Hardware SQ Group Count for VK for Gfx9 family
extern const unsigned int HWVKSQIsolatedGroupCountGfx9; ///< Hardware Isolated Group Count for VK for Gfx9 family

#endif // _GPA_INTERNAL_COUNTERS_VK_GFX9_H_
