//==============================================================================
// Copyright (c) 2010-2017 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  HSA internal counter definitions for GFX7
//==============================================================================

#ifndef _GPA_INTERNAL_COUNTERS_HSA_GFX7_H_
#define _GPA_INTERNAL_COUNTERS_HSA_GFX7_H_
// This file is autogenerated by the ConvertHWEnums project

extern GPA_HardwareCounterDesc* HSACounterGroupArrayGfx7[]; ///< Array of hardware counter groups for HSA for Gfx7 family
extern GPA_CounterGroupDesc HWHSAGroupsGfx7[]; ///< Array of counter groups for HSA for Gfx7 family
extern GPA_SQCounterGroupDesc HWHSASQGroupsGfx7[]; ///< Array of SQ groups for HSA for Gfx7 family
extern const unsigned int HWHSAGroupCountGfx7; ///< Hardware Group Count for HSA for Gfx7 family
extern const unsigned int HWHSASQGroupCountGfx7; ///< Hardware SQ Group Count for HSA for Gfx7 family

#endif // _GPA_INTERNAL_COUNTERS_HSA_GFX7_H_
