## Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
cmake_minimum_required(VERSION 3.10)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(PUBLIC_COUNTER_NAMES_DX12
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx10.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx103.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx103_gfx1031_gfx1032.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx103_gfx1033.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx11.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx11_gfx1103.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx11_gfx1150.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_baffin.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_carrizo.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_ellesmere.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_fiji.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_iceland.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx8_tonga.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx9.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx9_gfx904.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx9_gfx906.txt
${CMAKE_CURRENT_LIST_DIR}/public_counter_names_dx12_gfx9_gfx909.txt)