#/ Copyright (C) Advanced Micro Devices, Inc. All rights reserved.

enable_language(CSharp)

set(CMAKE_DOTNET_TARGET_FRAMEWORK "net8.0")
set(CMAKE_DOTNET_SDK "Microsoft.NET.Sdk")
set(CMAKE_FOLDER "${CMAKE_FOLDER}/Code Generation")

set(GPA_PROJECT_NAME PublicCounterCompiler)
set(ProjectName ${GPA_PROJECT_NAME})

include(${GPA_CMAKE_MODULES_DIR}/common.cmake)

add_executable(${GPA_PROJECT_NAME})
SET_EXECUTABLE_NAME(${GPA_PROJECT_NAME})
target_sources(PublicCounterCompiler PRIVATE
    DerivedCounterDef.cs
    InternalCounterDef.cs
    Program.cs
    CounterCompiler.cs
    FileNameAndPath.cs
    GpaUtility.cs
    public_counter_definitions_gfx10.txt
    public_counter_definitions_gfx103.txt
    public_counter_definitions_gfx11.txt
    public_counter_definitions_gfx115.txt
    public_counter_definitions_gfx12.txt
)

set_target_properties(${GPA_PROJECT_NAME} PROPERTIES
    VS_GLOBAL_ROOTNAMESPACE ${GPA_PROJECT_NAME}
    VS_PACKAGE_REFERENCES "Microsoft.NETCore.App"
)

if(EXISTS ${GPA_AUTOGEN_PUBLIC_COUNTER_INPUT_FILES})
    set(API_FILE_PREFIX_GL "oglp")
    set(API_FILE_PREFIX_DX11 "dx11")
    set(API_FILE_PREFIX_DX12 "dx12")
    set(API_FILE_PREFIX_VK "vk")
    foreach(API GL DX11 DX12 VK)
        file(GLOB PUBLIC_COUNTER_NAMES_${API} CONFIGURE_DEPENDS
            ${GPA_AUTOGEN_PUBLIC_COUNTER_INPUT_FILES}/public_counter_names_${API_FILE_PREFIX_${API}}_gfx*.txt)
        target_sources(${GPA_PROJECT_NAME} PRIVATE ${PUBLIC_COUNTER_NAMES_${API}})
        if(MSVC_IDE)
            source_group("AutoGenerated\\${API}" FILES ${PUBLIC_COUNTER_NAMES_${API}})
        endif()
    endforeach()
endif()

