//==============================================================================
// Copyright (c) 2015-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for VK GFX8 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX8
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX8

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for VKGfx8 Public counter index
#define GPUTIME_PUBLIC_VK_GFX8 0
#define EXECUTIONDURATION_PUBLIC_VK_GFX8 1
#define EXECUTIONSTART_PUBLIC_VK_GFX8 2
#define EXECUTIONEND_PUBLIC_VK_GFX8 3
#define GPUBUSY_PUBLIC_VK_GFX8 4
#define GPUBUSYCYCLES_PUBLIC_VK_GFX8 5
#define TESSELLATORBUSY_PUBLIC_VK_GFX8 6
#define TESSELLATORBUSYCYCLES_PUBLIC_VK_GFX8 7
#define VSBUSY_PUBLIC_VK_GFX8 8
#define VSBUSYCYCLES_PUBLIC_VK_GFX8 9
#define VSTIME_PUBLIC_VK_GFX8 10
#define HSBUSY_PUBLIC_VK_GFX8 11
#define HSBUSYCYCLES_PUBLIC_VK_GFX8 12
#define HSTIME_PUBLIC_VK_GFX8 13
#define DSBUSY_PUBLIC_VK_GFX8 14
#define DSBUSYCYCLES_PUBLIC_VK_GFX8 15
#define DSTIME_PUBLIC_VK_GFX8 16
#define GSBUSY_PUBLIC_VK_GFX8 17
#define GSBUSYCYCLES_PUBLIC_VK_GFX8 18
#define GSTIME_PUBLIC_VK_GFX8 19
#define PSBUSY_PUBLIC_VK_GFX8 20
#define PSBUSYCYCLES_PUBLIC_VK_GFX8 21
#define PSTIME_PUBLIC_VK_GFX8 22
#define CSBUSY_PUBLIC_VK_GFX8 23
#define CSBUSYCYCLES_PUBLIC_VK_GFX8 24
#define CSTIME_PUBLIC_VK_GFX8 25
#define VSVERTICESIN_PUBLIC_VK_GFX8 26
#define VSVALUINSTCOUNT_PUBLIC_VK_GFX8 27
#define VSSALUINSTCOUNT_PUBLIC_VK_GFX8 28
#define VSVALUBUSY_PUBLIC_VK_GFX8 29
#define VSVALUBUSYCYCLES_PUBLIC_VK_GFX8 30
#define VSSALUBUSY_PUBLIC_VK_GFX8 31
#define VSSALUBUSYCYCLES_PUBLIC_VK_GFX8 32
#define HSPATCHES_PUBLIC_VK_GFX8 33
#define HSVALUINSTCOUNT_PUBLIC_VK_GFX8 34
#define HSSALUINSTCOUNT_PUBLIC_VK_GFX8 35
#define HSVALUBUSY_PUBLIC_VK_GFX8 36
#define HSVALUBUSYCYCLES_PUBLIC_VK_GFX8 37
#define HSSALUBUSY_PUBLIC_VK_GFX8 38
#define HSSALUBUSYCYCLES_PUBLIC_VK_GFX8 39
#define DSVERTICESIN_PUBLIC_VK_GFX8 40
#define DSVALUINSTCOUNT_PUBLIC_VK_GFX8 41
#define DSSALUINSTCOUNT_PUBLIC_VK_GFX8 42
#define DSVALUBUSY_PUBLIC_VK_GFX8 43
#define DSVALUBUSYCYCLES_PUBLIC_VK_GFX8 44
#define DSSALUBUSY_PUBLIC_VK_GFX8 45
#define DSSALUBUSYCYCLES_PUBLIC_VK_GFX8 46
#define GSPRIMSIN_PUBLIC_VK_GFX8 47
#define GSVERTICESOUT_PUBLIC_VK_GFX8 48
#define GSVALUINSTCOUNT_PUBLIC_VK_GFX8 49
#define GSSALUINSTCOUNT_PUBLIC_VK_GFX8 50
#define GSVALUBUSY_PUBLIC_VK_GFX8 51
#define GSVALUBUSYCYCLES_PUBLIC_VK_GFX8 52
#define GSSALUBUSY_PUBLIC_VK_GFX8 53
#define GSSALUBUSYCYCLES_PUBLIC_VK_GFX8 54
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_VK_GFX8 55
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_VK_GFX8 56
#define PRIMITIVESIN_PUBLIC_VK_GFX8 57
#define CULLEDPRIMS_PUBLIC_VK_GFX8 58
#define CLIPPEDPRIMS_PUBLIC_VK_GFX8 59
#define PASTALLEDONRASTERIZER_PUBLIC_VK_GFX8 60
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_VK_GFX8 61
#define PSPIXELSOUT_PUBLIC_VK_GFX8 62
#define PSEXPORTSTALLS_PUBLIC_VK_GFX8 63
#define PSEXPORTSTALLSCYCLES_PUBLIC_VK_GFX8 64
#define PSVALUINSTCOUNT_PUBLIC_VK_GFX8 65
#define PSSALUINSTCOUNT_PUBLIC_VK_GFX8 66
#define PSVALUBUSY_PUBLIC_VK_GFX8 67
#define PSVALUBUSYCYCLES_PUBLIC_VK_GFX8 68
#define PSSALUBUSY_PUBLIC_VK_GFX8 69
#define PSSALUBUSYCYCLES_PUBLIC_VK_GFX8 70
#define CSTHREADGROUPS_PUBLIC_VK_GFX8 71
#define CSWAVEFRONTS_PUBLIC_VK_GFX8 72
#define CSTHREADS_PUBLIC_VK_GFX8 73
#define CSTHREADGROUPSIZE_PUBLIC_VK_GFX8 74
#define CSVALUINSTS_PUBLIC_VK_GFX8 75
#define CSVALUUTILIZATION_PUBLIC_VK_GFX8 76
#define CSSALUINSTS_PUBLIC_VK_GFX8 77
#define CSVFETCHINSTS_PUBLIC_VK_GFX8 78
#define CSSFETCHINSTS_PUBLIC_VK_GFX8 79
#define CSVWRITEINSTS_PUBLIC_VK_GFX8 80
#define CSFLATVMEMINSTS_PUBLIC_VK_GFX8 81
#define CSVALUBUSY_PUBLIC_VK_GFX8 82
#define CSVALUBUSYCYCLES_PUBLIC_VK_GFX8 83
#define CSSALUBUSY_PUBLIC_VK_GFX8 84
#define CSSALUBUSYCYCLES_PUBLIC_VK_GFX8 85
#define CSMEMUNITBUSY_PUBLIC_VK_GFX8 86
#define CSMEMUNITBUSYCYCLES_PUBLIC_VK_GFX8 87
#define CSMEMUNITSTALLED_PUBLIC_VK_GFX8 88
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_VK_GFX8 89
#define CSWRITEUNITSTALLED_PUBLIC_VK_GFX8 90
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_VK_GFX8 91
#define CSGDSINSTS_PUBLIC_VK_GFX8 92
#define CSLDSINSTS_PUBLIC_VK_GFX8 93
#define CSFLATLDSINSTS_PUBLIC_VK_GFX8 94
#define CSALUSTALLEDBYLDS_PUBLIC_VK_GFX8 95
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_VK_GFX8 96
#define CSLDSBANKCONFLICT_PUBLIC_VK_GFX8 97
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_VK_GFX8 98
#define TEXUNITBUSY_PUBLIC_VK_GFX8 99
#define TEXUNITBUSYCYCLES_PUBLIC_VK_GFX8 100
#define TEXTRIFILTERINGPCT_PUBLIC_VK_GFX8 101
#define TEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX8 102
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX8 103
#define TEXVOLFILTERINGPCT_PUBLIC_VK_GFX8 104
#define TEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX8 105
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX8 106
#define TEXAVEANISOTROPY_PUBLIC_VK_GFX8 107
#define DEPTHSTENCILTESTBUSY_PUBLIC_VK_GFX8 108
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_VK_GFX8 109
#define HIZTILESACCEPTED_PUBLIC_VK_GFX8 110
#define HIZTILESACCEPTEDCOUNT_PUBLIC_VK_GFX8 111
#define HIZTILESREJECTEDCOUNT_PUBLIC_VK_GFX8 112
#define PREZTILESDETAILCULLED_PUBLIC_VK_GFX8 113
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_VK_GFX8 114
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_VK_GFX8 115
#define HIZQUADSCULLED_PUBLIC_VK_GFX8 116
#define HIZQUADSCULLEDCOUNT_PUBLIC_VK_GFX8 117
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_VK_GFX8 118
#define PREZQUADSCULLED_PUBLIC_VK_GFX8 119
#define PREZQUADSCULLEDCOUNT_PUBLIC_VK_GFX8 120
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_VK_GFX8 121
#define POSTZQUADS_PUBLIC_VK_GFX8 122
#define POSTZQUADCOUNT_PUBLIC_VK_GFX8 123
#define PREZSAMPLESPASSING_PUBLIC_VK_GFX8 124
#define PREZSAMPLESFAILINGS_PUBLIC_VK_GFX8 125
#define PREZSAMPLESFAILINGZ_PUBLIC_VK_GFX8 126
#define POSTZSAMPLESPASSING_PUBLIC_VK_GFX8 127
#define POSTZSAMPLESFAILINGS_PUBLIC_VK_GFX8 128
#define POSTZSAMPLESFAILINGZ_PUBLIC_VK_GFX8 129
#define ZUNITSTALLED_PUBLIC_VK_GFX8 130
#define ZUNITSTALLEDCYCLES_PUBLIC_VK_GFX8 131
#define DBMEMREAD_PUBLIC_VK_GFX8 132
#define DBMEMWRITTEN_PUBLIC_VK_GFX8 133
#define CBMEMREAD_PUBLIC_VK_GFX8 134
#define CBCOLORANDMASKREAD_PUBLIC_VK_GFX8 135
#define CBMEMWRITTEN_PUBLIC_VK_GFX8 136
#define CBCOLORANDMASKWRITTEN_PUBLIC_VK_GFX8 137
#define CBSLOWPIXELPCT_PUBLIC_VK_GFX8 138
#define CBSLOWPIXELCOUNT_PUBLIC_VK_GFX8 139
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_VK_GFX8 140
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_VK_GFX8 141
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_VK_GFX8 142
#define FETCHSIZE_PUBLIC_VK_GFX8 143
#define WRITESIZE_PUBLIC_VK_GFX8 144
#define CACHEHIT_PUBLIC_VK_GFX8 145
#define CACHEMISS_PUBLIC_VK_GFX8 146
#define CACHEHITCOUNT_PUBLIC_VK_GFX8 147
#define CACHEMISSCOUNT_PUBLIC_VK_GFX8 148
#define MEMUNITBUSY_PUBLIC_VK_GFX8 149
#define MEMUNITBUSYCYCLES_PUBLIC_VK_GFX8 150
#define MEMUNITSTALLED_PUBLIC_VK_GFX8 151
#define MEMUNITSTALLEDCYCLES_PUBLIC_VK_GFX8 152
#define WRITEUNITSTALLED_PUBLIC_VK_GFX8 153
#define WRITEUNITSTALLEDCYCLES_PUBLIC_VK_GFX8 154

/// Number of public counters for VK GFX8 
const size_t kVkGfx8PublicCounterCount = 155;

/// Array of public counters for VK GFX8 
extern const GpaCounterDesc kVkGfx8PublicCounters[kVkGfx8PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX8
