//==============================================================================
// Copyright (c) 2015-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for OGLP GFX10 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX10
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX10

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for OGLPGfx10 Public counter index
#define GPUTIME_PUBLIC_OGLP_GFX10 0
#define GPUBUSY_PUBLIC_OGLP_GFX10 1
#define GPUBUSYCYCLES_PUBLIC_OGLP_GFX10 2
#define TESSELLATORBUSY_PUBLIC_OGLP_GFX10 3
#define TESSELLATORBUSYCYCLES_PUBLIC_OGLP_GFX10 4
#define VSGSBUSY_PUBLIC_OGLP_GFX10 5
#define VSGSBUSYCYCLES_PUBLIC_OGLP_GFX10 6
#define VSGSTIME_PUBLIC_OGLP_GFX10 7
#define PRETESSELLATIONBUSY_PUBLIC_OGLP_GFX10 8
#define PRETESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX10 9
#define PRETESSELLATIONTIME_PUBLIC_OGLP_GFX10 10
#define POSTTESSELLATIONBUSY_PUBLIC_OGLP_GFX10 11
#define POSTTESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX10 12
#define POSTTESSELLATIONTIME_PUBLIC_OGLP_GFX10 13
#define PSBUSY_PUBLIC_OGLP_GFX10 14
#define PSBUSYCYCLES_PUBLIC_OGLP_GFX10 15
#define PSTIME_PUBLIC_OGLP_GFX10 16
#define CSBUSY_PUBLIC_OGLP_GFX10 17
#define CSBUSYCYCLES_PUBLIC_OGLP_GFX10 18
#define CSTIME_PUBLIC_OGLP_GFX10 19
#define VSGSVERTICESIN_PUBLIC_OGLP_GFX10 20
#define VSGSPRIMSIN_PUBLIC_OGLP_GFX10 21
#define GSVERTICESOUT_PUBLIC_OGLP_GFX10 22
#define VSGSVALUINSTCOUNT_PUBLIC_OGLP_GFX10 23
#define VSGSSALUINSTCOUNT_PUBLIC_OGLP_GFX10 24
#define VSGSVALUBUSY_PUBLIC_OGLP_GFX10 25
#define VSGSVALUBUSYCYCLES_PUBLIC_OGLP_GFX10 26
#define VSGSSALUBUSY_PUBLIC_OGLP_GFX10 27
#define VSGSSALUBUSYCYCLES_PUBLIC_OGLP_GFX10 28
#define PRETESSVERTICESIN_PUBLIC_OGLP_GFX10 29
#define PRETESSVALUINSTCOUNT_PUBLIC_OGLP_GFX10 30
#define PRETESSSALUINSTCOUNT_PUBLIC_OGLP_GFX10 31
#define PRETESSVALUBUSY_PUBLIC_OGLP_GFX10 32
#define PRETESSVALUBUSYCYCLES_PUBLIC_OGLP_GFX10 33
#define PRETESSSALUBUSY_PUBLIC_OGLP_GFX10 34
#define PRETESSSALUBUSYCYCLES_PUBLIC_OGLP_GFX10 35
#define POSTTESSPRIMSOUT_PUBLIC_OGLP_GFX10 36
#define POSTTESSVALUINSTCOUNT_PUBLIC_OGLP_GFX10 37
#define POSTTESSSALUINSTCOUNT_PUBLIC_OGLP_GFX10 38
#define POSTTESSVALUBUSY_PUBLIC_OGLP_GFX10 39
#define POSTTESSVALUBUSYCYCLES_PUBLIC_OGLP_GFX10 40
#define POSTTESSSALUBUSY_PUBLIC_OGLP_GFX10 41
#define POSTTESSSALUBUSYCYCLES_PUBLIC_OGLP_GFX10 42
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_OGLP_GFX10 43
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_OGLP_GFX10 44
#define PRIMITIVESIN_PUBLIC_OGLP_GFX10 45
#define CULLEDPRIMS_PUBLIC_OGLP_GFX10 46
#define CLIPPEDPRIMS_PUBLIC_OGLP_GFX10 47
#define PASTALLEDONRASTERIZER_PUBLIC_OGLP_GFX10 48
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_OGLP_GFX10 49
#define PSPIXELSOUT_PUBLIC_OGLP_GFX10 50
#define PSEXPORTSTALLS_PUBLIC_OGLP_GFX10 51
#define PSEXPORTSTALLSCYCLES_PUBLIC_OGLP_GFX10 52
#define PSVALUINSTCOUNT_PUBLIC_OGLP_GFX10 53
#define PSSALUINSTCOUNT_PUBLIC_OGLP_GFX10 54
#define PSVALUBUSY_PUBLIC_OGLP_GFX10 55
#define PSVALUBUSYCYCLES_PUBLIC_OGLP_GFX10 56
#define PSSALUBUSY_PUBLIC_OGLP_GFX10 57
#define PSSALUBUSYCYCLES_PUBLIC_OGLP_GFX10 58
#define CSTHREADGROUPS_PUBLIC_OGLP_GFX10 59
#define CSWAVEFRONTS_PUBLIC_OGLP_GFX10 60
#define CSTHREADS_PUBLIC_OGLP_GFX10 61
#define CSTHREADGROUPSIZE_PUBLIC_OGLP_GFX10 62
#define CSVALUINSTS_PUBLIC_OGLP_GFX10 63
#define CSVALUUTILIZATION_PUBLIC_OGLP_GFX10 64
#define CSSALUINSTS_PUBLIC_OGLP_GFX10 65
#define CSVFETCHINSTS_PUBLIC_OGLP_GFX10 66
#define CSSFETCHINSTS_PUBLIC_OGLP_GFX10 67
#define CSVWRITEINSTS_PUBLIC_OGLP_GFX10 68
#define CSVALUBUSY_PUBLIC_OGLP_GFX10 69
#define CSVALUBUSYCYCLES_PUBLIC_OGLP_GFX10 70
#define CSSALUBUSY_PUBLIC_OGLP_GFX10 71
#define CSSALUBUSYCYCLES_PUBLIC_OGLP_GFX10 72
#define CSMEMUNITBUSY_PUBLIC_OGLP_GFX10 73
#define CSMEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX10 74
#define CSMEMUNITSTALLED_PUBLIC_OGLP_GFX10 75
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX10 76
#define CSWRITEUNITSTALLED_PUBLIC_OGLP_GFX10 77
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX10 78
#define CSGDSINSTS_PUBLIC_OGLP_GFX10 79
#define CSLDSINSTS_PUBLIC_OGLP_GFX10 80
#define CSALUSTALLEDBYLDS_PUBLIC_OGLP_GFX10 81
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_OGLP_GFX10 82
#define CSLDSBANKCONFLICT_PUBLIC_OGLP_GFX10 83
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_OGLP_GFX10 84
#define TEXUNITBUSY_PUBLIC_OGLP_GFX10 85
#define TEXUNITBUSYCYCLES_PUBLIC_OGLP_GFX10 86
#define TEXTRIFILTERINGPCT_PUBLIC_OGLP_GFX10 87
#define TEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX10 88
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX10 89
#define TEXVOLFILTERINGPCT_PUBLIC_OGLP_GFX10 90
#define TEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX10 91
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX10 92
#define TEXAVEANISOTROPY_PUBLIC_OGLP_GFX10 93
#define DEPTHSTENCILTESTBUSY_PUBLIC_OGLP_GFX10 94
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_OGLP_GFX10 95
#define HIZTILESACCEPTED_PUBLIC_OGLP_GFX10 96
#define HIZTILESACCEPTEDCOUNT_PUBLIC_OGLP_GFX10 97
#define HIZTILESREJECTEDCOUNT_PUBLIC_OGLP_GFX10 98
#define PREZTILESDETAILCULLED_PUBLIC_OGLP_GFX10 99
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_OGLP_GFX10 100
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_OGLP_GFX10 101
#define HIZQUADSCULLED_PUBLIC_OGLP_GFX10 102
#define HIZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX10 103
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_OGLP_GFX10 104
#define PREZQUADSCULLED_PUBLIC_OGLP_GFX10 105
#define PREZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX10 106
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_OGLP_GFX10 107
#define POSTZQUADS_PUBLIC_OGLP_GFX10 108
#define POSTZQUADCOUNT_PUBLIC_OGLP_GFX10 109
#define PREZSAMPLESPASSING_PUBLIC_OGLP_GFX10 110
#define PREZSAMPLESFAILINGS_PUBLIC_OGLP_GFX10 111
#define PREZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX10 112
#define POSTZSAMPLESPASSING_PUBLIC_OGLP_GFX10 113
#define POSTZSAMPLESFAILINGS_PUBLIC_OGLP_GFX10 114
#define POSTZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX10 115
#define ZUNITSTALLED_PUBLIC_OGLP_GFX10 116
#define ZUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX10 117
#define DBMEMREAD_PUBLIC_OGLP_GFX10 118
#define DBMEMWRITTEN_PUBLIC_OGLP_GFX10 119
#define CBMEMREAD_PUBLIC_OGLP_GFX10 120
#define CBCOLORANDMASKREAD_PUBLIC_OGLP_GFX10 121
#define CBMEMWRITTEN_PUBLIC_OGLP_GFX10 122
#define CBCOLORANDMASKWRITTEN_PUBLIC_OGLP_GFX10 123
#define CBSLOWPIXELPCT_PUBLIC_OGLP_GFX10 124
#define CBSLOWPIXELCOUNT_PUBLIC_OGLP_GFX10 125
#define L0CACHEHIT_PUBLIC_OGLP_GFX10 126
#define L0CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX10 127
#define L0CACHEHITCOUNT_PUBLIC_OGLP_GFX10 128
#define L0CACHEMISSCOUNT_PUBLIC_OGLP_GFX10 129
#define L1CACHEHIT_PUBLIC_OGLP_GFX10 130
#define L1CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX10 131
#define L1CACHEHITCOUNT_PUBLIC_OGLP_GFX10 132
#define L1CACHEMISSCOUNT_PUBLIC_OGLP_GFX10 133
#define L2CACHEHIT_PUBLIC_OGLP_GFX10 134
#define L2CACHEMISS_PUBLIC_OGLP_GFX10 135
#define L2CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX10 136
#define L2CACHEHITCOUNT_PUBLIC_OGLP_GFX10 137
#define L2CACHEMISSCOUNT_PUBLIC_OGLP_GFX10 138
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_OGLP_GFX10 139
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_OGLP_GFX10 140
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_OGLP_GFX10 141
#define FETCHSIZE_PUBLIC_OGLP_GFX10 142
#define WRITESIZE_PUBLIC_OGLP_GFX10 143
#define MEMUNITBUSY_PUBLIC_OGLP_GFX10 144
#define MEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX10 145
#define MEMUNITSTALLED_PUBLIC_OGLP_GFX10 146
#define MEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX10 147
#define WRITEUNITSTALLED_PUBLIC_OGLP_GFX10 148
#define WRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX10 149

/// Number of public counters for OGLP GFX10 
const size_t kOglpGfx10PublicCounterCount = 150;

/// Array of public counters for OGLP GFX10 
extern const GpaCounterDesc kOglpGfx10PublicCounters[kOglpGfx10PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX10
