//==============================================================================
// Copyright (c) 2015-2025 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for OGLP GFX11 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX11
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX11

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for OGLPGfx11 Public counter index
// clang-format off
#define DISCRETE_GPUTIME_PUBLIC_OGLP_GFX11 0
#define DISCRETE_GPUBUSY_PUBLIC_OGLP_GFX11 1
#define DISCRETE_GPUBUSYCYCLES_PUBLIC_OGLP_GFX11 2
#define DISCRETE_TESSELLATORBUSY_PUBLIC_OGLP_GFX11 3
#define DISCRETE_TESSELLATORBUSYCYCLES_PUBLIC_OGLP_GFX11 4
#define DISCRETE_VSGSBUSY_PUBLIC_OGLP_GFX11 5
#define DISCRETE_VSGSBUSYCYCLES_PUBLIC_OGLP_GFX11 6
#define DISCRETE_VSGSTIME_PUBLIC_OGLP_GFX11 7
#define DISCRETE_PRETESSELLATIONBUSY_PUBLIC_OGLP_GFX11 8
#define DISCRETE_PRETESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX11 9
#define DISCRETE_PRETESSELLATIONTIME_PUBLIC_OGLP_GFX11 10
#define DISCRETE_POSTTESSELLATIONBUSY_PUBLIC_OGLP_GFX11 11
#define DISCRETE_POSTTESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX11 12
#define DISCRETE_POSTTESSELLATIONTIME_PUBLIC_OGLP_GFX11 13
#define DISCRETE_PSBUSY_PUBLIC_OGLP_GFX11 14
#define DISCRETE_PSBUSYCYCLES_PUBLIC_OGLP_GFX11 15
#define DISCRETE_PSTIME_PUBLIC_OGLP_GFX11 16
#define DISCRETE_CSBUSY_PUBLIC_OGLP_GFX11 17
#define DISCRETE_CSBUSYCYCLES_PUBLIC_OGLP_GFX11 18
#define DISCRETE_CSTIME_PUBLIC_OGLP_GFX11 19
#define DISCRETE_VSGSVERTICESIN_PUBLIC_OGLP_GFX11 20
#define DISCRETE_VSGSPRIMSIN_PUBLIC_OGLP_GFX11 21
#define DISCRETE_PRETESSVERTICESIN_PUBLIC_OGLP_GFX11 22
#define DISCRETE_POSTTESSPRIMSOUT_PUBLIC_OGLP_GFX11 23
#define DISCRETE_PRIMITIVEASSEMBLYBUSY_PUBLIC_OGLP_GFX11 24
#define DISCRETE_PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_OGLP_GFX11 25
#define DISCRETE_PRIMITIVESIN_PUBLIC_OGLP_GFX11 26
#define DISCRETE_CULLEDPRIMS_PUBLIC_OGLP_GFX11 27
#define DISCRETE_CLIPPEDPRIMS_PUBLIC_OGLP_GFX11 28
#define DISCRETE_PASTALLEDONRASTERIZER_PUBLIC_OGLP_GFX11 29
#define DISCRETE_PASTALLEDONRASTERIZERCYCLES_PUBLIC_OGLP_GFX11 30
#define DISCRETE_PSPIXELSOUT_PUBLIC_OGLP_GFX11 31
#define DISCRETE_PSEXPORTSTALLS_PUBLIC_OGLP_GFX11 32
#define DISCRETE_PSEXPORTSTALLSCYCLES_PUBLIC_OGLP_GFX11 33
#define DISCRETE_CSTHREADGROUPSLAUNCHED_PUBLIC_OGLP_GFX11 34
#define DISCRETE_CSWAVEFRONTSLAUNCHED_PUBLIC_OGLP_GFX11 35
#define DISCRETE_CSTHREADSLAUNCHED_PUBLIC_OGLP_GFX11 36
#define DISCRETE_CSTHREADGROUPSIZE_PUBLIC_OGLP_GFX11 37
#define DISCRETE_CSALUSTALLEDBYLDS_PUBLIC_OGLP_GFX11 38
#define DISCRETE_CSALUSTALLEDBYLDSCYCLES_PUBLIC_OGLP_GFX11 39
#define DISCRETE_CSLDSBANKCONFLICT_PUBLIC_OGLP_GFX11 40
#define DISCRETE_CSLDSBANKCONFLICTCYCLES_PUBLIC_OGLP_GFX11 41
#define DISCRETE_TEXUNITBUSY_PUBLIC_OGLP_GFX11 42
#define DISCRETE_TEXUNITBUSYCYCLES_PUBLIC_OGLP_GFX11 43
#define DISCRETE_TEXTRIFILTERINGPCT_PUBLIC_OGLP_GFX11 44
#define DISCRETE_TEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX11 45
#define DISCRETE_NOTEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX11 46
#define DISCRETE_TEXVOLFILTERINGPCT_PUBLIC_OGLP_GFX11 47
#define DISCRETE_TEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX11 48
#define DISCRETE_NOTEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX11 49
#define DISCRETE_TEXAVEANISOTROPY_PUBLIC_OGLP_GFX11 50
#define DISCRETE_DEPTHSTENCILTESTBUSY_PUBLIC_OGLP_GFX11 51
#define DISCRETE_DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_OGLP_GFX11 52
#define DISCRETE_HIZTILESACCEPTED_PUBLIC_OGLP_GFX11 53
#define DISCRETE_HIZTILESACCEPTEDCOUNT_PUBLIC_OGLP_GFX11 54
#define DISCRETE_HIZTILESREJECTEDCOUNT_PUBLIC_OGLP_GFX11 55
#define DISCRETE_PREZTILESDETAILCULLED_PUBLIC_OGLP_GFX11 56
#define DISCRETE_PREZTILESDETAILCULLEDCOUNT_PUBLIC_OGLP_GFX11 57
#define DISCRETE_PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_OGLP_GFX11 58
#define DISCRETE_HIZQUADSCULLED_PUBLIC_OGLP_GFX11 59
#define DISCRETE_HIZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX11 60
#define DISCRETE_HIZQUADSACCEPTEDCOUNT_PUBLIC_OGLP_GFX11 61
#define DISCRETE_PREZQUADSCULLED_PUBLIC_OGLP_GFX11 62
#define DISCRETE_PREZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX11 63
#define DISCRETE_PREZQUADSSURVIVINGCOUNT_PUBLIC_OGLP_GFX11 64
#define DISCRETE_POSTZQUADS_PUBLIC_OGLP_GFX11 65
#define DISCRETE_POSTZQUADCOUNT_PUBLIC_OGLP_GFX11 66
#define DISCRETE_PREZSAMPLESPASSING_PUBLIC_OGLP_GFX11 67
#define DISCRETE_PREZSAMPLESFAILINGS_PUBLIC_OGLP_GFX11 68
#define DISCRETE_PREZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX11 69
#define DISCRETE_POSTZSAMPLESPASSING_PUBLIC_OGLP_GFX11 70
#define DISCRETE_POSTZSAMPLESFAILINGS_PUBLIC_OGLP_GFX11 71
#define DISCRETE_POSTZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX11 72
#define DISCRETE_ZUNITSTALLED_PUBLIC_OGLP_GFX11 73
#define DISCRETE_ZUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 74
#define DISCRETE_DBMEMREAD_PUBLIC_OGLP_GFX11 75
#define DISCRETE_DBMEMWRITTEN_PUBLIC_OGLP_GFX11 76
#define DISCRETE_L0CACHEHIT_PUBLIC_OGLP_GFX11 77
#define DISCRETE_L0CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 78
#define DISCRETE_L0CACHEHITCOUNT_PUBLIC_OGLP_GFX11 79
#define DISCRETE_L0CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 80
#define DISCRETE_SCALARCACHEHIT_PUBLIC_OGLP_GFX11 81
#define DISCRETE_SCALARCACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 82
#define DISCRETE_SCALARCACHEHITCOUNT_PUBLIC_OGLP_GFX11 83
#define DISCRETE_SCALARCACHEMISSCOUNT_PUBLIC_OGLP_GFX11 84
#define DISCRETE_INSTCACHEHIT_PUBLIC_OGLP_GFX11 85
#define DISCRETE_INSTCACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 86
#define DISCRETE_INSTCACHEHITCOUNT_PUBLIC_OGLP_GFX11 87
#define DISCRETE_INSTCACHEMISSCOUNT_PUBLIC_OGLP_GFX11 88
#define DISCRETE_L1CACHEHIT_PUBLIC_OGLP_GFX11 89
#define DISCRETE_L1CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 90
#define DISCRETE_L1CACHEHITCOUNT_PUBLIC_OGLP_GFX11 91
#define DISCRETE_L1CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 92
#define DISCRETE_L2CACHEMISS_PUBLIC_OGLP_GFX11 93
#define DISCRETE_L2CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 94
#define DISCRETE_L2CACHEHITCOUNT_PUBLIC_OGLP_GFX11 95
#define DISCRETE_L2CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 96
#define DISCRETE_L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_OGLP_GFX11 97
#define DISCRETE_L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_OGLP_GFX11 98
#define DISCRETE_L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_OGLP_GFX11 99
#define DISCRETE_FETCHSIZE_PUBLIC_OGLP_GFX11 100
#define DISCRETE_WRITESIZE_PUBLIC_OGLP_GFX11 101
#define DISCRETE_MEMUNITBUSY_PUBLIC_OGLP_GFX11 102
#define DISCRETE_MEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX11 103
#define DISCRETE_MEMUNITSTALLED_PUBLIC_OGLP_GFX11 104
#define DISCRETE_MEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 105
#define DISCRETE_WRITEUNITSTALLED_PUBLIC_OGLP_GFX11 106
#define DISCRETE_WRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 107
#define DISCRETE_LOCALVIDMEMBYTES_PUBLIC_OGLP_GFX11 108
#define DISCRETE_PCIEBYTES_PUBLIC_OGLP_GFX11 109

/// Number of public counters for OGLP GFX11
const size_t kOglpGfx11PublicCounterCount = 110;

/// Array of public counters for OGLP GFX11
extern const GpaCounterDesc kOglpGfx11PublicCounters[kOglpGfx11PublicCounterCount];

// clang-format on
#endif
