//==============================================================================
// Copyright (c) 2015-2024 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for OGLP GFX11 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX11
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX11

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for OGLPGfx11 Public counter index
#define GPUTIME_PUBLIC_OGLP_GFX11 0
#define GPUBUSY_PUBLIC_OGLP_GFX11 1
#define GPUBUSYCYCLES_PUBLIC_OGLP_GFX11 2
#define TESSELLATORBUSY_PUBLIC_OGLP_GFX11 3
#define TESSELLATORBUSYCYCLES_PUBLIC_OGLP_GFX11 4
#define VSGSBUSY_PUBLIC_OGLP_GFX11 5
#define VSGSBUSYCYCLES_PUBLIC_OGLP_GFX11 6
#define VSGSTIME_PUBLIC_OGLP_GFX11 7
#define PRETESSELLATIONBUSY_PUBLIC_OGLP_GFX11 8
#define PRETESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX11 9
#define PRETESSELLATIONTIME_PUBLIC_OGLP_GFX11 10
#define POSTTESSELLATIONBUSY_PUBLIC_OGLP_GFX11 11
#define POSTTESSELLATIONBUSYCYCLES_PUBLIC_OGLP_GFX11 12
#define POSTTESSELLATIONTIME_PUBLIC_OGLP_GFX11 13
#define PSBUSY_PUBLIC_OGLP_GFX11 14
#define PSBUSYCYCLES_PUBLIC_OGLP_GFX11 15
#define PSTIME_PUBLIC_OGLP_GFX11 16
#define CSBUSY_PUBLIC_OGLP_GFX11 17
#define CSBUSYCYCLES_PUBLIC_OGLP_GFX11 18
#define CSTIME_PUBLIC_OGLP_GFX11 19
#define VSGSVERTICESIN_PUBLIC_OGLP_GFX11 20
#define VSGSPRIMSIN_PUBLIC_OGLP_GFX11 21
#define PRETESSVERTICESIN_PUBLIC_OGLP_GFX11 22
#define POSTTESSPRIMSOUT_PUBLIC_OGLP_GFX11 23
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_OGLP_GFX11 24
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_OGLP_GFX11 25
#define PRIMITIVESIN_PUBLIC_OGLP_GFX11 26
#define CULLEDPRIMS_PUBLIC_OGLP_GFX11 27
#define CLIPPEDPRIMS_PUBLIC_OGLP_GFX11 28
#define PASTALLEDONRASTERIZER_PUBLIC_OGLP_GFX11 29
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_OGLP_GFX11 30
#define PSPIXELSOUT_PUBLIC_OGLP_GFX11 31
#define PSEXPORTSTALLS_PUBLIC_OGLP_GFX11 32
#define PSEXPORTSTALLSCYCLES_PUBLIC_OGLP_GFX11 33
#define CSTHREADGROUPS_PUBLIC_OGLP_GFX11 34
#define CSWAVEFRONTS_PUBLIC_OGLP_GFX11 35
#define CSTHREADS_PUBLIC_OGLP_GFX11 36
#define CSTHREADGROUPSIZE_PUBLIC_OGLP_GFX11 37
#define CSMEMUNITBUSY_PUBLIC_OGLP_GFX11 38
#define CSMEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX11 39
#define CSMEMUNITSTALLED_PUBLIC_OGLP_GFX11 40
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 41
#define CSWRITEUNITSTALLED_PUBLIC_OGLP_GFX11 42
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 43
#define CSALUSTALLEDBYLDS_PUBLIC_OGLP_GFX11 44
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_OGLP_GFX11 45
#define CSLDSBANKCONFLICT_PUBLIC_OGLP_GFX11 46
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_OGLP_GFX11 47
#define TEXUNITBUSY_PUBLIC_OGLP_GFX11 48
#define TEXUNITBUSYCYCLES_PUBLIC_OGLP_GFX11 49
#define TEXTRIFILTERINGPCT_PUBLIC_OGLP_GFX11 50
#define TEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX11 51
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX11 52
#define TEXVOLFILTERINGPCT_PUBLIC_OGLP_GFX11 53
#define TEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX11 54
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX11 55
#define TEXAVEANISOTROPY_PUBLIC_OGLP_GFX11 56
#define DEPTHSTENCILTESTBUSY_PUBLIC_OGLP_GFX11 57
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_OGLP_GFX11 58
#define HIZTILESACCEPTED_PUBLIC_OGLP_GFX11 59
#define HIZTILESACCEPTEDCOUNT_PUBLIC_OGLP_GFX11 60
#define HIZTILESREJECTEDCOUNT_PUBLIC_OGLP_GFX11 61
#define PREZTILESDETAILCULLED_PUBLIC_OGLP_GFX11 62
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_OGLP_GFX11 63
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_OGLP_GFX11 64
#define HIZQUADSCULLED_PUBLIC_OGLP_GFX11 65
#define HIZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX11 66
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_OGLP_GFX11 67
#define PREZQUADSCULLED_PUBLIC_OGLP_GFX11 68
#define PREZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX11 69
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_OGLP_GFX11 70
#define POSTZQUADS_PUBLIC_OGLP_GFX11 71
#define POSTZQUADCOUNT_PUBLIC_OGLP_GFX11 72
#define PREZSAMPLESPASSING_PUBLIC_OGLP_GFX11 73
#define PREZSAMPLESFAILINGS_PUBLIC_OGLP_GFX11 74
#define PREZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX11 75
#define POSTZSAMPLESPASSING_PUBLIC_OGLP_GFX11 76
#define POSTZSAMPLESFAILINGS_PUBLIC_OGLP_GFX11 77
#define POSTZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX11 78
#define ZUNITSTALLED_PUBLIC_OGLP_GFX11 79
#define ZUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 80
#define DBMEMREAD_PUBLIC_OGLP_GFX11 81
#define DBMEMWRITTEN_PUBLIC_OGLP_GFX11 82
#define L0CACHEHIT_PUBLIC_OGLP_GFX11 83
#define L0CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 84
#define L0CACHEHITCOUNT_PUBLIC_OGLP_GFX11 85
#define L0CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 86
#define SCALARCACHEHIT_PUBLIC_OGLP_GFX11 87
#define SCALARCACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 88
#define SCALARCACHEHITCOUNT_PUBLIC_OGLP_GFX11 89
#define SCALARCACHEMISSCOUNT_PUBLIC_OGLP_GFX11 90
#define INSTCACHEHIT_PUBLIC_OGLP_GFX11 91
#define INSTCACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 92
#define INSTCACHEHITCOUNT_PUBLIC_OGLP_GFX11 93
#define INSTCACHEMISSCOUNT_PUBLIC_OGLP_GFX11 94
#define L1CACHEHIT_PUBLIC_OGLP_GFX11 95
#define L1CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 96
#define L1CACHEHITCOUNT_PUBLIC_OGLP_GFX11 97
#define L1CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 98
#define L2CACHEMISS_PUBLIC_OGLP_GFX11 99
#define L2CACHEREQUESTCOUNT_PUBLIC_OGLP_GFX11 100
#define L2CACHEHITCOUNT_PUBLIC_OGLP_GFX11 101
#define L2CACHEMISSCOUNT_PUBLIC_OGLP_GFX11 102
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_OGLP_GFX11 103
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_OGLP_GFX11 104
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_OGLP_GFX11 105
#define FETCHSIZE_PUBLIC_OGLP_GFX11 106
#define WRITESIZE_PUBLIC_OGLP_GFX11 107
#define MEMUNITBUSY_PUBLIC_OGLP_GFX11 108
#define MEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX11 109
#define MEMUNITSTALLED_PUBLIC_OGLP_GFX11 110
#define MEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 111
#define WRITEUNITSTALLED_PUBLIC_OGLP_GFX11 112
#define WRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX11 113
#define LOCALVIDMEMBYTES_PUBLIC_OGLP_GFX11 114
#define PCIEBYTES_PUBLIC_OGLP_GFX11 115

/// Number of public counters for OGLP GFX11 
const size_t kOglpGfx11PublicCounterCount = 116;

/// Array of public counters for OGLP GFX11 
extern const GpaCounterDesc kOglpGfx11PublicCounters[kOglpGfx11PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX11
