//==============================================================================
// Copyright (c) 2015-2024 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for OGLP GFX8 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX8
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX8

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for OGLPGfx8 Public counter index
#define GPUTIME_PUBLIC_OGLP_GFX8 0
#define GPUBUSY_PUBLIC_OGLP_GFX8 1
#define GPUBUSYCYCLES_PUBLIC_OGLP_GFX8 2
#define TESSELLATORBUSY_PUBLIC_OGLP_GFX8 3
#define TESSELLATORBUSYCYCLES_PUBLIC_OGLP_GFX8 4
#define VSBUSY_PUBLIC_OGLP_GFX8 5
#define VSBUSYCYCLES_PUBLIC_OGLP_GFX8 6
#define VSTIME_PUBLIC_OGLP_GFX8 7
#define HSBUSY_PUBLIC_OGLP_GFX8 8
#define HSBUSYCYCLES_PUBLIC_OGLP_GFX8 9
#define HSTIME_PUBLIC_OGLP_GFX8 10
#define DSBUSY_PUBLIC_OGLP_GFX8 11
#define DSBUSYCYCLES_PUBLIC_OGLP_GFX8 12
#define DSTIME_PUBLIC_OGLP_GFX8 13
#define GSBUSY_PUBLIC_OGLP_GFX8 14
#define GSBUSYCYCLES_PUBLIC_OGLP_GFX8 15
#define GSTIME_PUBLIC_OGLP_GFX8 16
#define PSBUSY_PUBLIC_OGLP_GFX8 17
#define PSBUSYCYCLES_PUBLIC_OGLP_GFX8 18
#define PSTIME_PUBLIC_OGLP_GFX8 19
#define CSBUSY_PUBLIC_OGLP_GFX8 20
#define CSBUSYCYCLES_PUBLIC_OGLP_GFX8 21
#define CSTIME_PUBLIC_OGLP_GFX8 22
#define VSVERTICESIN_PUBLIC_OGLP_GFX8 23
#define VSVALUINSTCOUNT_PUBLIC_OGLP_GFX8 24
#define VSSALUINSTCOUNT_PUBLIC_OGLP_GFX8 25
#define VSVALUBUSY_PUBLIC_OGLP_GFX8 26
#define VSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 27
#define VSSALUBUSY_PUBLIC_OGLP_GFX8 28
#define VSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 29
#define HSPATCHES_PUBLIC_OGLP_GFX8 30
#define HSVALUINSTCOUNT_PUBLIC_OGLP_GFX8 31
#define HSSALUINSTCOUNT_PUBLIC_OGLP_GFX8 32
#define HSVALUBUSY_PUBLIC_OGLP_GFX8 33
#define HSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 34
#define HSSALUBUSY_PUBLIC_OGLP_GFX8 35
#define HSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 36
#define DSVERTICESIN_PUBLIC_OGLP_GFX8 37
#define DSVALUINSTCOUNT_PUBLIC_OGLP_GFX8 38
#define DSSALUINSTCOUNT_PUBLIC_OGLP_GFX8 39
#define DSVALUBUSY_PUBLIC_OGLP_GFX8 40
#define DSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 41
#define DSSALUBUSY_PUBLIC_OGLP_GFX8 42
#define DSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 43
#define GSPRIMSIN_PUBLIC_OGLP_GFX8 44
#define GSVERTICESOUT_PUBLIC_OGLP_GFX8 45
#define GSVALUINSTCOUNT_PUBLIC_OGLP_GFX8 46
#define GSSALUINSTCOUNT_PUBLIC_OGLP_GFX8 47
#define GSVALUBUSY_PUBLIC_OGLP_GFX8 48
#define GSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 49
#define GSSALUBUSY_PUBLIC_OGLP_GFX8 50
#define GSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 51
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_OGLP_GFX8 52
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_OGLP_GFX8 53
#define PRIMITIVESIN_PUBLIC_OGLP_GFX8 54
#define CULLEDPRIMS_PUBLIC_OGLP_GFX8 55
#define CLIPPEDPRIMS_PUBLIC_OGLP_GFX8 56
#define PASTALLEDONRASTERIZER_PUBLIC_OGLP_GFX8 57
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_OGLP_GFX8 58
#define PSPIXELSOUT_PUBLIC_OGLP_GFX8 59
#define PSEXPORTSTALLS_PUBLIC_OGLP_GFX8 60
#define PSEXPORTSTALLSCYCLES_PUBLIC_OGLP_GFX8 61
#define PSVALUINSTCOUNT_PUBLIC_OGLP_GFX8 62
#define PSSALUINSTCOUNT_PUBLIC_OGLP_GFX8 63
#define PSVALUBUSY_PUBLIC_OGLP_GFX8 64
#define PSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 65
#define PSSALUBUSY_PUBLIC_OGLP_GFX8 66
#define PSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 67
#define CSTHREADGROUPS_PUBLIC_OGLP_GFX8 68
#define CSWAVEFRONTS_PUBLIC_OGLP_GFX8 69
#define CSTHREADS_PUBLIC_OGLP_GFX8 70
#define CSTHREADGROUPSIZE_PUBLIC_OGLP_GFX8 71
#define CSVALUINSTS_PUBLIC_OGLP_GFX8 72
#define CSVALUUTILIZATION_PUBLIC_OGLP_GFX8 73
#define CSSALUINSTS_PUBLIC_OGLP_GFX8 74
#define CSVFETCHINSTS_PUBLIC_OGLP_GFX8 75
#define CSSFETCHINSTS_PUBLIC_OGLP_GFX8 76
#define CSVWRITEINSTS_PUBLIC_OGLP_GFX8 77
#define CSFLATVMEMINSTS_PUBLIC_OGLP_GFX8 78
#define CSVALUBUSY_PUBLIC_OGLP_GFX8 79
#define CSVALUBUSYCYCLES_PUBLIC_OGLP_GFX8 80
#define CSSALUBUSY_PUBLIC_OGLP_GFX8 81
#define CSSALUBUSYCYCLES_PUBLIC_OGLP_GFX8 82
#define CSMEMUNITBUSY_PUBLIC_OGLP_GFX8 83
#define CSMEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX8 84
#define CSMEMUNITSTALLED_PUBLIC_OGLP_GFX8 85
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX8 86
#define CSWRITEUNITSTALLED_PUBLIC_OGLP_GFX8 87
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX8 88
#define CSGDSINSTS_PUBLIC_OGLP_GFX8 89
#define CSLDSINSTS_PUBLIC_OGLP_GFX8 90
#define CSFLATLDSINSTS_PUBLIC_OGLP_GFX8 91
#define CSALUSTALLEDBYLDS_PUBLIC_OGLP_GFX8 92
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_OGLP_GFX8 93
#define CSLDSBANKCONFLICT_PUBLIC_OGLP_GFX8 94
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_OGLP_GFX8 95
#define TEXUNITBUSY_PUBLIC_OGLP_GFX8 96
#define TEXUNITBUSYCYCLES_PUBLIC_OGLP_GFX8 97
#define TEXTRIFILTERINGPCT_PUBLIC_OGLP_GFX8 98
#define TEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX8 99
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX8 100
#define TEXVOLFILTERINGPCT_PUBLIC_OGLP_GFX8 101
#define TEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX8 102
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX8 103
#define TEXAVEANISOTROPY_PUBLIC_OGLP_GFX8 104
#define DEPTHSTENCILTESTBUSY_PUBLIC_OGLP_GFX8 105
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_OGLP_GFX8 106
#define HIZTILESACCEPTED_PUBLIC_OGLP_GFX8 107
#define HIZTILESACCEPTEDCOUNT_PUBLIC_OGLP_GFX8 108
#define HIZTILESREJECTEDCOUNT_PUBLIC_OGLP_GFX8 109
#define PREZTILESDETAILCULLED_PUBLIC_OGLP_GFX8 110
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_OGLP_GFX8 111
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_OGLP_GFX8 112
#define HIZQUADSCULLED_PUBLIC_OGLP_GFX8 113
#define HIZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX8 114
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_OGLP_GFX8 115
#define PREZQUADSCULLED_PUBLIC_OGLP_GFX8 116
#define PREZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX8 117
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_OGLP_GFX8 118
#define POSTZQUADS_PUBLIC_OGLP_GFX8 119
#define POSTZQUADCOUNT_PUBLIC_OGLP_GFX8 120
#define PREZSAMPLESPASSING_PUBLIC_OGLP_GFX8 121
#define PREZSAMPLESFAILINGS_PUBLIC_OGLP_GFX8 122
#define PREZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX8 123
#define POSTZSAMPLESPASSING_PUBLIC_OGLP_GFX8 124
#define POSTZSAMPLESFAILINGS_PUBLIC_OGLP_GFX8 125
#define POSTZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX8 126
#define ZUNITSTALLED_PUBLIC_OGLP_GFX8 127
#define ZUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX8 128
#define DBMEMREAD_PUBLIC_OGLP_GFX8 129
#define DBMEMWRITTEN_PUBLIC_OGLP_GFX8 130
#define CBMEMREAD_PUBLIC_OGLP_GFX8 131
#define CBCOLORANDMASKREAD_PUBLIC_OGLP_GFX8 132
#define CBMEMWRITTEN_PUBLIC_OGLP_GFX8 133
#define CBCOLORANDMASKWRITTEN_PUBLIC_OGLP_GFX8 134
#define CBSLOWPIXELPCT_PUBLIC_OGLP_GFX8 135
#define CBSLOWPIXELCOUNT_PUBLIC_OGLP_GFX8 136
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_OGLP_GFX8 137
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_OGLP_GFX8 138
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_OGLP_GFX8 139
#define FETCHSIZE_PUBLIC_OGLP_GFX8 140
#define WRITESIZE_PUBLIC_OGLP_GFX8 141
#define CACHEHIT_PUBLIC_OGLP_GFX8 142
#define CACHEMISS_PUBLIC_OGLP_GFX8 143
#define CACHEHITCOUNT_PUBLIC_OGLP_GFX8 144
#define CACHEMISSCOUNT_PUBLIC_OGLP_GFX8 145
#define MEMUNITBUSY_PUBLIC_OGLP_GFX8 146
#define MEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX8 147
#define MEMUNITSTALLED_PUBLIC_OGLP_GFX8 148
#define MEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX8 149
#define WRITEUNITSTALLED_PUBLIC_OGLP_GFX8 150
#define WRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX8 151

/// Number of public counters for OGLP GFX8 
const size_t kOglpGfx8PublicCounterCount = 152;

/// Array of public counters for OGLP GFX8 
extern const GpaCounterDesc kOglpGfx8PublicCounters[kOglpGfx8PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX8
