//==============================================================================
// Copyright (c) 2015-2025 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for VK GFX10 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX10
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX10

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for VKGfx10 Public counter index
// clang-format off
#define DISCRETE_GPUTIME_PUBLIC_VK_GFX10 0
#define DISCRETE_EXECUTIONDURATION_PUBLIC_VK_GFX10 1
#define DISCRETE_EXECUTIONSTART_PUBLIC_VK_GFX10 2
#define DISCRETE_EXECUTIONEND_PUBLIC_VK_GFX10 3
#define DISCRETE_GPUBUSY_PUBLIC_VK_GFX10 4
#define DISCRETE_GPUBUSYCYCLES_PUBLIC_VK_GFX10 5
#define DISCRETE_TESSELLATORBUSY_PUBLIC_VK_GFX10 6
#define DISCRETE_TESSELLATORBUSYCYCLES_PUBLIC_VK_GFX10 7
#define DISCRETE_VSGSBUSY_PUBLIC_VK_GFX10 8
#define DISCRETE_VSGSBUSYCYCLES_PUBLIC_VK_GFX10 9
#define DISCRETE_VSGSTIME_PUBLIC_VK_GFX10 10
#define DISCRETE_PRETESSELLATIONBUSY_PUBLIC_VK_GFX10 11
#define DISCRETE_PRETESSELLATIONBUSYCYCLES_PUBLIC_VK_GFX10 12
#define DISCRETE_PRETESSELLATIONTIME_PUBLIC_VK_GFX10 13
#define DISCRETE_POSTTESSELLATIONBUSY_PUBLIC_VK_GFX10 14
#define DISCRETE_POSTTESSELLATIONBUSYCYCLES_PUBLIC_VK_GFX10 15
#define DISCRETE_POSTTESSELLATIONTIME_PUBLIC_VK_GFX10 16
#define DISCRETE_PSBUSY_PUBLIC_VK_GFX10 17
#define DISCRETE_PSBUSYCYCLES_PUBLIC_VK_GFX10 18
#define DISCRETE_PSTIME_PUBLIC_VK_GFX10 19
#define DISCRETE_CSBUSY_PUBLIC_VK_GFX10 20
#define DISCRETE_CSBUSYCYCLES_PUBLIC_VK_GFX10 21
#define DISCRETE_CSTIME_PUBLIC_VK_GFX10 22
#define DISCRETE_GSVERTICESOUT_PUBLIC_VK_GFX10 23
#define DISCRETE_PRETESSVERTICESIN_PUBLIC_VK_GFX10 24
#define DISCRETE_PRETESSVALUINSTCOUNT_PUBLIC_VK_GFX10 25
#define DISCRETE_PRETESSSALUINSTCOUNT_PUBLIC_VK_GFX10 26
#define DISCRETE_PRETESSVALUBUSY_PUBLIC_VK_GFX10 27
#define DISCRETE_PRETESSVALUBUSYCYCLES_PUBLIC_VK_GFX10 28
#define DISCRETE_PRETESSSALUBUSY_PUBLIC_VK_GFX10 29
#define DISCRETE_PRETESSSALUBUSYCYCLES_PUBLIC_VK_GFX10 30
#define DISCRETE_POSTTESSPRIMSOUT_PUBLIC_VK_GFX10 31
#define DISCRETE_POSTTESSVALUINSTCOUNT_PUBLIC_VK_GFX10 32
#define DISCRETE_POSTTESSSALUINSTCOUNT_PUBLIC_VK_GFX10 33
#define DISCRETE_POSTTESSVALUBUSY_PUBLIC_VK_GFX10 34
#define DISCRETE_POSTTESSVALUBUSYCYCLES_PUBLIC_VK_GFX10 35
#define DISCRETE_POSTTESSSALUBUSY_PUBLIC_VK_GFX10 36
#define DISCRETE_POSTTESSSALUBUSYCYCLES_PUBLIC_VK_GFX10 37
#define DISCRETE_PRIMITIVEASSEMBLYBUSY_PUBLIC_VK_GFX10 38
#define DISCRETE_PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_VK_GFX10 39
#define DISCRETE_PRIMITIVESIN_PUBLIC_VK_GFX10 40
#define DISCRETE_CULLEDPRIMS_PUBLIC_VK_GFX10 41
#define DISCRETE_CLIPPEDPRIMS_PUBLIC_VK_GFX10 42
#define DISCRETE_PASTALLEDONRASTERIZER_PUBLIC_VK_GFX10 43
#define DISCRETE_PASTALLEDONRASTERIZERCYCLES_PUBLIC_VK_GFX10 44
#define DISCRETE_PSPIXELSOUT_PUBLIC_VK_GFX10 45
#define DISCRETE_PSEXPORTSTALLS_PUBLIC_VK_GFX10 46
#define DISCRETE_PSEXPORTSTALLSCYCLES_PUBLIC_VK_GFX10 47
#define DISCRETE_CSTHREADGROUPSLAUNCHED_PUBLIC_VK_GFX10 48
#define DISCRETE_CSWAVEFRONTSLAUNCHED_PUBLIC_VK_GFX10 49
#define DISCRETE_CSTHREADSLAUNCHED_PUBLIC_VK_GFX10 50
#define DISCRETE_CSTHREADGROUPSIZE_PUBLIC_VK_GFX10 51
#define DISCRETE_CSVALUINSTS_PUBLIC_VK_GFX10 52
#define DISCRETE_CSVALUUTILIZATION_PUBLIC_VK_GFX10 53
#define DISCRETE_CSSALUINSTS_PUBLIC_VK_GFX10 54
#define DISCRETE_CSVFETCHINSTS_PUBLIC_VK_GFX10 55
#define DISCRETE_CSSFETCHINSTS_PUBLIC_VK_GFX10 56
#define DISCRETE_CSVWRITEINSTS_PUBLIC_VK_GFX10 57
#define DISCRETE_CSVALUBUSY_PUBLIC_VK_GFX10 58
#define DISCRETE_CSVALUBUSYCYCLES_PUBLIC_VK_GFX10 59
#define DISCRETE_CSSALUBUSY_PUBLIC_VK_GFX10 60
#define DISCRETE_CSSALUBUSYCYCLES_PUBLIC_VK_GFX10 61
#define DISCRETE_CSGDSINSTS_PUBLIC_VK_GFX10 62
#define DISCRETE_CSLDSINSTS_PUBLIC_VK_GFX10 63
#define DISCRETE_CSALUSTALLEDBYLDS_PUBLIC_VK_GFX10 64
#define DISCRETE_CSALUSTALLEDBYLDSCYCLES_PUBLIC_VK_GFX10 65
#define DISCRETE_CSLDSBANKCONFLICT_PUBLIC_VK_GFX10 66
#define DISCRETE_CSLDSBANKCONFLICTCYCLES_PUBLIC_VK_GFX10 67
#define DISCRETE_TEXUNITBUSY_PUBLIC_VK_GFX10 68
#define DISCRETE_TEXUNITBUSYCYCLES_PUBLIC_VK_GFX10 69
#define DISCRETE_TEXTRIFILTERINGPCT_PUBLIC_VK_GFX10 70
#define DISCRETE_TEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX10 71
#define DISCRETE_NOTEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX10 72
#define DISCRETE_TEXVOLFILTERINGPCT_PUBLIC_VK_GFX10 73
#define DISCRETE_TEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX10 74
#define DISCRETE_NOTEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX10 75
#define DISCRETE_TEXAVEANISOTROPY_PUBLIC_VK_GFX10 76
#define DISCRETE_DEPTHSTENCILTESTBUSY_PUBLIC_VK_GFX10 77
#define DISCRETE_DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_VK_GFX10 78
#define DISCRETE_HIZTILESACCEPTED_PUBLIC_VK_GFX10 79
#define DISCRETE_HIZTILESACCEPTEDCOUNT_PUBLIC_VK_GFX10 80
#define DISCRETE_HIZTILESREJECTEDCOUNT_PUBLIC_VK_GFX10 81
#define DISCRETE_PREZTILESDETAILCULLED_PUBLIC_VK_GFX10 82
#define DISCRETE_PREZTILESDETAILCULLEDCOUNT_PUBLIC_VK_GFX10 83
#define DISCRETE_PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_VK_GFX10 84
#define DISCRETE_HIZQUADSCULLED_PUBLIC_VK_GFX10 85
#define DISCRETE_HIZQUADSCULLEDCOUNT_PUBLIC_VK_GFX10 86
#define DISCRETE_HIZQUADSACCEPTEDCOUNT_PUBLIC_VK_GFX10 87
#define DISCRETE_PREZQUADSCULLED_PUBLIC_VK_GFX10 88
#define DISCRETE_PREZQUADSCULLEDCOUNT_PUBLIC_VK_GFX10 89
#define DISCRETE_PREZQUADSSURVIVINGCOUNT_PUBLIC_VK_GFX10 90
#define DISCRETE_POSTZQUADS_PUBLIC_VK_GFX10 91
#define DISCRETE_POSTZQUADCOUNT_PUBLIC_VK_GFX10 92
#define DISCRETE_PREZSAMPLESPASSING_PUBLIC_VK_GFX10 93
#define DISCRETE_PREZSAMPLESFAILINGS_PUBLIC_VK_GFX10 94
#define DISCRETE_PREZSAMPLESFAILINGZ_PUBLIC_VK_GFX10 95
#define DISCRETE_POSTZSAMPLESPASSING_PUBLIC_VK_GFX10 96
#define DISCRETE_POSTZSAMPLESFAILINGS_PUBLIC_VK_GFX10 97
#define DISCRETE_POSTZSAMPLESFAILINGZ_PUBLIC_VK_GFX10 98
#define DISCRETE_ZUNITSTALLED_PUBLIC_VK_GFX10 99
#define DISCRETE_ZUNITSTALLEDCYCLES_PUBLIC_VK_GFX10 100
#define DISCRETE_DBMEMREAD_PUBLIC_VK_GFX10 101
#define DISCRETE_DBMEMWRITTEN_PUBLIC_VK_GFX10 102
#define DISCRETE_CBMEMREAD_PUBLIC_VK_GFX10 103
#define DISCRETE_CBCOLORANDMASKREAD_PUBLIC_VK_GFX10 104
#define DISCRETE_CBMEMWRITTEN_PUBLIC_VK_GFX10 105
#define DISCRETE_CBCOLORANDMASKWRITTEN_PUBLIC_VK_GFX10 106
#define DISCRETE_CBSLOWPIXELPCT_PUBLIC_VK_GFX10 107
#define DISCRETE_CBSLOWPIXELCOUNT_PUBLIC_VK_GFX10 108
#define DISCRETE_L0CACHEHIT_PUBLIC_VK_GFX10 109
#define DISCRETE_L0CACHEREQUESTCOUNT_PUBLIC_VK_GFX10 110
#define DISCRETE_L0CACHEHITCOUNT_PUBLIC_VK_GFX10 111
#define DISCRETE_L0CACHEMISSCOUNT_PUBLIC_VK_GFX10 112
#define DISCRETE_SCALARCACHEHIT_PUBLIC_VK_GFX10 113
#define DISCRETE_SCALARCACHEREQUESTCOUNT_PUBLIC_VK_GFX10 114
#define DISCRETE_SCALARCACHEHITCOUNT_PUBLIC_VK_GFX10 115
#define DISCRETE_SCALARCACHEMISSCOUNT_PUBLIC_VK_GFX10 116
#define DISCRETE_INSTCACHEHIT_PUBLIC_VK_GFX10 117
#define DISCRETE_INSTCACHEREQUESTCOUNT_PUBLIC_VK_GFX10 118
#define DISCRETE_INSTCACHEHITCOUNT_PUBLIC_VK_GFX10 119
#define DISCRETE_INSTCACHEMISSCOUNT_PUBLIC_VK_GFX10 120
#define DISCRETE_L1CACHEHIT_PUBLIC_VK_GFX10 121
#define DISCRETE_L1CACHEREQUESTCOUNT_PUBLIC_VK_GFX10 122
#define DISCRETE_L1CACHEHITCOUNT_PUBLIC_VK_GFX10 123
#define DISCRETE_L1CACHEMISSCOUNT_PUBLIC_VK_GFX10 124
#define DISCRETE_L2CACHEHIT_PUBLIC_VK_GFX10 125
#define DISCRETE_L2CACHEMISS_PUBLIC_VK_GFX10 126
#define DISCRETE_L2CACHEREQUESTCOUNT_PUBLIC_VK_GFX10 127
#define DISCRETE_L2CACHEHITCOUNT_PUBLIC_VK_GFX10 128
#define DISCRETE_L2CACHEMISSCOUNT_PUBLIC_VK_GFX10 129
#define DISCRETE_L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_VK_GFX10 130
#define DISCRETE_L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_VK_GFX10 131
#define DISCRETE_L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_VK_GFX10 132
#define DISCRETE_FETCHSIZE_PUBLIC_VK_GFX10 133
#define DISCRETE_WRITESIZE_PUBLIC_VK_GFX10 134
#define DISCRETE_MEMUNITBUSY_PUBLIC_VK_GFX10 135
#define DISCRETE_MEMUNITBUSYCYCLES_PUBLIC_VK_GFX10 136
#define DISCRETE_MEMUNITSTALLED_PUBLIC_VK_GFX10 137
#define DISCRETE_MEMUNITSTALLEDCYCLES_PUBLIC_VK_GFX10 138
#define DISCRETE_WRITEUNITSTALLED_PUBLIC_VK_GFX10 139
#define DISCRETE_WRITEUNITSTALLEDCYCLES_PUBLIC_VK_GFX10 140
#define DISCRETE_LOCALVIDMEMBYTES_PUBLIC_VK_GFX10 141
#define DISCRETE_PCIEBYTES_PUBLIC_VK_GFX10 142

/// Number of public counters for VK GFX10
const size_t kVkGfx10PublicCounterCount = 143;

/// Array of public counters for VK GFX10
extern const GpaCounterDesc kVkGfx10PublicCounters[kVkGfx10PublicCounterCount];

// clang-format on
#endif
