//==============================================================================
// Copyright (c) 2015-2024 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for GL GFX10 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_GL_GFX10
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_GL_GFX10

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for GLGfx10 Public counter index
#define GPUTIME_PUBLIC_GL_GFX10 0
#define GPUBUSY_PUBLIC_GL_GFX10 1
#define GPUBUSYCYCLES_PUBLIC_GL_GFX10 2
#define TESSELLATORBUSY_PUBLIC_GL_GFX10 3
#define TESSELLATORBUSYCYCLES_PUBLIC_GL_GFX10 4
#define VSGSBUSY_PUBLIC_GL_GFX10 5
#define VSGSBUSYCYCLES_PUBLIC_GL_GFX10 6
#define VSGSTIME_PUBLIC_GL_GFX10 7
#define PRETESSELLATIONBUSY_PUBLIC_GL_GFX10 8
#define PRETESSELLATIONBUSYCYCLES_PUBLIC_GL_GFX10 9
#define PRETESSELLATIONTIME_PUBLIC_GL_GFX10 10
#define POSTTESSELLATIONBUSY_PUBLIC_GL_GFX10 11
#define POSTTESSELLATIONBUSYCYCLES_PUBLIC_GL_GFX10 12
#define POSTTESSELLATIONTIME_PUBLIC_GL_GFX10 13
#define PSBUSY_PUBLIC_GL_GFX10 14
#define PSBUSYCYCLES_PUBLIC_GL_GFX10 15
#define PSTIME_PUBLIC_GL_GFX10 16
#define CSBUSY_PUBLIC_GL_GFX10 17
#define CSBUSYCYCLES_PUBLIC_GL_GFX10 18
#define CSTIME_PUBLIC_GL_GFX10 19
#define GSVERTICESOUT_PUBLIC_GL_GFX10 20
#define PRETESSVERTICESIN_PUBLIC_GL_GFX10 21
#define PRETESSVALUINSTCOUNT_PUBLIC_GL_GFX10 22
#define PRETESSSALUINSTCOUNT_PUBLIC_GL_GFX10 23
#define PRETESSVALUBUSY_PUBLIC_GL_GFX10 24
#define PRETESSVALUBUSYCYCLES_PUBLIC_GL_GFX10 25
#define PRETESSSALUBUSY_PUBLIC_GL_GFX10 26
#define PRETESSSALUBUSYCYCLES_PUBLIC_GL_GFX10 27
#define POSTTESSPRIMSOUT_PUBLIC_GL_GFX10 28
#define POSTTESSVALUINSTCOUNT_PUBLIC_GL_GFX10 29
#define POSTTESSSALUINSTCOUNT_PUBLIC_GL_GFX10 30
#define POSTTESSVALUBUSY_PUBLIC_GL_GFX10 31
#define POSTTESSVALUBUSYCYCLES_PUBLIC_GL_GFX10 32
#define POSTTESSSALUBUSY_PUBLIC_GL_GFX10 33
#define POSTTESSSALUBUSYCYCLES_PUBLIC_GL_GFX10 34
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_GL_GFX10 35
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_GL_GFX10 36
#define PRIMITIVESIN_PUBLIC_GL_GFX10 37
#define CULLEDPRIMS_PUBLIC_GL_GFX10 38
#define CLIPPEDPRIMS_PUBLIC_GL_GFX10 39
#define PASTALLEDONRASTERIZER_PUBLIC_GL_GFX10 40
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_GL_GFX10 41
#define PSPIXELSOUT_PUBLIC_GL_GFX10 42
#define PSEXPORTSTALLS_PUBLIC_GL_GFX10 43
#define PSEXPORTSTALLSCYCLES_PUBLIC_GL_GFX10 44
#define CSTHREADGROUPS_PUBLIC_GL_GFX10 45
#define CSWAVEFRONTS_PUBLIC_GL_GFX10 46
#define CSTHREADS_PUBLIC_GL_GFX10 47
#define CSTHREADGROUPSIZE_PUBLIC_GL_GFX10 48
#define CSVALUINSTS_PUBLIC_GL_GFX10 49
#define CSVALUUTILIZATION_PUBLIC_GL_GFX10 50
#define CSSALUINSTS_PUBLIC_GL_GFX10 51
#define CSVFETCHINSTS_PUBLIC_GL_GFX10 52
#define CSSFETCHINSTS_PUBLIC_GL_GFX10 53
#define CSVWRITEINSTS_PUBLIC_GL_GFX10 54
#define CSVALUBUSY_PUBLIC_GL_GFX10 55
#define CSVALUBUSYCYCLES_PUBLIC_GL_GFX10 56
#define CSSALUBUSY_PUBLIC_GL_GFX10 57
#define CSSALUBUSYCYCLES_PUBLIC_GL_GFX10 58
#define CSMEMUNITBUSY_PUBLIC_GL_GFX10 59
#define CSMEMUNITBUSYCYCLES_PUBLIC_GL_GFX10 60
#define CSMEMUNITSTALLED_PUBLIC_GL_GFX10 61
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_GL_GFX10 62
#define CSWRITEUNITSTALLED_PUBLIC_GL_GFX10 63
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_GL_GFX10 64
#define CSGDSINSTS_PUBLIC_GL_GFX10 65
#define CSLDSINSTS_PUBLIC_GL_GFX10 66
#define CSALUSTALLEDBYLDS_PUBLIC_GL_GFX10 67
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_GL_GFX10 68
#define CSLDSBANKCONFLICT_PUBLIC_GL_GFX10 69
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_GL_GFX10 70
#define TEXUNITBUSY_PUBLIC_GL_GFX10 71
#define TEXUNITBUSYCYCLES_PUBLIC_GL_GFX10 72
#define TEXTRIFILTERINGPCT_PUBLIC_GL_GFX10 73
#define TEXTRIFILTERINGCOUNT_PUBLIC_GL_GFX10 74
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_GL_GFX10 75
#define TEXVOLFILTERINGPCT_PUBLIC_GL_GFX10 76
#define TEXVOLFILTERINGCOUNT_PUBLIC_GL_GFX10 77
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_GL_GFX10 78
#define TEXAVEANISOTROPY_PUBLIC_GL_GFX10 79
#define DEPTHSTENCILTESTBUSY_PUBLIC_GL_GFX10 80
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_GL_GFX10 81
#define HIZTILESACCEPTED_PUBLIC_GL_GFX10 82
#define HIZTILESACCEPTEDCOUNT_PUBLIC_GL_GFX10 83
#define HIZTILESREJECTEDCOUNT_PUBLIC_GL_GFX10 84
#define PREZTILESDETAILCULLED_PUBLIC_GL_GFX10 85
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_GL_GFX10 86
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_GL_GFX10 87
#define HIZQUADSCULLED_PUBLIC_GL_GFX10 88
#define HIZQUADSCULLEDCOUNT_PUBLIC_GL_GFX10 89
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_GL_GFX10 90
#define PREZQUADSCULLED_PUBLIC_GL_GFX10 91
#define PREZQUADSCULLEDCOUNT_PUBLIC_GL_GFX10 92
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_GL_GFX10 93
#define POSTZQUADS_PUBLIC_GL_GFX10 94
#define POSTZQUADCOUNT_PUBLIC_GL_GFX10 95
#define PREZSAMPLESPASSING_PUBLIC_GL_GFX10 96
#define PREZSAMPLESFAILINGS_PUBLIC_GL_GFX10 97
#define PREZSAMPLESFAILINGZ_PUBLIC_GL_GFX10 98
#define POSTZSAMPLESPASSING_PUBLIC_GL_GFX10 99
#define POSTZSAMPLESFAILINGS_PUBLIC_GL_GFX10 100
#define POSTZSAMPLESFAILINGZ_PUBLIC_GL_GFX10 101
#define ZUNITSTALLED_PUBLIC_GL_GFX10 102
#define ZUNITSTALLEDCYCLES_PUBLIC_GL_GFX10 103
#define DBMEMREAD_PUBLIC_GL_GFX10 104
#define DBMEMWRITTEN_PUBLIC_GL_GFX10 105
#define CBMEMREAD_PUBLIC_GL_GFX10 106
#define CBCOLORANDMASKREAD_PUBLIC_GL_GFX10 107
#define CBMEMWRITTEN_PUBLIC_GL_GFX10 108
#define CBCOLORANDMASKWRITTEN_PUBLIC_GL_GFX10 109
#define CBSLOWPIXELPCT_PUBLIC_GL_GFX10 110
#define CBSLOWPIXELCOUNT_PUBLIC_GL_GFX10 111
#define L0CACHEHIT_PUBLIC_GL_GFX10 112
#define L0CACHEREQUESTCOUNT_PUBLIC_GL_GFX10 113
#define L0CACHEHITCOUNT_PUBLIC_GL_GFX10 114
#define L0CACHEMISSCOUNT_PUBLIC_GL_GFX10 115
#define L1CACHEHIT_PUBLIC_GL_GFX10 116
#define L1CACHEREQUESTCOUNT_PUBLIC_GL_GFX10 117
#define L1CACHEHITCOUNT_PUBLIC_GL_GFX10 118
#define L1CACHEMISSCOUNT_PUBLIC_GL_GFX10 119
#define L2CACHEHIT_PUBLIC_GL_GFX10 120
#define L2CACHEMISS_PUBLIC_GL_GFX10 121
#define L2CACHEREQUESTCOUNT_PUBLIC_GL_GFX10 122
#define L2CACHEHITCOUNT_PUBLIC_GL_GFX10 123
#define L2CACHEMISSCOUNT_PUBLIC_GL_GFX10 124
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_GL_GFX10 125
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_GL_GFX10 126
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_GL_GFX10 127
#define FETCHSIZE_PUBLIC_GL_GFX10 128
#define WRITESIZE_PUBLIC_GL_GFX10 129
#define MEMUNITBUSY_PUBLIC_GL_GFX10 130
#define MEMUNITBUSYCYCLES_PUBLIC_GL_GFX10 131
#define MEMUNITSTALLED_PUBLIC_GL_GFX10 132
#define MEMUNITSTALLEDCYCLES_PUBLIC_GL_GFX10 133
#define WRITEUNITSTALLED_PUBLIC_GL_GFX10 134
#define WRITEUNITSTALLEDCYCLES_PUBLIC_GL_GFX10 135

/// Number of public counters for GL GFX10 
const size_t kGlGfx10PublicCounterCount = 136;

/// Array of public counters for GL GFX10 
extern const GpaCounterDesc kGlGfx10PublicCounters[kGlGfx10PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_GL_GFX10
