//==============================================================================
// Copyright (c) 2015-2024 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for VK GFX9 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX9
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX9

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for VKGfx9 Public counter index
#define GPUTIME_PUBLIC_VK_GFX9 0
#define EXECUTIONDURATION_PUBLIC_VK_GFX9 1
#define EXECUTIONSTART_PUBLIC_VK_GFX9 2
#define EXECUTIONEND_PUBLIC_VK_GFX9 3
#define GPUBUSY_PUBLIC_VK_GFX9 4
#define GPUBUSYCYCLES_PUBLIC_VK_GFX9 5
#define TESSELLATORBUSY_PUBLIC_VK_GFX9 6
#define TESSELLATORBUSYCYCLES_PUBLIC_VK_GFX9 7
#define VSGSBUSY_PUBLIC_VK_GFX9 8
#define VSGSBUSYCYCLES_PUBLIC_VK_GFX9 9
#define VSGSTIME_PUBLIC_VK_GFX9 10
#define PRETESSELLATIONBUSY_PUBLIC_VK_GFX9 11
#define PRETESSELLATIONBUSYCYCLES_PUBLIC_VK_GFX9 12
#define PRETESSELLATIONTIME_PUBLIC_VK_GFX9 13
#define POSTTESSELLATIONBUSY_PUBLIC_VK_GFX9 14
#define POSTTESSELLATIONBUSYCYCLES_PUBLIC_VK_GFX9 15
#define POSTTESSELLATIONTIME_PUBLIC_VK_GFX9 16
#define PSBUSY_PUBLIC_VK_GFX9 17
#define PSBUSYCYCLES_PUBLIC_VK_GFX9 18
#define PSTIME_PUBLIC_VK_GFX9 19
#define CSBUSY_PUBLIC_VK_GFX9 20
#define CSBUSYCYCLES_PUBLIC_VK_GFX9 21
#define CSTIME_PUBLIC_VK_GFX9 22
#define VSGSVERTICESIN_PUBLIC_VK_GFX9 23
#define VSGSPRIMSIN_PUBLIC_VK_GFX9 24
#define GSVERTICESOUT_PUBLIC_VK_GFX9 25
#define VSGSVALUINSTCOUNT_PUBLIC_VK_GFX9 26
#define VSGSSALUINSTCOUNT_PUBLIC_VK_GFX9 27
#define VSGSVALUBUSY_PUBLIC_VK_GFX9 28
#define VSGSVALUBUSYCYCLES_PUBLIC_VK_GFX9 29
#define VSGSSALUBUSY_PUBLIC_VK_GFX9 30
#define VSGSSALUBUSYCYCLES_PUBLIC_VK_GFX9 31
#define PRETESSVERTICESIN_PUBLIC_VK_GFX9 32
#define PRETESSVALUINSTCOUNT_PUBLIC_VK_GFX9 33
#define PRETESSSALUINSTCOUNT_PUBLIC_VK_GFX9 34
#define PRETESSVALUBUSY_PUBLIC_VK_GFX9 35
#define PRETESSVALUBUSYCYCLES_PUBLIC_VK_GFX9 36
#define PRETESSSALUBUSY_PUBLIC_VK_GFX9 37
#define PRETESSSALUBUSYCYCLES_PUBLIC_VK_GFX9 38
#define POSTTESSPRIMSOUT_PUBLIC_VK_GFX9 39
#define POSTTESSVALUINSTCOUNT_PUBLIC_VK_GFX9 40
#define POSTTESSSALUINSTCOUNT_PUBLIC_VK_GFX9 41
#define POSTTESSVALUBUSY_PUBLIC_VK_GFX9 42
#define POSTTESSVALUBUSYCYCLES_PUBLIC_VK_GFX9 43
#define POSTTESSSALUBUSY_PUBLIC_VK_GFX9 44
#define POSTTESSSALUBUSYCYCLES_PUBLIC_VK_GFX9 45
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_VK_GFX9 46
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_VK_GFX9 47
#define PRIMITIVESIN_PUBLIC_VK_GFX9 48
#define CULLEDPRIMS_PUBLIC_VK_GFX9 49
#define CLIPPEDPRIMS_PUBLIC_VK_GFX9 50
#define PASTALLEDONRASTERIZER_PUBLIC_VK_GFX9 51
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_VK_GFX9 52
#define PSPIXELSOUT_PUBLIC_VK_GFX9 53
#define PSEXPORTSTALLS_PUBLIC_VK_GFX9 54
#define PSEXPORTSTALLSCYCLES_PUBLIC_VK_GFX9 55
#define PSVALUINSTCOUNT_PUBLIC_VK_GFX9 56
#define PSSALUINSTCOUNT_PUBLIC_VK_GFX9 57
#define PSVALUBUSY_PUBLIC_VK_GFX9 58
#define PSVALUBUSYCYCLES_PUBLIC_VK_GFX9 59
#define PSSALUBUSY_PUBLIC_VK_GFX9 60
#define PSSALUBUSYCYCLES_PUBLIC_VK_GFX9 61
#define CSTHREADGROUPS_PUBLIC_VK_GFX9 62
#define CSWAVEFRONTS_PUBLIC_VK_GFX9 63
#define CSTHREADS_PUBLIC_VK_GFX9 64
#define CSTHREADGROUPSIZE_PUBLIC_VK_GFX9 65
#define CSVALUINSTS_PUBLIC_VK_GFX9 66
#define CSVALUUTILIZATION_PUBLIC_VK_GFX9 67
#define CSSALUINSTS_PUBLIC_VK_GFX9 68
#define CSVFETCHINSTS_PUBLIC_VK_GFX9 69
#define CSSFETCHINSTS_PUBLIC_VK_GFX9 70
#define CSVWRITEINSTS_PUBLIC_VK_GFX9 71
#define CSFLATVMEMINSTS_PUBLIC_VK_GFX9 72
#define CSVALUBUSY_PUBLIC_VK_GFX9 73
#define CSVALUBUSYCYCLES_PUBLIC_VK_GFX9 74
#define CSSALUBUSY_PUBLIC_VK_GFX9 75
#define CSSALUBUSYCYCLES_PUBLIC_VK_GFX9 76
#define CSMEMUNITBUSY_PUBLIC_VK_GFX9 77
#define CSMEMUNITBUSYCYCLES_PUBLIC_VK_GFX9 78
#define CSMEMUNITSTALLED_PUBLIC_VK_GFX9 79
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_VK_GFX9 80
#define CSWRITEUNITSTALLED_PUBLIC_VK_GFX9 81
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_VK_GFX9 82
#define CSGDSINSTS_PUBLIC_VK_GFX9 83
#define CSLDSINSTS_PUBLIC_VK_GFX9 84
#define CSFLATLDSINSTS_PUBLIC_VK_GFX9 85
#define CSALUSTALLEDBYLDS_PUBLIC_VK_GFX9 86
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_VK_GFX9 87
#define CSLDSBANKCONFLICT_PUBLIC_VK_GFX9 88
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_VK_GFX9 89
#define TEXUNITBUSY_PUBLIC_VK_GFX9 90
#define TEXUNITBUSYCYCLES_PUBLIC_VK_GFX9 91
#define TEXTRIFILTERINGPCT_PUBLIC_VK_GFX9 92
#define TEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX9 93
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_VK_GFX9 94
#define TEXVOLFILTERINGPCT_PUBLIC_VK_GFX9 95
#define TEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX9 96
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_VK_GFX9 97
#define TEXAVEANISOTROPY_PUBLIC_VK_GFX9 98
#define DEPTHSTENCILTESTBUSY_PUBLIC_VK_GFX9 99
#define DEPTHSTENCILTESTBUSYCYCLES_PUBLIC_VK_GFX9 100
#define HIZTILESACCEPTED_PUBLIC_VK_GFX9 101
#define HIZTILESACCEPTEDCOUNT_PUBLIC_VK_GFX9 102
#define HIZTILESREJECTEDCOUNT_PUBLIC_VK_GFX9 103
#define PREZTILESDETAILCULLED_PUBLIC_VK_GFX9 104
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_VK_GFX9 105
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_VK_GFX9 106
#define HIZQUADSCULLED_PUBLIC_VK_GFX9 107
#define HIZQUADSCULLEDCOUNT_PUBLIC_VK_GFX9 108
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_VK_GFX9 109
#define PREZQUADSCULLED_PUBLIC_VK_GFX9 110
#define PREZQUADSCULLEDCOUNT_PUBLIC_VK_GFX9 111
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_VK_GFX9 112
#define POSTZQUADS_PUBLIC_VK_GFX9 113
#define POSTZQUADCOUNT_PUBLIC_VK_GFX9 114
#define PREZSAMPLESPASSING_PUBLIC_VK_GFX9 115
#define PREZSAMPLESFAILINGS_PUBLIC_VK_GFX9 116
#define PREZSAMPLESFAILINGZ_PUBLIC_VK_GFX9 117
#define POSTZSAMPLESPASSING_PUBLIC_VK_GFX9 118
#define POSTZSAMPLESFAILINGS_PUBLIC_VK_GFX9 119
#define POSTZSAMPLESFAILINGZ_PUBLIC_VK_GFX9 120
#define ZUNITSTALLED_PUBLIC_VK_GFX9 121
#define ZUNITSTALLEDCYCLES_PUBLIC_VK_GFX9 122
#define DBMEMREAD_PUBLIC_VK_GFX9 123
#define DBMEMWRITTEN_PUBLIC_VK_GFX9 124
#define CBMEMREAD_PUBLIC_VK_GFX9 125
#define CBCOLORANDMASKREAD_PUBLIC_VK_GFX9 126
#define CBMEMWRITTEN_PUBLIC_VK_GFX9 127
#define CBCOLORANDMASKWRITTEN_PUBLIC_VK_GFX9 128
#define CBSLOWPIXELPCT_PUBLIC_VK_GFX9 129
#define CBSLOWPIXELCOUNT_PUBLIC_VK_GFX9 130
#define L0TAGCONFLICTREADSTALLEDCYCLES_PUBLIC_VK_GFX9 131
#define L0TAGCONFLICTWRITESTALLEDCYCLES_PUBLIC_VK_GFX9 132
#define L0TAGCONFLICTATOMICSTALLEDCYCLES_PUBLIC_VK_GFX9 133
#define FETCHSIZE_PUBLIC_VK_GFX9 134
#define WRITESIZE_PUBLIC_VK_GFX9 135
#define L1CACHEHIT_PUBLIC_VK_GFX9 136
#define L1CACHEHITCOUNT_PUBLIC_VK_GFX9 137
#define L1CACHEMISSCOUNT_PUBLIC_VK_GFX9 138
#define L2CACHEHIT_PUBLIC_VK_GFX9 139
#define L2CACHEMISS_PUBLIC_VK_GFX9 140
#define L2CACHEHITCOUNT_PUBLIC_VK_GFX9 141
#define L2CACHEMISSCOUNT_PUBLIC_VK_GFX9 142
#define MEMUNITBUSY_PUBLIC_VK_GFX9 143
#define MEMUNITBUSYCYCLES_PUBLIC_VK_GFX9 144
#define MEMUNITSTALLED_PUBLIC_VK_GFX9 145
#define MEMUNITSTALLEDCYCLES_PUBLIC_VK_GFX9 146
#define WRITEUNITSTALLED_PUBLIC_VK_GFX9 147
#define WRITEUNITSTALLEDCYCLES_PUBLIC_VK_GFX9 148
#define LOCALVIDMEMBYTES_PUBLIC_VK_GFX9 149
#define PCIEBYTES_PUBLIC_VK_GFX9 150

/// Number of public counters for VK GFX9 
const size_t kVkGfx9PublicCounterCount = 151;

/// Array of public counters for VK GFX9 
extern const GpaCounterDesc kVkGfx9PublicCounters[kVkGfx9PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_VK_GFX9
