//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx11
{

    static constexpr std::array kGl2c0CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C0_PERF_SEL_REQ", "GL2C0", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C0_PERF_SEL_MISS", "GL2C0", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C0_PERF_SEL_MC_WRREQ", "GL2C0", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C0_PERF_SEL_EA_WRREQ_64B", "GL2C0", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C0_PERF_SEL_MC_WRREQ_STALL", "GL2C0", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C0_PERF_SEL_EA_RDREQ_32B", "GL2C0", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C0_PERF_SEL_EA_RDREQ_64B", "GL2C0", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C0_PERF_SEL_EA_RDREQ_96B", "GL2C0", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C0_PERF_SEL_EA_RDREQ_128B", "GL2C0", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c0CountersGfx11 = kGl2c0CountersGfx11Data;

    static constexpr std::array kGl2c1CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C1_PERF_SEL_REQ", "GL2C1", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C1_PERF_SEL_MISS", "GL2C1", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C1_PERF_SEL_MC_WRREQ", "GL2C1", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C1_PERF_SEL_EA_WRREQ_64B", "GL2C1", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C1_PERF_SEL_MC_WRREQ_STALL", "GL2C1", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C1_PERF_SEL_EA_RDREQ_32B", "GL2C1", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C1_PERF_SEL_EA_RDREQ_64B", "GL2C1", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C1_PERF_SEL_EA_RDREQ_96B", "GL2C1", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C1_PERF_SEL_EA_RDREQ_128B", "GL2C1", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c1CountersGfx11 = kGl2c1CountersGfx11Data;

    static constexpr std::array kGl2c2CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C2_PERF_SEL_REQ", "GL2C2", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C2_PERF_SEL_MISS", "GL2C2", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C2_PERF_SEL_MC_WRREQ", "GL2C2", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C2_PERF_SEL_EA_WRREQ_64B", "GL2C2", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C2_PERF_SEL_MC_WRREQ_STALL", "GL2C2", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C2_PERF_SEL_EA_RDREQ_32B", "GL2C2", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C2_PERF_SEL_EA_RDREQ_64B", "GL2C2", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C2_PERF_SEL_EA_RDREQ_96B", "GL2C2", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C2_PERF_SEL_EA_RDREQ_128B", "GL2C2", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c2CountersGfx11 = kGl2c2CountersGfx11Data;

    static constexpr std::array kGl2c3CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C3_PERF_SEL_REQ", "GL2C3", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C3_PERF_SEL_MISS", "GL2C3", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C3_PERF_SEL_MC_WRREQ", "GL2C3", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C3_PERF_SEL_EA_WRREQ_64B", "GL2C3", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C3_PERF_SEL_MC_WRREQ_STALL", "GL2C3", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C3_PERF_SEL_EA_RDREQ_32B", "GL2C3", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C3_PERF_SEL_EA_RDREQ_64B", "GL2C3", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C3_PERF_SEL_EA_RDREQ_96B", "GL2C3", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C3_PERF_SEL_EA_RDREQ_128B", "GL2C3", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c3CountersGfx11 = kGl2c3CountersGfx11Data;

    static constexpr std::array kGl2c4CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C4_PERF_SEL_REQ", "GL2C4", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C4_PERF_SEL_MISS", "GL2C4", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C4_PERF_SEL_MC_WRREQ", "GL2C4", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C4_PERF_SEL_EA_WRREQ_64B", "GL2C4", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C4_PERF_SEL_MC_WRREQ_STALL", "GL2C4", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C4_PERF_SEL_EA_RDREQ_32B", "GL2C4", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C4_PERF_SEL_EA_RDREQ_64B", "GL2C4", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C4_PERF_SEL_EA_RDREQ_96B", "GL2C4", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C4_PERF_SEL_EA_RDREQ_128B", "GL2C4", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c4CountersGfx11 = kGl2c4CountersGfx11Data;

    static constexpr std::array kGl2c5CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C5_PERF_SEL_REQ", "GL2C5", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C5_PERF_SEL_MISS", "GL2C5", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C5_PERF_SEL_MC_WRREQ", "GL2C5", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C5_PERF_SEL_EA_WRREQ_64B", "GL2C5", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C5_PERF_SEL_MC_WRREQ_STALL", "GL2C5", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C5_PERF_SEL_EA_RDREQ_32B", "GL2C5", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C5_PERF_SEL_EA_RDREQ_64B", "GL2C5", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C5_PERF_SEL_EA_RDREQ_96B", "GL2C5", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C5_PERF_SEL_EA_RDREQ_128B", "GL2C5", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c5CountersGfx11 = kGl2c5CountersGfx11Data;

    static constexpr std::array kGl2c6CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C6_PERF_SEL_REQ", "GL2C6", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C6_PERF_SEL_MISS", "GL2C6", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C6_PERF_SEL_MC_WRREQ", "GL2C6", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C6_PERF_SEL_EA_WRREQ_64B", "GL2C6", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C6_PERF_SEL_MC_WRREQ_STALL", "GL2C6", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C6_PERF_SEL_EA_RDREQ_32B", "GL2C6", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C6_PERF_SEL_EA_RDREQ_64B", "GL2C6", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C6_PERF_SEL_EA_RDREQ_96B", "GL2C6", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C6_PERF_SEL_EA_RDREQ_128B", "GL2C6", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c6CountersGfx11 = kGl2c6CountersGfx11Data;

    static constexpr std::array kGl2c7CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C7_PERF_SEL_REQ", "GL2C7", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C7_PERF_SEL_MISS", "GL2C7", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C7_PERF_SEL_MC_WRREQ", "GL2C7", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C7_PERF_SEL_EA_WRREQ_64B", "GL2C7", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C7_PERF_SEL_MC_WRREQ_STALL", "GL2C7", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C7_PERF_SEL_EA_RDREQ_32B", "GL2C7", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C7_PERF_SEL_EA_RDREQ_64B", "GL2C7", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C7_PERF_SEL_EA_RDREQ_96B", "GL2C7", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C7_PERF_SEL_EA_RDREQ_128B", "GL2C7", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c7CountersGfx11 = kGl2c7CountersGfx11Data;

    static constexpr std::array kGl2c8CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C8_PERF_SEL_REQ", "GL2C8", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C8_PERF_SEL_MISS", "GL2C8", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C8_PERF_SEL_MC_WRREQ", "GL2C8", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C8_PERF_SEL_EA_WRREQ_64B", "GL2C8", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C8_PERF_SEL_MC_WRREQ_STALL", "GL2C8", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C8_PERF_SEL_EA_RDREQ_32B", "GL2C8", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C8_PERF_SEL_EA_RDREQ_64B", "GL2C8", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C8_PERF_SEL_EA_RDREQ_96B", "GL2C8", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C8_PERF_SEL_EA_RDREQ_128B", "GL2C8", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c8CountersGfx11 = kGl2c8CountersGfx11Data;

    static constexpr std::array kGl2c9CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C9_PERF_SEL_REQ", "GL2C9", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C9_PERF_SEL_MISS", "GL2C9", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C9_PERF_SEL_MC_WRREQ", "GL2C9", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C9_PERF_SEL_EA_WRREQ_64B", "GL2C9", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C9_PERF_SEL_MC_WRREQ_STALL", "GL2C9", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C9_PERF_SEL_EA_RDREQ_32B", "GL2C9", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C9_PERF_SEL_EA_RDREQ_64B", "GL2C9", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C9_PERF_SEL_EA_RDREQ_96B", "GL2C9", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C9_PERF_SEL_EA_RDREQ_128B", "GL2C9", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c9CountersGfx11 = kGl2c9CountersGfx11Data;

    static constexpr std::array kGl2c10CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C10_PERF_SEL_REQ", "GL2C10", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C10_PERF_SEL_MISS", "GL2C10", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C10_PERF_SEL_MC_WRREQ", "GL2C10", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C10_PERF_SEL_EA_WRREQ_64B", "GL2C10", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C10_PERF_SEL_MC_WRREQ_STALL", "GL2C10", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C10_PERF_SEL_EA_RDREQ_32B", "GL2C10", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C10_PERF_SEL_EA_RDREQ_64B", "GL2C10", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C10_PERF_SEL_EA_RDREQ_96B", "GL2C10", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C10_PERF_SEL_EA_RDREQ_128B", "GL2C10", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c10CountersGfx11 = kGl2c10CountersGfx11Data;

    static constexpr std::array kGl2c11CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C11_PERF_SEL_REQ", "GL2C11", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C11_PERF_SEL_MISS", "GL2C11", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C11_PERF_SEL_MC_WRREQ", "GL2C11", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C11_PERF_SEL_EA_WRREQ_64B", "GL2C11", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C11_PERF_SEL_MC_WRREQ_STALL", "GL2C11", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C11_PERF_SEL_EA_RDREQ_32B", "GL2C11", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C11_PERF_SEL_EA_RDREQ_64B", "GL2C11", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C11_PERF_SEL_EA_RDREQ_96B", "GL2C11", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C11_PERF_SEL_EA_RDREQ_128B", "GL2C11", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c11CountersGfx11 = kGl2c11CountersGfx11Data;

    static constexpr std::array kGl2c12CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C12_PERF_SEL_REQ", "GL2C12", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C12_PERF_SEL_MISS", "GL2C12", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C12_PERF_SEL_MC_WRREQ", "GL2C12", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C12_PERF_SEL_EA_WRREQ_64B", "GL2C12", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C12_PERF_SEL_MC_WRREQ_STALL", "GL2C12", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C12_PERF_SEL_EA_RDREQ_32B", "GL2C12", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C12_PERF_SEL_EA_RDREQ_64B", "GL2C12", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C12_PERF_SEL_EA_RDREQ_96B", "GL2C12", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C12_PERF_SEL_EA_RDREQ_128B", "GL2C12", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c12CountersGfx11 = kGl2c12CountersGfx11Data;

    static constexpr std::array kGl2c13CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C13_PERF_SEL_REQ", "GL2C13", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C13_PERF_SEL_MISS", "GL2C13", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C13_PERF_SEL_MC_WRREQ", "GL2C13", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C13_PERF_SEL_EA_WRREQ_64B", "GL2C13", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C13_PERF_SEL_MC_WRREQ_STALL", "GL2C13", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C13_PERF_SEL_EA_RDREQ_32B", "GL2C13", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C13_PERF_SEL_EA_RDREQ_64B", "GL2C13", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C13_PERF_SEL_EA_RDREQ_96B", "GL2C13", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C13_PERF_SEL_EA_RDREQ_128B", "GL2C13", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c13CountersGfx11 = kGl2c13CountersGfx11Data;

    static constexpr std::array kGl2c14CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C14_PERF_SEL_REQ", "GL2C14", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C14_PERF_SEL_MISS", "GL2C14", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C14_PERF_SEL_MC_WRREQ", "GL2C14", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C14_PERF_SEL_EA_WRREQ_64B", "GL2C14", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C14_PERF_SEL_MC_WRREQ_STALL", "GL2C14", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C14_PERF_SEL_EA_RDREQ_32B", "GL2C14", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C14_PERF_SEL_EA_RDREQ_64B", "GL2C14", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C14_PERF_SEL_EA_RDREQ_96B", "GL2C14", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C14_PERF_SEL_EA_RDREQ_128B", "GL2C14", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c14CountersGfx11 = kGl2c14CountersGfx11Data;

    static constexpr std::array kGl2c15CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C15_PERF_SEL_REQ", "GL2C15", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C15_PERF_SEL_MISS", "GL2C15", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C15_PERF_SEL_MC_WRREQ", "GL2C15", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C15_PERF_SEL_EA_WRREQ_64B", "GL2C15", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C15_PERF_SEL_MC_WRREQ_STALL", "GL2C15", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C15_PERF_SEL_EA_RDREQ_32B", "GL2C15", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C15_PERF_SEL_EA_RDREQ_64B", "GL2C15", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C15_PERF_SEL_EA_RDREQ_96B", "GL2C15", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C15_PERF_SEL_EA_RDREQ_128B", "GL2C15", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c15CountersGfx11 = kGl2c15CountersGfx11Data;

    static constexpr std::array kGl2c16CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C16_PERF_SEL_REQ", "GL2C16", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C16_PERF_SEL_MISS", "GL2C16", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C16_PERF_SEL_MC_WRREQ", "GL2C16", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C16_PERF_SEL_EA_WRREQ_64B", "GL2C16", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C16_PERF_SEL_MC_WRREQ_STALL", "GL2C16", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C16_PERF_SEL_EA_RDREQ_32B", "GL2C16", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C16_PERF_SEL_EA_RDREQ_64B", "GL2C16", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C16_PERF_SEL_EA_RDREQ_96B", "GL2C16", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C16_PERF_SEL_EA_RDREQ_128B", "GL2C16", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c16CountersGfx11 = kGl2c16CountersGfx11Data;

    static constexpr std::array kGl2c17CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C17_PERF_SEL_REQ", "GL2C17", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C17_PERF_SEL_MISS", "GL2C17", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C17_PERF_SEL_MC_WRREQ", "GL2C17", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C17_PERF_SEL_EA_WRREQ_64B", "GL2C17", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C17_PERF_SEL_MC_WRREQ_STALL", "GL2C17", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C17_PERF_SEL_EA_RDREQ_32B", "GL2C17", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C17_PERF_SEL_EA_RDREQ_64B", "GL2C17", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C17_PERF_SEL_EA_RDREQ_96B", "GL2C17", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C17_PERF_SEL_EA_RDREQ_128B", "GL2C17", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c17CountersGfx11 = kGl2c17CountersGfx11Data;

    static constexpr std::array kGl2c18CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C18_PERF_SEL_REQ", "GL2C18", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C18_PERF_SEL_MISS", "GL2C18", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C18_PERF_SEL_MC_WRREQ", "GL2C18", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C18_PERF_SEL_EA_WRREQ_64B", "GL2C18", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C18_PERF_SEL_MC_WRREQ_STALL", "GL2C18", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C18_PERF_SEL_EA_RDREQ_32B", "GL2C18", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C18_PERF_SEL_EA_RDREQ_64B", "GL2C18", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C18_PERF_SEL_EA_RDREQ_96B", "GL2C18", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C18_PERF_SEL_EA_RDREQ_128B", "GL2C18", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c18CountersGfx11 = kGl2c18CountersGfx11Data;

    static constexpr std::array kGl2c19CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C19_PERF_SEL_REQ", "GL2C19", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C19_PERF_SEL_MISS", "GL2C19", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C19_PERF_SEL_MC_WRREQ", "GL2C19", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C19_PERF_SEL_EA_WRREQ_64B", "GL2C19", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C19_PERF_SEL_MC_WRREQ_STALL", "GL2C19", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C19_PERF_SEL_EA_RDREQ_32B", "GL2C19", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C19_PERF_SEL_EA_RDREQ_64B", "GL2C19", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C19_PERF_SEL_EA_RDREQ_96B", "GL2C19", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C19_PERF_SEL_EA_RDREQ_128B", "GL2C19", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c19CountersGfx11 = kGl2c19CountersGfx11Data;

    static constexpr std::array kGl2c20CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C20_PERF_SEL_REQ", "GL2C20", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C20_PERF_SEL_MISS", "GL2C20", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C20_PERF_SEL_MC_WRREQ", "GL2C20", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C20_PERF_SEL_EA_WRREQ_64B", "GL2C20", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C20_PERF_SEL_MC_WRREQ_STALL", "GL2C20", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C20_PERF_SEL_EA_RDREQ_32B", "GL2C20", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C20_PERF_SEL_EA_RDREQ_64B", "GL2C20", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C20_PERF_SEL_EA_RDREQ_96B", "GL2C20", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C20_PERF_SEL_EA_RDREQ_128B", "GL2C20", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c20CountersGfx11 = kGl2c20CountersGfx11Data;

    static constexpr std::array kGl2c21CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C21_PERF_SEL_REQ", "GL2C21", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C21_PERF_SEL_MISS", "GL2C21", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C21_PERF_SEL_MC_WRREQ", "GL2C21", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C21_PERF_SEL_EA_WRREQ_64B", "GL2C21", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C21_PERF_SEL_MC_WRREQ_STALL", "GL2C21", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C21_PERF_SEL_EA_RDREQ_32B", "GL2C21", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C21_PERF_SEL_EA_RDREQ_64B", "GL2C21", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C21_PERF_SEL_EA_RDREQ_96B", "GL2C21", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C21_PERF_SEL_EA_RDREQ_128B", "GL2C21", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c21CountersGfx11 = kGl2c21CountersGfx11Data;

    static constexpr std::array kGl2c22CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C22_PERF_SEL_REQ", "GL2C22", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C22_PERF_SEL_MISS", "GL2C22", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C22_PERF_SEL_MC_WRREQ", "GL2C22", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C22_PERF_SEL_EA_WRREQ_64B", "GL2C22", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C22_PERF_SEL_MC_WRREQ_STALL", "GL2C22", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C22_PERF_SEL_EA_RDREQ_32B", "GL2C22", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C22_PERF_SEL_EA_RDREQ_64B", "GL2C22", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C22_PERF_SEL_EA_RDREQ_96B", "GL2C22", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C22_PERF_SEL_EA_RDREQ_128B", "GL2C22", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c22CountersGfx11 = kGl2c22CountersGfx11Data;

    static constexpr std::array kGl2c23CountersGfx11Data = {
        GpaHardwareCounterDesc{3, "GL2C23_PERF_SEL_REQ", "GL2C23", "Number of requests of all types. This is measured at the tag block. This may be more than the number of requests arriving at the GL2C, but it is a good indication of the total amount of work that needs to be performed."},
        GpaHardwareCounterDesc{43, "GL2C23_PERF_SEL_MISS", "GL2C23", "Number of cache misses. UC reads count as misses."},
        GpaHardwareCounterDesc{83, "GL2C23_PERF_SEL_MC_WRREQ", "GL2C23", "Number of transactions (either 32-byte or 64-byte) going over the GL2C_EA_wrreq interface. Atomics may travel over the same interface and are generally classified as write requests. This does not include probe commands."},
        GpaHardwareCounterDesc{85, "GL2C23_PERF_SEL_EA_WRREQ_64B", "GL2C23", "Number of 64-byte transactions going (64-byte write or CMPSWAP) over the TC_EA_wrreq interface."},
        GpaHardwareCounterDesc{88, "GL2C23_PERF_SEL_MC_WRREQ_STALL", "GL2C23", "Number of cycles a write request was stalled."},
        GpaHardwareCounterDesc{99, "GL2C23_PERF_SEL_EA_RDREQ_32B", "GL2C23", "Number of 32-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{100, "GL2C23_PERF_SEL_EA_RDREQ_64B", "GL2C23", "Number of 64-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{101, "GL2C23_PERF_SEL_EA_RDREQ_96B", "GL2C23", "Number of 96-byte GL2C/EA read requests"},
        GpaHardwareCounterDesc{102, "GL2C23_PERF_SEL_EA_RDREQ_128B", "GL2C23", "Number of 128-byte GL2C/EA read requests"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl2c23CountersGfx11 = kGl2c23CountersGfx11Data;
} // counter_gfx11

// clang-format on
