//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx11
{

    static constexpr std::array kSqgHs0CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS0_PERF_SEL_WAVES", "SQG_HS0", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS0_PERF_SEL_WAVES_32", "SQG_HS0", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS0_PERF_SEL_ITEMS", "SQG_HS0", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs0CountersGfx11 = kSqgHs0CountersGfx11Data;

    static constexpr std::array kSqgHs1CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS1_PERF_SEL_WAVES", "SQG_HS1", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS1_PERF_SEL_WAVES_32", "SQG_HS1", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS1_PERF_SEL_ITEMS", "SQG_HS1", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs1CountersGfx11 = kSqgHs1CountersGfx11Data;

    static constexpr std::array kSqgHs2CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS2_PERF_SEL_WAVES", "SQG_HS2", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS2_PERF_SEL_WAVES_32", "SQG_HS2", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS2_PERF_SEL_ITEMS", "SQG_HS2", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs2CountersGfx11 = kSqgHs2CountersGfx11Data;

    static constexpr std::array kSqgHs3CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS3_PERF_SEL_WAVES", "SQG_HS3", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS3_PERF_SEL_WAVES_32", "SQG_HS3", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS3_PERF_SEL_ITEMS", "SQG_HS3", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs3CountersGfx11 = kSqgHs3CountersGfx11Data;

    static constexpr std::array kSqgHs4CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS4_PERF_SEL_WAVES", "SQG_HS4", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS4_PERF_SEL_WAVES_32", "SQG_HS4", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS4_PERF_SEL_ITEMS", "SQG_HS4", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs4CountersGfx11 = kSqgHs4CountersGfx11Data;

    static constexpr std::array kSqgHs5CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_HS5_PERF_SEL_WAVES", "SQG_HS5", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_HS5_PERF_SEL_WAVES_32", "SQG_HS5", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_HS5_PERF_SEL_ITEMS", "SQG_HS5", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgHs5CountersGfx11 = kSqgHs5CountersGfx11Data;
} // counter_gfx11

// clang-format on
