//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX103.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx103.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx103
{

    static constexpr std::array kPaSc0CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC0_QZ0_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC0_QZ1_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC0_QZ2_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC0_QZ3_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC0_P0_HIZ_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC0_P1_HIZ_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC0_P2_HIZ_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC0_P3_HIZ_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC0_EARLYZ_QUAD_COUNT", "PA_SC0", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc0CountersGfx103 = kPaSc0CountersGfx103Data;

    static constexpr std::array kPaSc1CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC1_QZ0_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC1_QZ1_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC1_QZ2_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC1_QZ3_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC1_P0_HIZ_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC1_P1_HIZ_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC1_P2_HIZ_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC1_P3_HIZ_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC1_EARLYZ_QUAD_COUNT", "PA_SC1", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc1CountersGfx103 = kPaSc1CountersGfx103Data;

    static constexpr std::array kPaSc2CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC2_QZ0_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC2_QZ1_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC2_QZ2_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC2_QZ3_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC2_P0_HIZ_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC2_P1_HIZ_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC2_P2_HIZ_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC2_P3_HIZ_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC2_EARLYZ_QUAD_COUNT", "PA_SC2", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc2CountersGfx103 = kPaSc2CountersGfx103Data;

    static constexpr std::array kPaSc3CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC3_QZ0_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC3_QZ1_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC3_QZ2_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC3_QZ3_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC3_P0_HIZ_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC3_P1_HIZ_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC3_P2_HIZ_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC3_P3_HIZ_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC3_EARLYZ_QUAD_COUNT", "PA_SC3", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc3CountersGfx103 = kPaSc3CountersGfx103Data;

    static constexpr std::array kPaSc4CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC4_QZ0_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC4_QZ1_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC4_QZ2_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC4_QZ3_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC4_P0_HIZ_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC4_P1_HIZ_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC4_P2_HIZ_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC4_P3_HIZ_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC4_EARLYZ_QUAD_COUNT", "PA_SC4", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc4CountersGfx103 = kPaSc4CountersGfx103Data;

    static constexpr std::array kPaSc5CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC5_QZ0_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC5_QZ1_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC5_QZ2_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC5_QZ3_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC5_P0_HIZ_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC5_P1_HIZ_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC5_P2_HIZ_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC5_P3_HIZ_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC5_EARLYZ_QUAD_COUNT", "PA_SC5", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc5CountersGfx103 = kPaSc5CountersGfx103Data;

    static constexpr std::array kPaSc6CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC6_QZ0_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC6_QZ1_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC6_QZ2_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC6_QZ3_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC6_P0_HIZ_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC6_P1_HIZ_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC6_P2_HIZ_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC6_P3_HIZ_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC6_EARLYZ_QUAD_COUNT", "PA_SC6", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc6CountersGfx103 = kPaSc6CountersGfx103Data;

    static constexpr std::array kPaSc7CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC7_QZ0_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC7_QZ1_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC7_QZ2_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC7_QZ3_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC7_P0_HIZ_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC7_P1_HIZ_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC7_P2_HIZ_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC7_P3_HIZ_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC7_EARLYZ_QUAD_COUNT", "PA_SC7", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc7CountersGfx103 = kPaSc7CountersGfx103Data;

    static constexpr std::array kPaSc8CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC8_QZ0_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC8_QZ1_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC8_QZ2_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC8_QZ3_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC8_P0_HIZ_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC8_P1_HIZ_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC8_P2_HIZ_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC8_P3_HIZ_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC8_EARLYZ_QUAD_COUNT", "PA_SC8", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc8CountersGfx103 = kPaSc8CountersGfx103Data;

    static constexpr std::array kPaSc9CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC9_QZ0_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC9_QZ1_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC9_QZ2_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC9_QZ3_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC9_P0_HIZ_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC9_P1_HIZ_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC9_P2_HIZ_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC9_P3_HIZ_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC9_EARLYZ_QUAD_COUNT", "PA_SC9", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc9CountersGfx103 = kPaSc9CountersGfx103Data;

    static constexpr std::array kPaSc10CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC10_QZ0_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC10_QZ1_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC10_QZ2_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC10_QZ3_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC10_P0_HIZ_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC10_P1_HIZ_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC10_P2_HIZ_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC10_P3_HIZ_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC10_EARLYZ_QUAD_COUNT", "PA_SC10", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc10CountersGfx103 = kPaSc10CountersGfx103Data;

    static constexpr std::array kPaSc11CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC11_QZ0_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC11_QZ1_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC11_QZ2_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC11_QZ3_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC11_P0_HIZ_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC11_P1_HIZ_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC11_P2_HIZ_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC11_P3_HIZ_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC11_EARLYZ_QUAD_COUNT", "PA_SC11", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc11CountersGfx103 = kPaSc11CountersGfx103Data;

    static constexpr std::array kPaSc12CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC12_QZ0_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC12_QZ1_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC12_QZ2_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC12_QZ3_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC12_P0_HIZ_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC12_P1_HIZ_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC12_P2_HIZ_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC12_P3_HIZ_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC12_EARLYZ_QUAD_COUNT", "PA_SC12", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc12CountersGfx103 = kPaSc12CountersGfx103Data;

    static constexpr std::array kPaSc13CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC13_QZ0_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC13_QZ1_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC13_QZ2_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC13_QZ3_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC13_P0_HIZ_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC13_P1_HIZ_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC13_P2_HIZ_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC13_P3_HIZ_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC13_EARLYZ_QUAD_COUNT", "PA_SC13", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc13CountersGfx103 = kPaSc13CountersGfx103Data;

    static constexpr std::array kPaSc14CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC14_QZ0_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC14_QZ1_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC14_QZ2_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC14_QZ3_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC14_P0_HIZ_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC14_P1_HIZ_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC14_P2_HIZ_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC14_P3_HIZ_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC14_EARLYZ_QUAD_COUNT", "PA_SC14", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc14CountersGfx103 = kPaSc14CountersGfx103Data;

    static constexpr std::array kPaSc15CountersGfx103Data = {
        GpaHardwareCounterDesc{159, "PA_SC15_QZ0_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_QZ0_QUAD_COUNT quad count; quad-z pipe 0 ;"},
        GpaHardwareCounterDesc{160, "PA_SC15_QZ1_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_QZ1_QUAD_COUNT quad count; quad-z pipe 1 ;"},
        GpaHardwareCounterDesc{161, "PA_SC15_QZ2_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_QZ2_QUAD_COUNT quad count; quad-z pipe 2 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{162, "PA_SC15_QZ3_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_QZ3_QUAD_COUNT quad count; quad-z pipe 3 DEPRECATED (NUM_DB_PER_PACKER=4 variants only)"},
        GpaHardwareCounterDesc{235, "PA_SC15_P0_HIZ_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_P0_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 0 ;"},
        GpaHardwareCounterDesc{236, "PA_SC15_P1_HIZ_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_P1_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 1 ;"},
        GpaHardwareCounterDesc{237, "PA_SC15_P2_HIZ_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_P2_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 2 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{238, "PA_SC15_P3_HIZ_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_P3_HIZ_QUAD_COUNT total quads surviving hi-z; db pipe 3 (DEPRECATED only valid for NUM_DB_PER_PACKER=4)"},
        GpaHardwareCounterDesc{259, "PA_SC15_EARLYZ_QUAD_COUNT", "PA_SC15", "SC_PERF_SEL_SC_EARLYZ_QUAD_COUNT total quads surviving early-z ;"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kPaSc15CountersGfx103 = kPaSc15CountersGfx103Data;
} // counter_gfx103

// clang-format on
