//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx11
{

    static constexpr std::array kGl1c0CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C0_PERF_SEL_REQ", "GL1C0", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C0_PERF_SEL_REQ_MISS", "GL1C0", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c0CountersGfx11 = kGl1c0CountersGfx11Data;

    static constexpr std::array kGl1c1CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C1_PERF_SEL_REQ", "GL1C1", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C1_PERF_SEL_REQ_MISS", "GL1C1", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c1CountersGfx11 = kGl1c1CountersGfx11Data;

    static constexpr std::array kGl1c2CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C2_PERF_SEL_REQ", "GL1C2", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C2_PERF_SEL_REQ_MISS", "GL1C2", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c2CountersGfx11 = kGl1c2CountersGfx11Data;

    static constexpr std::array kGl1c3CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C3_PERF_SEL_REQ", "GL1C3", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C3_PERF_SEL_REQ_MISS", "GL1C3", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c3CountersGfx11 = kGl1c3CountersGfx11Data;

    static constexpr std::array kGl1c4CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C4_PERF_SEL_REQ", "GL1C4", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C4_PERF_SEL_REQ_MISS", "GL1C4", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c4CountersGfx11 = kGl1c4CountersGfx11Data;

    static constexpr std::array kGl1c5CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C5_PERF_SEL_REQ", "GL1C5", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C5_PERF_SEL_REQ_MISS", "GL1C5", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c5CountersGfx11 = kGl1c5CountersGfx11Data;

    static constexpr std::array kGl1c6CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C6_PERF_SEL_REQ", "GL1C6", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C6_PERF_SEL_REQ_MISS", "GL1C6", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c6CountersGfx11 = kGl1c6CountersGfx11Data;

    static constexpr std::array kGl1c7CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C7_PERF_SEL_REQ", "GL1C7", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C7_PERF_SEL_REQ_MISS", "GL1C7", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c7CountersGfx11 = kGl1c7CountersGfx11Data;

    static constexpr std::array kGl1c8CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C8_PERF_SEL_REQ", "GL1C8", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C8_PERF_SEL_REQ_MISS", "GL1C8", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c8CountersGfx11 = kGl1c8CountersGfx11Data;

    static constexpr std::array kGl1c9CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C9_PERF_SEL_REQ", "GL1C9", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C9_PERF_SEL_REQ_MISS", "GL1C9", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c9CountersGfx11 = kGl1c9CountersGfx11Data;

    static constexpr std::array kGl1c10CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C10_PERF_SEL_REQ", "GL1C10", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C10_PERF_SEL_REQ_MISS", "GL1C10", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c10CountersGfx11 = kGl1c10CountersGfx11Data;

    static constexpr std::array kGl1c11CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C11_PERF_SEL_REQ", "GL1C11", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C11_PERF_SEL_REQ_MISS", "GL1C11", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c11CountersGfx11 = kGl1c11CountersGfx11Data;

    static constexpr std::array kGl1c12CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C12_PERF_SEL_REQ", "GL1C12", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C12_PERF_SEL_REQ_MISS", "GL1C12", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c12CountersGfx11 = kGl1c12CountersGfx11Data;

    static constexpr std::array kGl1c13CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C13_PERF_SEL_REQ", "GL1C13", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C13_PERF_SEL_REQ_MISS", "GL1C13", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c13CountersGfx11 = kGl1c13CountersGfx11Data;

    static constexpr std::array kGl1c14CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C14_PERF_SEL_REQ", "GL1C14", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C14_PERF_SEL_REQ_MISS", "GL1C14", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c14CountersGfx11 = kGl1c14CountersGfx11Data;

    static constexpr std::array kGl1c15CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C15_PERF_SEL_REQ", "GL1C15", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C15_PERF_SEL_REQ_MISS", "GL1C15", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c15CountersGfx11 = kGl1c15CountersGfx11Data;

    static constexpr std::array kGl1c16CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C16_PERF_SEL_REQ", "GL1C16", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C16_PERF_SEL_REQ_MISS", "GL1C16", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c16CountersGfx11 = kGl1c16CountersGfx11Data;

    static constexpr std::array kGl1c17CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C17_PERF_SEL_REQ", "GL1C17", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C17_PERF_SEL_REQ_MISS", "GL1C17", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c17CountersGfx11 = kGl1c17CountersGfx11Data;

    static constexpr std::array kGl1c18CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C18_PERF_SEL_REQ", "GL1C18", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C18_PERF_SEL_REQ_MISS", "GL1C18", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c18CountersGfx11 = kGl1c18CountersGfx11Data;

    static constexpr std::array kGl1c19CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C19_PERF_SEL_REQ", "GL1C19", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C19_PERF_SEL_REQ_MISS", "GL1C19", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c19CountersGfx11 = kGl1c19CountersGfx11Data;

    static constexpr std::array kGl1c20CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C20_PERF_SEL_REQ", "GL1C20", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C20_PERF_SEL_REQ_MISS", "GL1C20", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c20CountersGfx11 = kGl1c20CountersGfx11Data;

    static constexpr std::array kGl1c21CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C21_PERF_SEL_REQ", "GL1C21", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C21_PERF_SEL_REQ_MISS", "GL1C21", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c21CountersGfx11 = kGl1c21CountersGfx11Data;

    static constexpr std::array kGl1c22CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C22_PERF_SEL_REQ", "GL1C22", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C22_PERF_SEL_REQ_MISS", "GL1C22", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c22CountersGfx11 = kGl1c22CountersGfx11Data;

    static constexpr std::array kGl1c23CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C23_PERF_SEL_REQ", "GL1C23", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C23_PERF_SEL_REQ_MISS", "GL1C23", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c23CountersGfx11 = kGl1c23CountersGfx11Data;

    static constexpr std::array kGl1c24CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C24_PERF_SEL_REQ", "GL1C24", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C24_PERF_SEL_REQ_MISS", "GL1C24", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c24CountersGfx11 = kGl1c24CountersGfx11Data;

    static constexpr std::array kGl1c25CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C25_PERF_SEL_REQ", "GL1C25", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C25_PERF_SEL_REQ_MISS", "GL1C25", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c25CountersGfx11 = kGl1c25CountersGfx11Data;

    static constexpr std::array kGl1c26CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C26_PERF_SEL_REQ", "GL1C26", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C26_PERF_SEL_REQ_MISS", "GL1C26", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c26CountersGfx11 = kGl1c26CountersGfx11Data;

    static constexpr std::array kGl1c27CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C27_PERF_SEL_REQ", "GL1C27", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C27_PERF_SEL_REQ_MISS", "GL1C27", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c27CountersGfx11 = kGl1c27CountersGfx11Data;

    static constexpr std::array kGl1c28CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C28_PERF_SEL_REQ", "GL1C28", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C28_PERF_SEL_REQ_MISS", "GL1C28", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c28CountersGfx11 = kGl1c28CountersGfx11Data;

    static constexpr std::array kGl1c29CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C29_PERF_SEL_REQ", "GL1C29", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C29_PERF_SEL_REQ_MISS", "GL1C29", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c29CountersGfx11 = kGl1c29CountersGfx11Data;

    static constexpr std::array kGl1c30CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C30_PERF_SEL_REQ", "GL1C30", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C30_PERF_SEL_REQ_MISS", "GL1C30", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c30CountersGfx11 = kGl1c30CountersGfx11Data;

    static constexpr std::array kGl1c31CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C31_PERF_SEL_REQ", "GL1C31", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C31_PERF_SEL_REQ_MISS", "GL1C31", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c31CountersGfx11 = kGl1c31CountersGfx11Data;

    static constexpr std::array kGl1c32CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C32_PERF_SEL_REQ", "GL1C32", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C32_PERF_SEL_REQ_MISS", "GL1C32", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c32CountersGfx11 = kGl1c32CountersGfx11Data;

    static constexpr std::array kGl1c33CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C33_PERF_SEL_REQ", "GL1C33", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C33_PERF_SEL_REQ_MISS", "GL1C33", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c33CountersGfx11 = kGl1c33CountersGfx11Data;

    static constexpr std::array kGl1c34CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C34_PERF_SEL_REQ", "GL1C34", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C34_PERF_SEL_REQ_MISS", "GL1C34", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c34CountersGfx11 = kGl1c34CountersGfx11Data;

    static constexpr std::array kGl1c35CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C35_PERF_SEL_REQ", "GL1C35", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C35_PERF_SEL_REQ_MISS", "GL1C35", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c35CountersGfx11 = kGl1c35CountersGfx11Data;

    static constexpr std::array kGl1c36CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C36_PERF_SEL_REQ", "GL1C36", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C36_PERF_SEL_REQ_MISS", "GL1C36", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c36CountersGfx11 = kGl1c36CountersGfx11Data;

    static constexpr std::array kGl1c37CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C37_PERF_SEL_REQ", "GL1C37", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C37_PERF_SEL_REQ_MISS", "GL1C37", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c37CountersGfx11 = kGl1c37CountersGfx11Data;

    static constexpr std::array kGl1c38CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C38_PERF_SEL_REQ", "GL1C38", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C38_PERF_SEL_REQ_MISS", "GL1C38", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c38CountersGfx11 = kGl1c38CountersGfx11Data;

    static constexpr std::array kGl1c39CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C39_PERF_SEL_REQ", "GL1C39", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C39_PERF_SEL_REQ_MISS", "GL1C39", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c39CountersGfx11 = kGl1c39CountersGfx11Data;

    static constexpr std::array kGl1c40CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C40_PERF_SEL_REQ", "GL1C40", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C40_PERF_SEL_REQ_MISS", "GL1C40", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c40CountersGfx11 = kGl1c40CountersGfx11Data;

    static constexpr std::array kGl1c41CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C41_PERF_SEL_REQ", "GL1C41", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C41_PERF_SEL_REQ_MISS", "GL1C41", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c41CountersGfx11 = kGl1c41CountersGfx11Data;

    static constexpr std::array kGl1c42CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C42_PERF_SEL_REQ", "GL1C42", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C42_PERF_SEL_REQ_MISS", "GL1C42", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c42CountersGfx11 = kGl1c42CountersGfx11Data;

    static constexpr std::array kGl1c43CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C43_PERF_SEL_REQ", "GL1C43", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C43_PERF_SEL_REQ_MISS", "GL1C43", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c43CountersGfx11 = kGl1c43CountersGfx11Data;

    static constexpr std::array kGl1c44CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C44_PERF_SEL_REQ", "GL1C44", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C44_PERF_SEL_REQ_MISS", "GL1C44", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c44CountersGfx11 = kGl1c44CountersGfx11Data;

    static constexpr std::array kGl1c45CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C45_PERF_SEL_REQ", "GL1C45", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C45_PERF_SEL_REQ_MISS", "GL1C45", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c45CountersGfx11 = kGl1c45CountersGfx11Data;

    static constexpr std::array kGl1c46CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C46_PERF_SEL_REQ", "GL1C46", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C46_PERF_SEL_REQ_MISS", "GL1C46", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c46CountersGfx11 = kGl1c46CountersGfx11Data;

    static constexpr std::array kGl1c47CountersGfx11Data = {
        GpaHardwareCounterDesc{14, "GL1C47_PERF_SEL_REQ", "GL1C47", "Read, writes, atomics, nop. Invalids are not counted as requests."},
        GpaHardwareCounterDesc{18, "GL1C47_PERF_SEL_REQ_MISS", "GL1C47", "Count of requests that miss in the cache. Writes and atomics always miss. Partial miss counts as miss."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGl1c47CountersGfx11 = kGl1c47CountersGfx11Data;
} // counter_gfx11

// clang-format on
