//==============================================================================
// Copyright (c) 2010-2020 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  VK counter definitions for GFX9
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project

#ifndef _GPA_HW_COUNTER_VK_GFX9_H_
#define _GPA_HW_COUNTER_VK_GFX9_H_

#include <vulkan/vulkan.h>
#include <vk_amd_gpa_interface.h>

#include <set>

struct GPA_HardwareCounterDesc;
struct GPA_CounterGroupDesc;
struct GPA_SQCounterGroupDesc;

namespace countergfx9
{
    extern GPA_HardwareCounterDesc*           vk_counter_group_array_gfx9[]; ///< Array of hardware counter groups for vk for gfx9 family
    extern GPA_HardwareCounterDesc*           vk_exposed_counters_group_array_gfx9[]; ///< Array of hardware exposed counter groups for vk for gfx9 family
    extern GPA_CounterGroupDesc               hw_vk_groups_gfx9[]; ///< Array of counter groups for vk for gfx9 family
    extern GPA_CounterGroupExposedCounterDesc hw_vk_exposed_counters_by_group_gfx9[]; ///< Array of exposed counter groups for vk for gfx9 family
    extern GPA_PaddedCounterDesc              vk_padded_counter_by_group_gfx9[]; ///< Array of reserved counter for vk for gfx9 family
    extern GPA_SQCounterGroupDesc             hw_vk_sq_groups_gfx9[]; ///< Array of SQ groups for vk for gfx9 family
    extern unsigned int                       hw_vk_sq_isolated_groups_gfx9[]; ///< Array of counter groups isolated from SQ counter groups for vk for gfx9 family
    extern VkGpaPerfBlockAMD                  hw_vk_driver_enum_gfx9[]; ///< Array of driver enum values per group for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimebottomtobottomduration_index_gfx9; ///< Index of delta between the previous command reaching bottom of pipe and the current command reaching bottom of pipe, will not include latency of first data to travel through pipeline, best for large data sets. for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimebottomtobottomstart_index_gfx9; ///< Index of time of the previous command reaching bottom of pipe for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimebottomtobottomend_index_gfx9; ///< Index of time of the current command reaching bottom of pipe for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimetoptobottomduration_index_gfx9; ///< Index of execution duration of the current command from top of pipe to bottom of pipe, may include overhead of time in queue for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimetoptobottomstart_index_gfx9; ///< Index of time that the current command reaches the top of pipe for vk for gfx9 family
    extern const unsigned int                 hw_vk_gputimetoptobottomend_index_gfx9; ///< Index of time that the current command reaches the bottom of pipe for vk for gfx9 family
    extern const std::set<unsigned int>       hw_vk_timestamp_block_ids_gfx9; ///< Timestamp block id's for vk for gfx9 family
    extern const std::set<unsigned int>       hw_vk_time_counter_indices_gfx9; ///< Timestamp counter indices for vk for gfx9 family
    extern const unsigned int                 hw_vk_group_count_gfx9; ///< Hardware Group Count for vk for gfx9 family
    extern const unsigned int                 hw_vk_exposed_counters_group_count_gfx9; ///< Whitelist hardware counter Group Count for vk for gfx9 family
    extern const unsigned int                 vk_padded_counter_group_count_gfx9; ///< reserved counter group count for vk for gfx9 family
    extern const unsigned int                 hw_vk_sq_group_count_gfx9; ///< Hardware SQ Group Count for vk for gfx9 family
    extern const unsigned int                 hw_vk_sq_isolated_group_count_gfx9; ///< Hardware Isolated Group Count for vk for gfx9 family
}; // namespace

#endif  // _GPA_HW_COUNTER_VK_GFX9_H_
