//==============================================================================
// Copyright (c) 2010-2022 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX8_CARRIZO.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX8_CARRIZO_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX8_CARRIZO_H_

// clang-format off

#include <set>

struct GpaHardwareCounterDesc;
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx8.h"

namespace counter_gfx8_carrizo
{
/// @brief Uses the input ASIC type to determine if this data provides an ASIC specific version.
///
/// @param [in] asic_type The ASIC type that is currently in use.
///
/// @return True if the ASIC is matched by this file.
inline bool MatchAsic(GDT_HW_ASIC_TYPE asic_type)
{
    static std::set<GDT_HW_ASIC_TYPE> asics_supported = { GDT_CARRIZO, GDT_CARRIZO_EMB };

    if (asics_supported.find(asic_type) == asics_supported.end())
    {
        return false;
    }

    return true;
}

    extern std::vector<GpaHardwareCounterDesc> kVgt0CountersGfx8_carrizo; ///< Array of internal counters for Vgt0 block for Gfx8_carrizo family
    extern std::vector<GpaHardwareCounterDesc> kVgt1CountersGfx8_carrizo; ///< Array of internal counters for Vgt1 block for Gfx8_carrizo family
    extern std::vector<GpaHardwareCounterDesc> kVgt2CountersGfx8_carrizo; ///< Array of internal counters for Vgt2 block for Gfx8_carrizo family
    extern std::vector<GpaHardwareCounterDesc> kVgt3CountersGfx8_carrizo; ///< Array of internal counters for Vgt3 block for Gfx8_carrizo family

/// @brief Replaces count number of block instance counters at the destination with the overriding source counters.
///
/// @param [in] dest_counter Destination to update.
/// @param [in] src_counter Source to update from.
/// @param [in] count Number of counters to update.
inline void ReplaceBlockInstanceCounters(std::vector<GpaHardwareCounterDesc> &dest_counter, const std::vector<GpaHardwareCounterDesc> &src_counter)
{
    assert(src_counter.size() == dest_counter.size());
    dest_counter = src_counter;
}

/// @brief If the requested ASIC type is supported, then the global GPU generation block instance counters are updated.
///
/// @param [in] asic_type The ASIC type that is currently in use.
///
/// @return True if the ASIC is matched by this file and block instances are updated, otherwise false.
inline bool OverrideBlockInstanceCounters(GDT_HW_ASIC_TYPE asic_type)
{
    if (!MatchAsic(asic_type))
    {
        return false;
    }

    ReplaceBlockInstanceCounters(counter_gfx8::kVgt0CountersGfx8, kVgt0CountersGfx8_carrizo);
    ReplaceBlockInstanceCounters(counter_gfx8::kVgt1CountersGfx8, kVgt1CountersGfx8_carrizo);
    ReplaceBlockInstanceCounters(counter_gfx8::kVgt2CountersGfx8, kVgt2CountersGfx8_carrizo);
    ReplaceBlockInstanceCounters(counter_gfx8::kVgt3CountersGfx8, kVgt3CountersGfx8_carrizo);

    return true;
}

bool OverrideMaxBlockEvents(GDT_HW_ASIC_TYPE asic_type);
} // counter_gfx8_carrizo

// clang-format on

#endif  // GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX8_CARRIZO_H_
