//==============================================================================
// Copyright (c) 2010-2025 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11_GFX1150.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX11_GFX1150_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX11_GFX1150_H_

// clang-format off

#include "gpu_perf_api_common/gpa_array_view.hpp"
#include <array>
#include <cassert>

#include "DeviceInfo.h"

struct GpaHardwareCounterDesc;

#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"

namespace counter_gfx11_gfx1150
{
/// @brief Uses the input ASIC type to determine if this data provides an ASIC specific version.
///
/// @param [in] asic_type The ASIC type that is currently in use.
///
/// @return True if the ASIC is matched by this file.
inline bool MatchAsic(GDT_HW_ASIC_TYPE asic_type)
{
    static constexpr std::array asics_supported = { GDT_GFX11_5_0, GDT_GFX11_5_1, GDT_GFX11_5_2, GDT_GFX11_5_3, GDT_GFX11_5_3A };

    return std::find(asics_supported.begin(), asics_supported.end(), asic_type) != asics_supported.end();
}

    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc0CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc0 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc1CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc1 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc2CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc2 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc3CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc3 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc4CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc4 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc5CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc5 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc6CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc6 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc7CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc7 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc8CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc8 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc9CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc9 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc10CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc10 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc11CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc11 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc12CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc12 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc13CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc13 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc14CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc14 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc15CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc15 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc16CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc16 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc17CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc17 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc18CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc18 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc19CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc19 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc20CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc20 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc21CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc21 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc22CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc22 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kPaSc23CountersGfx11_gfx1150; ///< Array view of internal counters for PaSc23 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd0CountersGfx11_gfx1150; ///< Array view of internal counters for Td0 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd1CountersGfx11_gfx1150; ///< Array view of internal counters for Td1 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd2CountersGfx11_gfx1150; ///< Array view of internal counters for Td2 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd3CountersGfx11_gfx1150; ///< Array view of internal counters for Td3 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd4CountersGfx11_gfx1150; ///< Array view of internal counters for Td4 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd5CountersGfx11_gfx1150; ///< Array view of internal counters for Td5 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd6CountersGfx11_gfx1150; ///< Array view of internal counters for Td6 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd7CountersGfx11_gfx1150; ///< Array view of internal counters for Td7 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd8CountersGfx11_gfx1150; ///< Array view of internal counters for Td8 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd9CountersGfx11_gfx1150; ///< Array view of internal counters for Td9 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd10CountersGfx11_gfx1150; ///< Array view of internal counters for Td10 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd11CountersGfx11_gfx1150; ///< Array view of internal counters for Td11 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd12CountersGfx11_gfx1150; ///< Array view of internal counters for Td12 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd13CountersGfx11_gfx1150; ///< Array view of internal counters for Td13 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd14CountersGfx11_gfx1150; ///< Array view of internal counters for Td14 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd15CountersGfx11_gfx1150; ///< Array view of internal counters for Td15 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd16CountersGfx11_gfx1150; ///< Array view of internal counters for Td16 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd17CountersGfx11_gfx1150; ///< Array view of internal counters for Td17 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd18CountersGfx11_gfx1150; ///< Array view of internal counters for Td18 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd19CountersGfx11_gfx1150; ///< Array view of internal counters for Td19 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd20CountersGfx11_gfx1150; ///< Array view of internal counters for Td20 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd21CountersGfx11_gfx1150; ///< Array view of internal counters for Td21 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd22CountersGfx11_gfx1150; ///< Array view of internal counters for Td22 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd23CountersGfx11_gfx1150; ///< Array view of internal counters for Td23 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd24CountersGfx11_gfx1150; ///< Array view of internal counters for Td24 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd25CountersGfx11_gfx1150; ///< Array view of internal counters for Td25 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd26CountersGfx11_gfx1150; ///< Array view of internal counters for Td26 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd27CountersGfx11_gfx1150; ///< Array view of internal counters for Td27 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd28CountersGfx11_gfx1150; ///< Array view of internal counters for Td28 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd29CountersGfx11_gfx1150; ///< Array view of internal counters for Td29 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd30CountersGfx11_gfx1150; ///< Array view of internal counters for Td30 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd31CountersGfx11_gfx1150; ///< Array view of internal counters for Td31 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd32CountersGfx11_gfx1150; ///< Array view of internal counters for Td32 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd33CountersGfx11_gfx1150; ///< Array view of internal counters for Td33 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd34CountersGfx11_gfx1150; ///< Array view of internal counters for Td34 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd35CountersGfx11_gfx1150; ///< Array view of internal counters for Td35 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd36CountersGfx11_gfx1150; ///< Array view of internal counters for Td36 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd37CountersGfx11_gfx1150; ///< Array view of internal counters for Td37 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd38CountersGfx11_gfx1150; ///< Array view of internal counters for Td38 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd39CountersGfx11_gfx1150; ///< Array view of internal counters for Td39 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd40CountersGfx11_gfx1150; ///< Array view of internal counters for Td40 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd41CountersGfx11_gfx1150; ///< Array view of internal counters for Td41 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd42CountersGfx11_gfx1150; ///< Array view of internal counters for Td42 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd43CountersGfx11_gfx1150; ///< Array view of internal counters for Td43 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd44CountersGfx11_gfx1150; ///< Array view of internal counters for Td44 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd45CountersGfx11_gfx1150; ///< Array view of internal counters for Td45 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd46CountersGfx11_gfx1150; ///< Array view of internal counters for Td46 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd47CountersGfx11_gfx1150; ///< Array view of internal counters for Td47 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd48CountersGfx11_gfx1150; ///< Array view of internal counters for Td48 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd49CountersGfx11_gfx1150; ///< Array view of internal counters for Td49 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd50CountersGfx11_gfx1150; ///< Array view of internal counters for Td50 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd51CountersGfx11_gfx1150; ///< Array view of internal counters for Td51 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd52CountersGfx11_gfx1150; ///< Array view of internal counters for Td52 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd53CountersGfx11_gfx1150; ///< Array view of internal counters for Td53 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd54CountersGfx11_gfx1150; ///< Array view of internal counters for Td54 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd55CountersGfx11_gfx1150; ///< Array view of internal counters for Td55 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd56CountersGfx11_gfx1150; ///< Array view of internal counters for Td56 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd57CountersGfx11_gfx1150; ///< Array view of internal counters for Td57 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd58CountersGfx11_gfx1150; ///< Array view of internal counters for Td58 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd59CountersGfx11_gfx1150; ///< Array view of internal counters for Td59 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd60CountersGfx11_gfx1150; ///< Array view of internal counters for Td60 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd61CountersGfx11_gfx1150; ///< Array view of internal counters for Td61 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd62CountersGfx11_gfx1150; ///< Array view of internal counters for Td62 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd63CountersGfx11_gfx1150; ///< Array view of internal counters for Td63 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd64CountersGfx11_gfx1150; ///< Array view of internal counters for Td64 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd65CountersGfx11_gfx1150; ///< Array view of internal counters for Td65 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd66CountersGfx11_gfx1150; ///< Array view of internal counters for Td66 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd67CountersGfx11_gfx1150; ///< Array view of internal counters for Td67 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd68CountersGfx11_gfx1150; ///< Array view of internal counters for Td68 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd69CountersGfx11_gfx1150; ///< Array view of internal counters for Td69 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd70CountersGfx11_gfx1150; ///< Array view of internal counters for Td70 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd71CountersGfx11_gfx1150; ///< Array view of internal counters for Td71 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd72CountersGfx11_gfx1150; ///< Array view of internal counters for Td72 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd73CountersGfx11_gfx1150; ///< Array view of internal counters for Td73 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd74CountersGfx11_gfx1150; ///< Array view of internal counters for Td74 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd75CountersGfx11_gfx1150; ///< Array view of internal counters for Td75 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd76CountersGfx11_gfx1150; ///< Array view of internal counters for Td76 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd77CountersGfx11_gfx1150; ///< Array view of internal counters for Td77 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd78CountersGfx11_gfx1150; ///< Array view of internal counters for Td78 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd79CountersGfx11_gfx1150; ///< Array view of internal counters for Td79 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd80CountersGfx11_gfx1150; ///< Array view of internal counters for Td80 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd81CountersGfx11_gfx1150; ///< Array view of internal counters for Td81 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd82CountersGfx11_gfx1150; ///< Array view of internal counters for Td82 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd83CountersGfx11_gfx1150; ///< Array view of internal counters for Td83 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd84CountersGfx11_gfx1150; ///< Array view of internal counters for Td84 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd85CountersGfx11_gfx1150; ///< Array view of internal counters for Td85 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd86CountersGfx11_gfx1150; ///< Array view of internal counters for Td86 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd87CountersGfx11_gfx1150; ///< Array view of internal counters for Td87 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd88CountersGfx11_gfx1150; ///< Array view of internal counters for Td88 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd89CountersGfx11_gfx1150; ///< Array view of internal counters for Td89 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd90CountersGfx11_gfx1150; ///< Array view of internal counters for Td90 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd91CountersGfx11_gfx1150; ///< Array view of internal counters for Td91 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd92CountersGfx11_gfx1150; ///< Array view of internal counters for Td92 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd93CountersGfx11_gfx1150; ///< Array view of internal counters for Td93 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd94CountersGfx11_gfx1150; ///< Array view of internal counters for Td94 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTd95CountersGfx11_gfx1150; ///< Array view of internal counters for Td95 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp0CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp0 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp1CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp1 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp2CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp2 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp3CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp3 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp4CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp4 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp5CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp5 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp6CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp6 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp7CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp7 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp8CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp8 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp9CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp9 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp10CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp10 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp11CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp11 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp12CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp12 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp13CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp13 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp14CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp14 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp15CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp15 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp16CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp16 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp17CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp17 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp18CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp18 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp19CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp19 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp20CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp20 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp21CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp21 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp22CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp22 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp23CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp23 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp24CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp24 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp25CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp25 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp26CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp26 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp27CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp27 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp28CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp28 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp29CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp29 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp30CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp30 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp31CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp31 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp32CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp32 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp33CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp33 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp34CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp34 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp35CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp35 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp36CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp36 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp37CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp37 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp38CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp38 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp39CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp39 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp40CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp40 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp41CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp41 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp42CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp42 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp43CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp43 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp44CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp44 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp45CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp45 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp46CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp46 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp47CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp47 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp48CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp48 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp49CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp49 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp50CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp50 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp51CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp51 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp52CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp52 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp53CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp53 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp54CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp54 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp55CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp55 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp56CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp56 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp57CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp57 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp58CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp58 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp59CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp59 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp60CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp60 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp61CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp61 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp62CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp62 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp63CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp63 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp64CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp64 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp65CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp65 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp66CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp66 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp67CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp67 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp68CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp68 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp69CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp69 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp70CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp70 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp71CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp71 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp72CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp72 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp73CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp73 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp74CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp74 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp75CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp75 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp76CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp76 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp77CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp77 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp78CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp78 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp79CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp79 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp80CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp80 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp81CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp81 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp82CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp82 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp83CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp83 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp84CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp84 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp85CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp85 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp86CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp86 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp87CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp87 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp88CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp88 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp89CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp89 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp90CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp90 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp91CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp91 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp92CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp92 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp93CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp93 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp94CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp94 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kTcp95CountersGfx11_gfx1150; ///< Array view of internal counters for Tcp95 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb0CountersGfx11_gfx1150; ///< Array view of internal counters for Db0 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb1CountersGfx11_gfx1150; ///< Array view of internal counters for Db1 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb2CountersGfx11_gfx1150; ///< Array view of internal counters for Db2 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb3CountersGfx11_gfx1150; ///< Array view of internal counters for Db3 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb4CountersGfx11_gfx1150; ///< Array view of internal counters for Db4 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb5CountersGfx11_gfx1150; ///< Array view of internal counters for Db5 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb6CountersGfx11_gfx1150; ///< Array view of internal counters for Db6 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb7CountersGfx11_gfx1150; ///< Array view of internal counters for Db7 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb8CountersGfx11_gfx1150; ///< Array view of internal counters for Db8 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb9CountersGfx11_gfx1150; ///< Array view of internal counters for Db9 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb10CountersGfx11_gfx1150; ///< Array view of internal counters for Db10 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb11CountersGfx11_gfx1150; ///< Array view of internal counters for Db11 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb12CountersGfx11_gfx1150; ///< Array view of internal counters for Db12 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb13CountersGfx11_gfx1150; ///< Array view of internal counters for Db13 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb14CountersGfx11_gfx1150; ///< Array view of internal counters for Db14 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb15CountersGfx11_gfx1150; ///< Array view of internal counters for Db15 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb16CountersGfx11_gfx1150; ///< Array view of internal counters for Db16 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb17CountersGfx11_gfx1150; ///< Array view of internal counters for Db17 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb18CountersGfx11_gfx1150; ///< Array view of internal counters for Db18 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb19CountersGfx11_gfx1150; ///< Array view of internal counters for Db19 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb20CountersGfx11_gfx1150; ///< Array view of internal counters for Db20 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb21CountersGfx11_gfx1150; ///< Array view of internal counters for Db21 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb22CountersGfx11_gfx1150; ///< Array view of internal counters for Db22 block for Gfx11_gfx1150 family
    extern gpa_array_view<GpaHardwareCounterDesc> kDb23CountersGfx11_gfx1150; ///< Array view of internal counters for Db23 block for Gfx11_gfx1150 family

/// @brief This function is called on variant hardware which has a different register spec and therefore we need to substitute the base set of counters with the variant's set.
///
/// @param [in] dest_counter Destination to update.
/// @param [in] src_counter Source to update from.
inline void ReplaceBlockInstanceCounters(gpa_array_view<GpaHardwareCounterDesc> &dest_counter, const gpa_array_view<GpaHardwareCounterDesc> &src_counter)
{
    assert(src_counter.size() == dest_counter.size());
    dest_counter = src_counter;
}

/// @brief If the requested ASIC type is supported, then the global GPU generation block instance counters are updated.
///
/// @param [in] asic_type The ASIC type that is currently in use.
///
/// @return True if the ASIC is matched by this file and block instances are updated, otherwise false.
inline bool OverrideBlockInstanceCounters(GDT_HW_ASIC_TYPE asic_type)
{
    if (!MatchAsic(asic_type))
    {
        return false;
    }

    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc0CountersGfx11, kPaSc0CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc1CountersGfx11, kPaSc1CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc2CountersGfx11, kPaSc2CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc3CountersGfx11, kPaSc3CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc4CountersGfx11, kPaSc4CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc5CountersGfx11, kPaSc5CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc6CountersGfx11, kPaSc6CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc7CountersGfx11, kPaSc7CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc8CountersGfx11, kPaSc8CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc9CountersGfx11, kPaSc9CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc10CountersGfx11, kPaSc10CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc11CountersGfx11, kPaSc11CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc12CountersGfx11, kPaSc12CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc13CountersGfx11, kPaSc13CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc14CountersGfx11, kPaSc14CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc15CountersGfx11, kPaSc15CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc16CountersGfx11, kPaSc16CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc17CountersGfx11, kPaSc17CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc18CountersGfx11, kPaSc18CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc19CountersGfx11, kPaSc19CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc20CountersGfx11, kPaSc20CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc21CountersGfx11, kPaSc21CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc22CountersGfx11, kPaSc22CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kPaSc23CountersGfx11, kPaSc23CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd0CountersGfx11, kTd0CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd1CountersGfx11, kTd1CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd2CountersGfx11, kTd2CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd3CountersGfx11, kTd3CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd4CountersGfx11, kTd4CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd5CountersGfx11, kTd5CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd6CountersGfx11, kTd6CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd7CountersGfx11, kTd7CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd8CountersGfx11, kTd8CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd9CountersGfx11, kTd9CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd10CountersGfx11, kTd10CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd11CountersGfx11, kTd11CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd12CountersGfx11, kTd12CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd13CountersGfx11, kTd13CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd14CountersGfx11, kTd14CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd15CountersGfx11, kTd15CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd16CountersGfx11, kTd16CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd17CountersGfx11, kTd17CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd18CountersGfx11, kTd18CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd19CountersGfx11, kTd19CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd20CountersGfx11, kTd20CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd21CountersGfx11, kTd21CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd22CountersGfx11, kTd22CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd23CountersGfx11, kTd23CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd24CountersGfx11, kTd24CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd25CountersGfx11, kTd25CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd26CountersGfx11, kTd26CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd27CountersGfx11, kTd27CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd28CountersGfx11, kTd28CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd29CountersGfx11, kTd29CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd30CountersGfx11, kTd30CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd31CountersGfx11, kTd31CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd32CountersGfx11, kTd32CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd33CountersGfx11, kTd33CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd34CountersGfx11, kTd34CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd35CountersGfx11, kTd35CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd36CountersGfx11, kTd36CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd37CountersGfx11, kTd37CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd38CountersGfx11, kTd38CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd39CountersGfx11, kTd39CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd40CountersGfx11, kTd40CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd41CountersGfx11, kTd41CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd42CountersGfx11, kTd42CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd43CountersGfx11, kTd43CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd44CountersGfx11, kTd44CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd45CountersGfx11, kTd45CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd46CountersGfx11, kTd46CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd47CountersGfx11, kTd47CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd48CountersGfx11, kTd48CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd49CountersGfx11, kTd49CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd50CountersGfx11, kTd50CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd51CountersGfx11, kTd51CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd52CountersGfx11, kTd52CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd53CountersGfx11, kTd53CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd54CountersGfx11, kTd54CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd55CountersGfx11, kTd55CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd56CountersGfx11, kTd56CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd57CountersGfx11, kTd57CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd58CountersGfx11, kTd58CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd59CountersGfx11, kTd59CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd60CountersGfx11, kTd60CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd61CountersGfx11, kTd61CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd62CountersGfx11, kTd62CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd63CountersGfx11, kTd63CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd64CountersGfx11, kTd64CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd65CountersGfx11, kTd65CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd66CountersGfx11, kTd66CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd67CountersGfx11, kTd67CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd68CountersGfx11, kTd68CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd69CountersGfx11, kTd69CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd70CountersGfx11, kTd70CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd71CountersGfx11, kTd71CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd72CountersGfx11, kTd72CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd73CountersGfx11, kTd73CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd74CountersGfx11, kTd74CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd75CountersGfx11, kTd75CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd76CountersGfx11, kTd76CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd77CountersGfx11, kTd77CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd78CountersGfx11, kTd78CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd79CountersGfx11, kTd79CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd80CountersGfx11, kTd80CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd81CountersGfx11, kTd81CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd82CountersGfx11, kTd82CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd83CountersGfx11, kTd83CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd84CountersGfx11, kTd84CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd85CountersGfx11, kTd85CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd86CountersGfx11, kTd86CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd87CountersGfx11, kTd87CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd88CountersGfx11, kTd88CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd89CountersGfx11, kTd89CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd90CountersGfx11, kTd90CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd91CountersGfx11, kTd91CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd92CountersGfx11, kTd92CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd93CountersGfx11, kTd93CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd94CountersGfx11, kTd94CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTd95CountersGfx11, kTd95CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp0CountersGfx11, kTcp0CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp1CountersGfx11, kTcp1CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp2CountersGfx11, kTcp2CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp3CountersGfx11, kTcp3CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp4CountersGfx11, kTcp4CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp5CountersGfx11, kTcp5CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp6CountersGfx11, kTcp6CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp7CountersGfx11, kTcp7CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp8CountersGfx11, kTcp8CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp9CountersGfx11, kTcp9CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp10CountersGfx11, kTcp10CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp11CountersGfx11, kTcp11CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp12CountersGfx11, kTcp12CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp13CountersGfx11, kTcp13CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp14CountersGfx11, kTcp14CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp15CountersGfx11, kTcp15CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp16CountersGfx11, kTcp16CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp17CountersGfx11, kTcp17CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp18CountersGfx11, kTcp18CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp19CountersGfx11, kTcp19CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp20CountersGfx11, kTcp20CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp21CountersGfx11, kTcp21CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp22CountersGfx11, kTcp22CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp23CountersGfx11, kTcp23CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp24CountersGfx11, kTcp24CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp25CountersGfx11, kTcp25CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp26CountersGfx11, kTcp26CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp27CountersGfx11, kTcp27CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp28CountersGfx11, kTcp28CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp29CountersGfx11, kTcp29CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp30CountersGfx11, kTcp30CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp31CountersGfx11, kTcp31CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp32CountersGfx11, kTcp32CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp33CountersGfx11, kTcp33CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp34CountersGfx11, kTcp34CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp35CountersGfx11, kTcp35CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp36CountersGfx11, kTcp36CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp37CountersGfx11, kTcp37CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp38CountersGfx11, kTcp38CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp39CountersGfx11, kTcp39CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp40CountersGfx11, kTcp40CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp41CountersGfx11, kTcp41CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp42CountersGfx11, kTcp42CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp43CountersGfx11, kTcp43CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp44CountersGfx11, kTcp44CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp45CountersGfx11, kTcp45CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp46CountersGfx11, kTcp46CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp47CountersGfx11, kTcp47CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp48CountersGfx11, kTcp48CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp49CountersGfx11, kTcp49CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp50CountersGfx11, kTcp50CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp51CountersGfx11, kTcp51CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp52CountersGfx11, kTcp52CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp53CountersGfx11, kTcp53CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp54CountersGfx11, kTcp54CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp55CountersGfx11, kTcp55CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp56CountersGfx11, kTcp56CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp57CountersGfx11, kTcp57CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp58CountersGfx11, kTcp58CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp59CountersGfx11, kTcp59CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp60CountersGfx11, kTcp60CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp61CountersGfx11, kTcp61CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp62CountersGfx11, kTcp62CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp63CountersGfx11, kTcp63CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp64CountersGfx11, kTcp64CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp65CountersGfx11, kTcp65CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp66CountersGfx11, kTcp66CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp67CountersGfx11, kTcp67CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp68CountersGfx11, kTcp68CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp69CountersGfx11, kTcp69CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp70CountersGfx11, kTcp70CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp71CountersGfx11, kTcp71CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp72CountersGfx11, kTcp72CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp73CountersGfx11, kTcp73CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp74CountersGfx11, kTcp74CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp75CountersGfx11, kTcp75CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp76CountersGfx11, kTcp76CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp77CountersGfx11, kTcp77CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp78CountersGfx11, kTcp78CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp79CountersGfx11, kTcp79CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp80CountersGfx11, kTcp80CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp81CountersGfx11, kTcp81CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp82CountersGfx11, kTcp82CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp83CountersGfx11, kTcp83CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp84CountersGfx11, kTcp84CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp85CountersGfx11, kTcp85CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp86CountersGfx11, kTcp86CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp87CountersGfx11, kTcp87CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp88CountersGfx11, kTcp88CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp89CountersGfx11, kTcp89CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp90CountersGfx11, kTcp90CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp91CountersGfx11, kTcp91CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp92CountersGfx11, kTcp92CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp93CountersGfx11, kTcp93CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp94CountersGfx11, kTcp94CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kTcp95CountersGfx11, kTcp95CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb0CountersGfx11, kDb0CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb1CountersGfx11, kDb1CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb2CountersGfx11, kDb2CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb3CountersGfx11, kDb3CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb4CountersGfx11, kDb4CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb5CountersGfx11, kDb5CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb6CountersGfx11, kDb6CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb7CountersGfx11, kDb7CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb8CountersGfx11, kDb8CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb9CountersGfx11, kDb9CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb10CountersGfx11, kDb10CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb11CountersGfx11, kDb11CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb12CountersGfx11, kDb12CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb13CountersGfx11, kDb13CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb14CountersGfx11, kDb14CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb15CountersGfx11, kDb15CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb16CountersGfx11, kDb16CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb17CountersGfx11, kDb17CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb18CountersGfx11, kDb18CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb19CountersGfx11, kDb19CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb20CountersGfx11, kDb20CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb21CountersGfx11, kDb21CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb22CountersGfx11, kDb22CountersGfx11_gfx1150);
    ReplaceBlockInstanceCounters(counter_gfx11::kDb23CountersGfx11, kDb23CountersGfx11_gfx1150);

    return true;
}

bool OverrideMaxBlockEvents(GDT_HW_ASIC_TYPE asic_type);
} // counter_gfx11_gfx1150

// clang-format on

#endif
