//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx11
{

    static constexpr std::array kSqgGs0CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS0_PERF_SEL_WAVES", "SQG_GS0", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS0_PERF_SEL_WAVES_32", "SQG_GS0", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS0_PERF_SEL_ITEMS", "SQG_GS0", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs0CountersGfx11 = kSqgGs0CountersGfx11Data;

    static constexpr std::array kSqgGs1CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS1_PERF_SEL_WAVES", "SQG_GS1", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS1_PERF_SEL_WAVES_32", "SQG_GS1", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS1_PERF_SEL_ITEMS", "SQG_GS1", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs1CountersGfx11 = kSqgGs1CountersGfx11Data;

    static constexpr std::array kSqgGs2CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS2_PERF_SEL_WAVES", "SQG_GS2", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS2_PERF_SEL_WAVES_32", "SQG_GS2", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS2_PERF_SEL_ITEMS", "SQG_GS2", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs2CountersGfx11 = kSqgGs2CountersGfx11Data;

    static constexpr std::array kSqgGs3CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS3_PERF_SEL_WAVES", "SQG_GS3", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS3_PERF_SEL_WAVES_32", "SQG_GS3", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS3_PERF_SEL_ITEMS", "SQG_GS3", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs3CountersGfx11 = kSqgGs3CountersGfx11Data;

    static constexpr std::array kSqgGs4CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS4_PERF_SEL_WAVES", "SQG_GS4", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS4_PERF_SEL_WAVES_32", "SQG_GS4", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS4_PERF_SEL_ITEMS", "SQG_GS4", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs4CountersGfx11 = kSqgGs4CountersGfx11Data;

    static constexpr std::array kSqgGs5CountersGfx11Data = {
        GpaHardwareCounterDesc{20, "SQG_GS5_PERF_SEL_WAVES", "SQG_GS5", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{21, "SQG_GS5_PERF_SEL_WAVES_32", "SQG_GS5", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{24, "SQG_GS5_PERF_SEL_ITEMS", "SQG_GS5", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs5CountersGfx11 = kSqgGs5CountersGfx11Data;
} // counter_gfx11

// clang-format on
