//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief OGLP counter definitions for GFX115.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_OGLP_GFX115_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_OGLP_GFX115_H_

// clang-format off

#include <set>

struct GpaHardwareCounterDesc;
struct GpaCounterGroupDesc;
struct GpaSqCounterGroupDesc;

namespace counter_oglp_gfx115
{
    extern const gpa_array_view<gpa_array_view<GpaHardwareCounterDesc>*> kOglpCounterGroupArrayGfx115; ///< Array of hardware counter groups for Oglp for Gfx115 family
    extern const gpa_array_view<GpaCounterGroupDesc>                    kHwOglpGroupsGfx115; ///< Array of counter groups for Oglp for Gfx115 family
    extern GpaCounterGroupExposedCounterDesc                            kHwOglpExposedCountersByGroupGfx115[]; ///< Array of exposed counter groups for Oglp for Gfx115 family
    extern GpaPaddedCounterDesc                                         kOglpPaddedCounterByGroupGfx115[]; ///< Array of reserved counter for Oglp for Gfx115 family
    extern GpaSqCounterGroupDesc                                        kHwOglpSqGroupsGfx115[]; ///< Array of SQ groups for Oglp for Gfx115 family
    extern unsigned int                                                 kHwOglpSqIsolatedGroupsGfx115[]; ///< Array of counter groups isolated from SQ counter groups for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeBottomToBottomDurationIndexGfx115; ///< Index of delta between the previous command reaching bottom of pipe and the current command reaching bottom of pipe, will not include latency of first data to travel through pipeline, best for large data sets. for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeBottomToBottomStartIndexGfx115; ///< Index of time of the previous command reaching bottom of pipe for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeBottomToBottomEndIndexGfx115; ///< Index of time of the current command reaching bottom of pipe for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeTopToBottomDurationIndexGfx115; ///< Index of execution duration of the current command from top of pipe to bottom of pipe, may include overhead of time in queue for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeTopToBottomStartIndexGfx115; ///< Index of time that the current command reaches the top of pipe for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGpuTimeTopToBottomEndIndexGfx115; ///< Index of time that the current command reaches the bottom of pipe for Oglp for Gfx115 family
    extern const std::set<unsigned int>                                 kHwOglpTimestampBlockIdsGfx115; ///< Timestamp block id's for Oglp for Gfx115 family
    extern const std::set<unsigned int>                                 kHwOglpTimeCounterIndicesGfx115; ///< Timestamp counter indices for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpGroupCountGfx115; ///< Hardware Group Count for Oglp for Gfx115 family
    extern const unsigned int                                           kOglpPaddedCounterGroupCountGfx115; ///< reserved counter group count for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpSqGroupCountGfx115; ///< Hardware SQ Group Count for Oglp for Gfx115 family
    extern const unsigned int                                           kHwOglpSqIsolatedGroupCountGfx115; ///< Hardware Isolated Group Count for Oglp for Gfx115 family

/// @brief If the requested ASIC type is supported, then the global GPU generation block instance counters are updated.
///
/// @param [in] asic_type The ASIC type that is currently in use.
///
/// @return True if the ASIC is matched by this file and block instances are updated, otherwise false.
inline bool OverrideMaxBlockEvents(device_info::AsicType asic_type)
{
    UNREFERENCED_PARAMETER(asic_type);

    return true;
}
} //  namespace counter_oglp_gfx115

// clang-format on

#endif
