//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX103.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx103.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx103
{

    static constexpr std::array kGrbmCountersGfx103Data = {
        GpaHardwareCounterDesc{0, "GRBM_PERF_SEL_COUNT", "GRBM", "Tie High - Count Number of Clocks"},
        GpaHardwareCounterDesc{2, "GRBM_PERF_SEL_GUI_ACTIVE", "GRBM", "The GUI is Active"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kGrbmCountersGfx103 = kGrbmCountersGfx103Data;
} // counter_gfx103

// clang-format on
