//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX11.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx11.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx11
{

    static constexpr std::array kSx0CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX0_PERF_SEL_DB0_PIXELS", "SX0", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX0_PERF_SEL_DB0_PIXEL_STALL", "SX0", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX0_PERF_SEL_DB1_PIXELS", "SX0", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX0_PERF_SEL_DB1_PIXEL_STALL", "SX0", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX0_PERF_SEL_DB2_PIXELS", "SX0", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX0_PERF_SEL_DB2_PIXEL_STALL", "SX0", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX0_PERF_SEL_DB3_PIXELS", "SX0", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX0_PERF_SEL_DB3_PIXEL_STALL", "SX0", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx0CountersGfx11 = kSx0CountersGfx11Data;

    static constexpr std::array kSx1CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX1_PERF_SEL_DB0_PIXELS", "SX1", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX1_PERF_SEL_DB0_PIXEL_STALL", "SX1", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX1_PERF_SEL_DB1_PIXELS", "SX1", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX1_PERF_SEL_DB1_PIXEL_STALL", "SX1", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX1_PERF_SEL_DB2_PIXELS", "SX1", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX1_PERF_SEL_DB2_PIXEL_STALL", "SX1", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX1_PERF_SEL_DB3_PIXELS", "SX1", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX1_PERF_SEL_DB3_PIXEL_STALL", "SX1", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx1CountersGfx11 = kSx1CountersGfx11Data;

    static constexpr std::array kSx2CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX2_PERF_SEL_DB0_PIXELS", "SX2", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX2_PERF_SEL_DB0_PIXEL_STALL", "SX2", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX2_PERF_SEL_DB1_PIXELS", "SX2", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX2_PERF_SEL_DB1_PIXEL_STALL", "SX2", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX2_PERF_SEL_DB2_PIXELS", "SX2", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX2_PERF_SEL_DB2_PIXEL_STALL", "SX2", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX2_PERF_SEL_DB3_PIXELS", "SX2", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX2_PERF_SEL_DB3_PIXEL_STALL", "SX2", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx2CountersGfx11 = kSx2CountersGfx11Data;

    static constexpr std::array kSx3CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX3_PERF_SEL_DB0_PIXELS", "SX3", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX3_PERF_SEL_DB0_PIXEL_STALL", "SX3", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX3_PERF_SEL_DB1_PIXELS", "SX3", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX3_PERF_SEL_DB1_PIXEL_STALL", "SX3", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX3_PERF_SEL_DB2_PIXELS", "SX3", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX3_PERF_SEL_DB2_PIXEL_STALL", "SX3", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX3_PERF_SEL_DB3_PIXELS", "SX3", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX3_PERF_SEL_DB3_PIXEL_STALL", "SX3", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx3CountersGfx11 = kSx3CountersGfx11Data;

    static constexpr std::array kSx4CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX4_PERF_SEL_DB0_PIXELS", "SX4", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX4_PERF_SEL_DB0_PIXEL_STALL", "SX4", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX4_PERF_SEL_DB1_PIXELS", "SX4", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX4_PERF_SEL_DB1_PIXEL_STALL", "SX4", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX4_PERF_SEL_DB2_PIXELS", "SX4", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX4_PERF_SEL_DB2_PIXEL_STALL", "SX4", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX4_PERF_SEL_DB3_PIXELS", "SX4", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX4_PERF_SEL_DB3_PIXEL_STALL", "SX4", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx4CountersGfx11 = kSx4CountersGfx11Data;

    static constexpr std::array kSx5CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX5_PERF_SEL_DB0_PIXELS", "SX5", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX5_PERF_SEL_DB0_PIXEL_STALL", "SX5", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX5_PERF_SEL_DB1_PIXELS", "SX5", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX5_PERF_SEL_DB1_PIXEL_STALL", "SX5", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX5_PERF_SEL_DB2_PIXELS", "SX5", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX5_PERF_SEL_DB2_PIXEL_STALL", "SX5", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX5_PERF_SEL_DB3_PIXELS", "SX5", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX5_PERF_SEL_DB3_PIXEL_STALL", "SX5", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx5CountersGfx11 = kSx5CountersGfx11Data;

    static constexpr std::array kSx6CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX6_PERF_SEL_DB0_PIXELS", "SX6", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX6_PERF_SEL_DB0_PIXEL_STALL", "SX6", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX6_PERF_SEL_DB1_PIXELS", "SX6", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX6_PERF_SEL_DB1_PIXEL_STALL", "SX6", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX6_PERF_SEL_DB2_PIXELS", "SX6", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX6_PERF_SEL_DB2_PIXEL_STALL", "SX6", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX6_PERF_SEL_DB3_PIXELS", "SX6", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX6_PERF_SEL_DB3_PIXEL_STALL", "SX6", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx6CountersGfx11 = kSx6CountersGfx11Data;

    static constexpr std::array kSx7CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX7_PERF_SEL_DB0_PIXELS", "SX7", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX7_PERF_SEL_DB0_PIXEL_STALL", "SX7", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX7_PERF_SEL_DB1_PIXELS", "SX7", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX7_PERF_SEL_DB1_PIXEL_STALL", "SX7", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX7_PERF_SEL_DB2_PIXELS", "SX7", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX7_PERF_SEL_DB2_PIXEL_STALL", "SX7", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX7_PERF_SEL_DB3_PIXELS", "SX7", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX7_PERF_SEL_DB3_PIXEL_STALL", "SX7", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx7CountersGfx11 = kSx7CountersGfx11Data;

    static constexpr std::array kSx8CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX8_PERF_SEL_DB0_PIXELS", "SX8", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX8_PERF_SEL_DB0_PIXEL_STALL", "SX8", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX8_PERF_SEL_DB1_PIXELS", "SX8", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX8_PERF_SEL_DB1_PIXEL_STALL", "SX8", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX8_PERF_SEL_DB2_PIXELS", "SX8", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX8_PERF_SEL_DB2_PIXEL_STALL", "SX8", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX8_PERF_SEL_DB3_PIXELS", "SX8", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX8_PERF_SEL_DB3_PIXEL_STALL", "SX8", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx8CountersGfx11 = kSx8CountersGfx11Data;

    static constexpr std::array kSx9CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX9_PERF_SEL_DB0_PIXELS", "SX9", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX9_PERF_SEL_DB0_PIXEL_STALL", "SX9", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX9_PERF_SEL_DB1_PIXELS", "SX9", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX9_PERF_SEL_DB1_PIXEL_STALL", "SX9", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX9_PERF_SEL_DB2_PIXELS", "SX9", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX9_PERF_SEL_DB2_PIXEL_STALL", "SX9", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX9_PERF_SEL_DB3_PIXELS", "SX9", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX9_PERF_SEL_DB3_PIXEL_STALL", "SX9", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx9CountersGfx11 = kSx9CountersGfx11Data;

    static constexpr std::array kSx10CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX10_PERF_SEL_DB0_PIXELS", "SX10", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX10_PERF_SEL_DB0_PIXEL_STALL", "SX10", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX10_PERF_SEL_DB1_PIXELS", "SX10", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX10_PERF_SEL_DB1_PIXEL_STALL", "SX10", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX10_PERF_SEL_DB2_PIXELS", "SX10", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX10_PERF_SEL_DB2_PIXEL_STALL", "SX10", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX10_PERF_SEL_DB3_PIXELS", "SX10", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX10_PERF_SEL_DB3_PIXEL_STALL", "SX10", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx10CountersGfx11 = kSx10CountersGfx11Data;

    static constexpr std::array kSx11CountersGfx11Data = {
        GpaHardwareCounterDesc{12, "SX11_PERF_SEL_DB0_PIXELS", "SX11", "Number of pixels sent to the DB0"},
        GpaHardwareCounterDesc{14, "SX11_PERF_SEL_DB0_PIXEL_STALL", "SX11", "Number of cycles where pixel traffic is stalled due to the DB0"},
        GpaHardwareCounterDesc{17, "SX11_PERF_SEL_DB1_PIXELS", "SX11", "Number of pixels sent to the DB1"},
        GpaHardwareCounterDesc{19, "SX11_PERF_SEL_DB1_PIXEL_STALL", "SX11", "Number of cycles where pixel traffic is stalled due to the DB1"},
        GpaHardwareCounterDesc{22, "SX11_PERF_SEL_DB2_PIXELS", "SX11", "Number of pixels sent to the DB2"},
        GpaHardwareCounterDesc{24, "SX11_PERF_SEL_DB2_PIXEL_STALL", "SX11", "Number of cycles where pixel traffic is stalled due to the DB2"},
        GpaHardwareCounterDesc{27, "SX11_PERF_SEL_DB3_PIXELS", "SX11", "Number of pixels sent to the DB3"},
        GpaHardwareCounterDesc{29, "SX11_PERF_SEL_DB3_PIXEL_STALL", "SX11", "Number of cycles where pixel traffic is stalled due to the DB3"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSx11CountersGfx11 = kSx11CountersGfx11Data;
} // counter_gfx11

// clang-format on
