//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX12.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx12.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx12
{

    static constexpr std::array kSqgGs0CountersGfx12Data = {
        GpaHardwareCounterDesc{19, "SQG_GS0_PERF_SEL_WAVES", "SQG_GS0", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{20, "SQG_GS0_PERF_SEL_WAVES_32", "SQG_GS0", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{22, "SQG_GS0_PERF_SEL_ITEMS", "SQG_GS0", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs0CountersGfx12 = kSqgGs0CountersGfx12Data;

    static constexpr std::array kSqgGs1CountersGfx12Data = {
        GpaHardwareCounterDesc{19, "SQG_GS1_PERF_SEL_WAVES", "SQG_GS1", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{20, "SQG_GS1_PERF_SEL_WAVES_32", "SQG_GS1", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{22, "SQG_GS1_PERF_SEL_ITEMS", "SQG_GS1", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs1CountersGfx12 = kSqgGs1CountersGfx12Data;

    static constexpr std::array kSqgGs2CountersGfx12Data = {
        GpaHardwareCounterDesc{19, "SQG_GS2_PERF_SEL_WAVES", "SQG_GS2", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{20, "SQG_GS2_PERF_SEL_WAVES_32", "SQG_GS2", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{22, "SQG_GS2_PERF_SEL_ITEMS", "SQG_GS2", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs2CountersGfx12 = kSqgGs2CountersGfx12Data;

    static constexpr std::array kSqgGs3CountersGfx12Data = {
        GpaHardwareCounterDesc{19, "SQG_GS3_PERF_SEL_WAVES", "SQG_GS3", "Count number of waves sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{20, "SQG_GS3_PERF_SEL_WAVES_32", "SQG_GS3", "Count number of wave32s sent to SQs. {emulated, global, C1}"},
        GpaHardwareCounterDesc{22, "SQG_GS3_PERF_SEL_ITEMS", "SQG_GS3", "Number of valid work items in SQs. {emulated, global, C1}"},
    };
    gpa_array_view<GpaHardwareCounterDesc> kSqgGs3CountersGfx12 = kSqgGs3CountersGfx12Data;
} // counter_gfx12

// clang-format on
