//==============================================================================
// Copyright Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX10.
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project.

// clang-format off

#include "gpu_perf_api_counter_generator/gpa_counter.h"
#include "auto_generated/gpu_perf_api_counter_generator/gpa_hw_counter_gfx10.h"
#include "gpu_performance_api/gpu_perf_api_types.h"

namespace counter_gfx10
{

    static constexpr std::array kCpfCountersGfx10Data = {
        GpaHardwareCounterDesc{0, "CPF_PERF_SEL_ALWAYS_COUNT", "CPF", "Always Count."},
        GpaHardwareCounterDesc{24, "CPF_PERF_SEL_CPF_STAT_BUSY", "CPF", "CPF Busy."},
    };
    gpa_array_view<GpaHardwareCounterDesc> kCpfCountersGfx10 = kCpfCountersGfx10Data;
} // counter_gfx10

// clang-format on
