## Copyright (C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved. ##

set(PUBLIC_COUNTER_DEF_HEADERS_DX11
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx10.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103_asics.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103_gfx1031_gfx1032.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103_gfx1033.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx10_asics.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_asics.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1102.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1103.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1150.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx12.h
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx12_asics.h)

set(PUBLIC_COUNTER_DEF_SRC_DX11
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx10.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103_gfx1031_gfx1032.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx103_gfx1033.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1102.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1103.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx11_gfx1150.cc
${CMAKE_CURRENT_LIST_DIR}/public_counter_definitions_dx11_gfx12.cc)

