//==============================================================================
// Copyright (c) 2010-2019 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  GL counter definitions for GFX10
//==============================================================================

#include "GPACounter.h"
#include "GPAHWCounterGfx10.h"
#include "GPAHWExposedCountersGfx10.h"
#include "GPAHWCounterGLGfx10.h"

// This file is autogenerated by the ConvertHWEnums project

namespace CounterGfx10
{
    GPA_HardwareCounterDesc* GLCounterGroupArrayGfx10[] = {
        CB0countersGfx10,
        CB1countersGfx10,
        CB2countersGfx10,
        CB3countersGfx10,
        CPFcountersGfx10,
        DB0countersGfx10,
        DB1countersGfx10,
        DB2countersGfx10,
        DB3countersGfx10,
        GRBMcountersGfx10,
        GRBMSE0countersGfx10,
        PA_SU0countersGfx10,
        PA_SC0countersGfx10,
        PA_SC1countersGfx10,
        SPI0countersGfx10,
        SQ0countersGfx10,
        SQ_ES0countersGfx10,
        SQ_GS0countersGfx10,
        SQ_VS0countersGfx10,
        SQ_PS0countersGfx10,
        SQ_LS0countersGfx10,
        SQ_HS0countersGfx10,
        SQ_CS0countersGfx10,
        SX0countersGfx10,
        TA0countersGfx10,
        TA1countersGfx10,
        TA2countersGfx10,
        TA3countersGfx10,
        TA4countersGfx10,
        TA5countersGfx10,
        TA6countersGfx10,
        TA7countersGfx10,
        TA8countersGfx10,
        TA9countersGfx10,
        TA10countersGfx10,
        TA11countersGfx10,
        TA12countersGfx10,
        TA13countersGfx10,
        TA14countersGfx10,
        TA15countersGfx10,
        TD0countersGfx10,
        TD1countersGfx10,
        TD2countersGfx10,
        TD3countersGfx10,
        TD4countersGfx10,
        TD5countersGfx10,
        TD6countersGfx10,
        TD7countersGfx10,
        TD8countersGfx10,
        TD9countersGfx10,
        TD10countersGfx10,
        TD11countersGfx10,
        TD12countersGfx10,
        TD13countersGfx10,
        TD14countersGfx10,
        TD15countersGfx10,
        TCP0countersGfx10,
        TCP1countersGfx10,
        TCP2countersGfx10,
        TCP3countersGfx10,
        TCP4countersGfx10,
        TCP5countersGfx10,
        TCP6countersGfx10,
        TCP7countersGfx10,
        TCP8countersGfx10,
        TCP9countersGfx10,
        TCP10countersGfx10,
        TCP11countersGfx10,
        TCP12countersGfx10,
        TCP13countersGfx10,
        TCP14countersGfx10,
        TCP15countersGfx10,
        GDScountersGfx10,
        CPGcountersGfx10,
        CPCcountersGfx10,
        GEcountersGfx10,
        GL1A0countersGfx10,
        GL1C0countersGfx10,
        GL2A0countersGfx10,
        GL2A1countersGfx10,
        GL2A2countersGfx10,
        GL2A3countersGfx10,
        GL2C0countersGfx10,
        GL2C1countersGfx10,
        GL2C2countersGfx10,
        GL2C3countersGfx10,
        GL2C4countersGfx10,
        GL2C5countersGfx10,
        GL2C6countersGfx10,
        GL2C7countersGfx10,
        GL2C8countersGfx10,
        GL2C9countersGfx10,
        GL2C10countersGfx10,
        GL2C11countersGfx10,
        GL2C12countersGfx10,
        GL2C13countersGfx10,
        GL2C14countersGfx10,
        GL2C15countersGfx10,
        GL2C16countersGfx10,
        GL2C17countersGfx10,
        GL2C18countersGfx10,
        GL2C19countersGfx10,
        GL2C20countersGfx10,
        GL2C21countersGfx10,
        GL2C22countersGfx10,
        GL2C23countersGfx10,
        PA_PHcountersGfx10,
        UTCL10countersGfx10,
        CHC0countersGfx10,
        CHAcountersGfx10,
        CHCGcountersGfx10,
        GPINcountersGfx10,
        GPUTimecountersGfx10,
    };

    GPA_HardwareCounterDesc* GLExposedCountersGroupArrayGfx10[] = {
        CB0ExposedCountersGfx10,
        CB1ExposedCountersGfx10,
        CB2ExposedCountersGfx10,
        CB3ExposedCountersGfx10,
        CPFExposedCountersGfx10,
        DB0ExposedCountersGfx10,
        DB1ExposedCountersGfx10,
        DB2ExposedCountersGfx10,
        DB3ExposedCountersGfx10,
        GRBMExposedCountersGfx10,
        PA_SU0ExposedCountersGfx10,
        PA_SC0ExposedCountersGfx10,
        PA_SC1ExposedCountersGfx10,
        SPI0ExposedCountersGfx10,
        SQ0ExposedCountersGfx10,
        SQ_ES0ExposedCountersGfx10,
        SQ_GS0ExposedCountersGfx10,
        SQ_VS0ExposedCountersGfx10,
        SQ_PS0ExposedCountersGfx10,
        SQ_LS0ExposedCountersGfx10,
        SQ_HS0ExposedCountersGfx10,
        SQ_CS0ExposedCountersGfx10,
        SX0ExposedCountersGfx10,
        TA0ExposedCountersGfx10,
        TA1ExposedCountersGfx10,
        TA2ExposedCountersGfx10,
        TA3ExposedCountersGfx10,
        TA4ExposedCountersGfx10,
        TA5ExposedCountersGfx10,
        TA6ExposedCountersGfx10,
        TA7ExposedCountersGfx10,
        TA8ExposedCountersGfx10,
        TA9ExposedCountersGfx10,
        TA10ExposedCountersGfx10,
        TA11ExposedCountersGfx10,
        TA12ExposedCountersGfx10,
        TA13ExposedCountersGfx10,
        TA14ExposedCountersGfx10,
        TA15ExposedCountersGfx10,
        TCP0ExposedCountersGfx10,
        TCP1ExposedCountersGfx10,
        TCP2ExposedCountersGfx10,
        TCP3ExposedCountersGfx10,
        TCP4ExposedCountersGfx10,
        TCP5ExposedCountersGfx10,
        TCP6ExposedCountersGfx10,
        TCP7ExposedCountersGfx10,
        TCP8ExposedCountersGfx10,
        TCP9ExposedCountersGfx10,
        TCP10ExposedCountersGfx10,
        TCP11ExposedCountersGfx10,
        TCP12ExposedCountersGfx10,
        TCP13ExposedCountersGfx10,
        TCP14ExposedCountersGfx10,
        TCP15ExposedCountersGfx10,
        GEExposedCountersGfx10,
        GL1C0ExposedCountersGfx10,
        GL2C0ExposedCountersGfx10,
        GL2C1ExposedCountersGfx10,
        GL2C2ExposedCountersGfx10,
        GL2C3ExposedCountersGfx10,
        GL2C4ExposedCountersGfx10,
        GL2C5ExposedCountersGfx10,
        GL2C6ExposedCountersGfx10,
        GL2C7ExposedCountersGfx10,
        GL2C8ExposedCountersGfx10,
        GL2C9ExposedCountersGfx10,
        GL2C10ExposedCountersGfx10,
        GL2C11ExposedCountersGfx10,
        GL2C12ExposedCountersGfx10,
        GL2C13ExposedCountersGfx10,
        GL2C14ExposedCountersGfx10,
        GL2C15ExposedCountersGfx10,
        GL2C16ExposedCountersGfx10,
        GL2C17ExposedCountersGfx10,
        GL2C18ExposedCountersGfx10,
        GL2C19ExposedCountersGfx10,
        GL2C20ExposedCountersGfx10,
        GL2C21ExposedCountersGfx10,
        GL2C22ExposedCountersGfx10,
        GL2C23ExposedCountersGfx10,
        GPUTimeExposedCountersGfx10,
    };

    GPA_CounterGroupDesc HWGLGroupsGfx10[] = {
        {0, "CB0", 0, 461, 4, 4},
        {1, "CB1", 1, 461, 4, 4},
        {2, "CB2", 2, 461, 4, 4},
        {3, "CB3", 3, 461, 4, 4},
        {4, "CPF", 0, 40, 2, 4},
        {5, "DB0", 0, 370, 4, 8},
        {6, "DB1", 1, 370, 4, 8},
        {7, "DB2", 2, 370, 4, 8},
        {8, "DB3", 3, 370, 4, 8},
        {9, "GRBM", 0, 47, 2, 0},
        {10, "GRBMSE", 0, 19, 4, 0},
        {11, "PA_SU", 0, 266, 4, 16},
        {12, "PA_SC0", 0, 552, 8, 4},
        {13, "PA_SC1", 1, 552, 8, 4},
        {14, "SPI", 0, 329, 6, 16},
        {15, "SQ", 0, 512, 16, 16},
        {16, "SQ_ES", 0, 512, 16, 16},
        {17, "SQ_GS", 0, 512, 16, 16},
        {18, "SQ_VS", 0, 512, 16, 16},
        {19, "SQ_PS", 0, 512, 16, 16},
        {20, "SQ_LS", 0, 512, 16, 16},
        {21, "SQ_HS", 0, 512, 16, 16},
        {22, "SQ_CS", 0, 512, 16, 16},
        {23, "SX", 0, 225, 4, 8},
        {24, "TA0", 0, 226, 2, 4},
        {25, "TA1", 1, 226, 2, 4},
        {26, "TA2", 2, 226, 2, 4},
        {27, "TA3", 3, 226, 2, 4},
        {28, "TA4", 4, 226, 2, 4},
        {29, "TA5", 5, 226, 2, 4},
        {30, "TA6", 6, 226, 2, 4},
        {31, "TA7", 7, 226, 2, 4},
        {32, "TA8", 8, 226, 2, 4},
        {33, "TA9", 9, 226, 2, 4},
        {34, "TA10", 10, 226, 2, 4},
        {35, "TA11", 11, 226, 2, 4},
        {36, "TA12", 12, 226, 2, 4},
        {37, "TA13", 13, 226, 2, 4},
        {38, "TA14", 14, 226, 2, 4},
        {39, "TA15", 15, 226, 2, 4},
        {40, "TD0", 0, 61, 2, 4},
        {41, "TD1", 1, 61, 2, 4},
        {42, "TD2", 2, 61, 2, 4},
        {43, "TD3", 3, 61, 2, 4},
        {44, "TD4", 4, 61, 2, 4},
        {45, "TD5", 5, 61, 2, 4},
        {46, "TD6", 6, 61, 2, 4},
        {47, "TD7", 7, 61, 2, 4},
        {48, "TD8", 8, 61, 2, 4},
        {49, "TD9", 9, 61, 2, 4},
        {50, "TD10", 10, 61, 2, 4},
        {51, "TD11", 11, 61, 2, 4},
        {52, "TD12", 12, 61, 2, 4},
        {53, "TD13", 13, 61, 2, 4},
        {54, "TD14", 14, 61, 2, 4},
        {55, "TD15", 15, 61, 2, 4},
        {56, "TCP0", 0, 77, 4, 8},
        {57, "TCP1", 1, 77, 4, 8},
        {58, "TCP2", 2, 77, 4, 8},
        {59, "TCP3", 3, 77, 4, 8},
        {60, "TCP4", 4, 77, 4, 8},
        {61, "TCP5", 5, 77, 4, 8},
        {62, "TCP6", 6, 77, 4, 8},
        {63, "TCP7", 7, 77, 4, 8},
        {64, "TCP8", 8, 77, 4, 8},
        {65, "TCP9", 9, 77, 4, 8},
        {66, "TCP10", 10, 77, 4, 8},
        {67, "TCP11", 11, 77, 4, 8},
        {68, "TCP12", 12, 77, 4, 8},
        {69, "TCP13", 13, 77, 4, 8},
        {70, "TCP14", 14, 77, 4, 8},
        {71, "TCP15", 15, 77, 4, 8},
        {72, "GDS", 0, 123, 4, 4},
        {73, "CPG", 0, 82, 2, 4},
        {74, "CPC", 0, 47, 2, 4},
        {75, "GE", 0, 315, 12, 0},
        {76, "GL1A", 0, 36, 4, 0},
        {77, "GL1C", 0, 64, 4, 0},
        {78, "GL2A0", 0, 91, 4, 0},
        {79, "GL2A1", 1, 91, 4, 0},
        {80, "GL2A2", 2, 91, 4, 0},
        {81, "GL2A3", 3, 91, 4, 0},
        {82, "GL2C0", 0, 235, 4, 0},
        {83, "GL2C1", 1, 235, 4, 0},
        {84, "GL2C2", 2, 235, 4, 0},
        {85, "GL2C3", 3, 235, 4, 0},
        {86, "GL2C4", 4, 235, 4, 0},
        {87, "GL2C5", 5, 235, 4, 0},
        {88, "GL2C6", 6, 235, 4, 0},
        {89, "GL2C7", 7, 235, 4, 0},
        {90, "GL2C8", 8, 235, 4, 0},
        {91, "GL2C9", 9, 235, 4, 0},
        {92, "GL2C10", 10, 235, 4, 0},
        {93, "GL2C11", 11, 235, 4, 0},
        {94, "GL2C12", 12, 235, 4, 0},
        {95, "GL2C13", 13, 235, 4, 0},
        {96, "GL2C14", 14, 235, 4, 0},
        {97, "GL2C15", 15, 235, 4, 0},
        {98, "GL2C16", 16, 235, 4, 0},
        {99, "GL2C17", 17, 235, 4, 0},
        {100, "GL2C18", 18, 235, 4, 0},
        {101, "GL2C19", 19, 235, 4, 0},
        {102, "GL2C20", 20, 235, 4, 0},
        {103, "GL2C21", 21, 235, 4, 0},
        {104, "GL2C22", 22, 235, 4, 0},
        {105, "GL2C23", 23, 235, 4, 0},
        {106, "PA_PH", 0, 960, 8, 0},
        {107, "UTCL1", 0, 15, 2, 0},
        {108, "CHC", 0, 35, 4, 0},
        {109, "CHA", 0, 45, 4, 0},
        {110, "CHCG", 0, 35, 4, 0},
        {111, "GPIN", 0, 5, 5, 0},
        {112, "GPUTime", 0, 6, 2, 0},
    };

    GPA_CounterGroupExposedCounterDesc HWGLExposedCountersByGroupGfx10[] = {
        {0, 0, {7, 116, 117, 118, 126, 127, 128, 162, 257, 259}},
        {1, 461, {7, 116, 117, 118, 126, 127, 128, 162, 257, 259}},
        {2, 922, {7, 116, 117, 118, 126, 127, 128, 162, 257, 259}},
        {3, 1383, {7, 116, 117, 118, 126, 127, 128, 162, 257, 259}},
        {4, 1844, {0, 24}},
        {5, 1884, {4, 15, 28, 46, 48, 55, 60, 63, 144, 174, 175, 176, 177, 178, 179}},
        {6, 2254, {4, 15, 28, 46, 48, 55, 60, 63, 144, 174, 175, 176, 177, 178, 179}},
        {7, 2624, {4, 15, 28, 46, 48, 55, 60, 63, 144, 174, 175, 176, 177, 178, 179}},
        {8, 2994, {4, 15, 28, 46, 48, 55, 60, 63, 144, 174, 175, 176, 177, 178, 179}},
        {9, 3364, {0, 2}},
        {11, 3430, {8, 14, 21, 54, 55, 56, 57, 61, 62, 73, 74, 105, 109}},
        {12, 3696, {159, 160, 161, 162, 235, 236, 237, 238, 259}},
        {13, 4248, {159, 160, 161, 162, 235, 236, 237, 238, 259}},
        {14, 4800, {1, 9, 18, 21, 34, 41, 45, 46, 49, 51, 52, 55, 60, 61, 62, 63, 80, 81, 82, 83, 308, 314, 320, 326}},
        {15, 5129, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {16, 5641, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {17, 6153, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {18, 6665, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {19, 7177, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {20, 7689, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {21, 8201, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {22, 8713, {4, 5, 8, 31, 55, 57, 59, 60, 61, 64, 69, 70, 82, 117, 285}},
        {23, 9225, {12, 14, 17, 19, 22, 24, 27, 29}},
        {24, 9450, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {25, 9676, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {26, 9902, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {27, 10128, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {28, 10354, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {29, 10580, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {30, 10806, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {31, 11032, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {32, 11258, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {33, 11484, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {34, 11710, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {35, 11936, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {36, 12162, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {37, 12388, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {38, 12614, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {39, 12840, {15, 68, 69, 70, 71, 89, 90, 91, 92, 93, 94, 95, 96, 97, 101, 102}},
        {56, 14042, {9, 18, 36}},
        {57, 14119, {9, 18, 36}},
        {58, 14196, {9, 18, 36}},
        {59, 14273, {9, 18, 36}},
        {60, 14350, {9, 18, 36}},
        {61, 14427, {9, 18, 36}},
        {62, 14504, {9, 18, 36}},
        {63, 14581, {9, 18, 36}},
        {64, 14658, {9, 18, 36}},
        {65, 14735, {9, 18, 36}},
        {66, 14812, {9, 18, 36}},
        {67, 14889, {9, 18, 36}},
        {68, 14966, {9, 18, 36}},
        {69, 15043, {9, 18, 36}},
        {70, 15120, {9, 18, 36}},
        {71, 15197, {9, 18, 36}},
        {75, 15526, {211, 221, 227, 233, 275}},
        {77, 15877, {14, 18}},
        {82, 16305, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {83, 16540, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {84, 16775, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {85, 17010, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {86, 17245, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {87, 17480, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {88, 17715, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {89, 17950, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {90, 18185, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {91, 18420, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {92, 18655, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {93, 18890, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {94, 19125, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {95, 19360, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {96, 19595, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {97, 19830, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {98, 20065, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {99, 20300, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {100, 20535, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {101, 20770, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {102, 21005, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {103, 21240, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {104, 21475, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {105, 21710, {3, 35, 75, 76, 79, 89, 90, 91, 92}},
        {112, 23040, {0, 1, 2, 3, 4, 5}},
    };

    GPA_PaddedCounterDesc GLPaddedCounterByGroupGfx10[] = {
    {}
    };

    GPA_SQCounterGroupDesc HWGLSQGroupsGfx10[] = {
        {15, 0, SQ_ALL},
        {16, 0, SQ_ES},
        {17, 0, SQ_GS},
        {18, 0, SQ_VS},
        {19, 0, SQ_PS},
        {20, 0, SQ_LS},
        {21, 0, SQ_HS},
        {22, 0, SQ_CS},
    };


    unsigned int HWGLSQIsolatedGroupsGfx10[] = {
        24, // Ta
        25, // Ta
        26, // Ta
        27, // Ta
        28, // Ta
        29, // Ta
        30, // Ta
        31, // Ta
        32, // Ta
        33, // Ta
        34, // Ta
        35, // Ta
        36, // Ta
        37, // Ta
        38, // Ta
        39, // Ta
        40, // Td
        41, // Td
        42, // Td
        43, // Td
        44, // Td
        45, // Td
        46, // Td
        47, // Td
        48, // Td
        49, // Td
        50, // Td
        51, // Td
        52, // Td
        53, // Td
        54, // Td
        55, // Td
        56, // Tcp
        57, // Tcp
        58, // Tcp
        59, // Tcp
        60, // Tcp
        61, // Tcp
        62, // Tcp
        63, // Tcp
        64, // Tcp
        65, // Tcp
        66, // Tcp
        67, // Tcp
        68, // Tcp
        69, // Tcp
        70, // Tcp
        71, // Tcp
    };

    const unsigned int HWGLGputimeBottomToBottomDurationIndexGfx10 = 23040; ///< Index of delta between the previous command reaching bottom of pipe and the current command reaching bottom of pipe, will not include latency of first data to travel through pipeline, best for large data sets. for GL for Gfx10 family
    const unsigned int HWGLGputimeBottomToBottomStartIndexGfx10 = static_cast<unsigned int>(-1); ///< Index of time of the previous command reaching bottom of pipe for GL for Gfx10 family
    const unsigned int HWGLGputimeBottomToBottomEndIndexGfx10 = static_cast<unsigned int>(-1); ///< Index of time of the current command reaching bottom of pipe for GL for Gfx10 family
    const unsigned int HWGLGputimeTopToBottomDurationIndexGfx10 = 23043; ///< Index of execution duration of the current command from top of pipe to bottom of pipe, may include overhead of time in queue for GL for Gfx10 family
    const unsigned int HWGLGputimeTopToBottomStartIndexGfx10 = static_cast<unsigned int>(-1); ///< Index of time that the current command reaches the top of pipe for GL for Gfx10 family
    const unsigned int HWGLGputimeTopToBottomEndIndexGfx10 = static_cast<unsigned int>(-1); ///< Index of time that the current command reaches the bottom of pipe for GL for Gfx10 family
    const std::set<unsigned int> HWGLTimestampBlockIdsGfx10 =       {112}; ///< Timestamp block id's for GL for Gfx10 family
    const std::set<unsigned int> HWGLTimeCounterIndicesGfx10 =      {23040, 23041, 23042, 23043, 23044, 23045}; ///< Timestamp counter indices for GL for Gfx10 family
    const unsigned int           HWGLGroupCountGfx10                = sizeof(HWGLGroupsGfx10) / sizeof(GPA_CounterGroupDesc);
    const unsigned int           HWGLExposedCountersGroupCountGfx10 = 82;
    const unsigned int           GLPaddedCounterGroupCountGfx10 = 0;
    const unsigned int           HWGLSQGroupCountGfx10              = sizeof(HWGLSQGroupsGfx10) / sizeof(GPA_SQCounterGroupDesc);
    const unsigned int           HWGLSQIsolatedGroupCountGfx10      = sizeof(HWGLSQIsolatedGroupsGfx10) / sizeof(unsigned int);
}; // namespace
