//==============================================================================
// Copyright (c) 2010-2019 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  HSA counter definitions for GFX8
//==============================================================================

// This file is autogenerated by the ConvertHWEnums project

#ifndef _GPA_HW_COUNTER_HSA_GFX8_H_
#define _GPA_HW_COUNTER_HSA_GFX8_H_

#include <set>

struct GPA_HardwareCounterDesc;
struct GPA_CounterGroupDesc;
struct GPA_SQCounterGroupDesc;

namespace CounterGfx8
{
    extern GPA_HardwareCounterDesc*           HSACounterGroupArrayGfx8[]; ///< Array of hardware counter groups for HSA for Gfx8 family
    extern GPA_HardwareCounterDesc*           HSAExposedCountersGroupArrayGfx8[]; ///< Array of hardware exposed counter groups for HSA for Gfx8 family
    extern GPA_CounterGroupDesc               HWHSAGroupsGfx8[]; ///< Array of counter groups for HSA for Gfx8 family
    extern GPA_CounterGroupExposedCounterDesc HWHSAExposedCountersByGroupGfx8[]; ///< Array of exposed counter groups for HSA for Gfx8 family
    extern GPA_PaddedCounterDesc              HSAPaddedCounterByGroupGfx8[]; ///< Array of reserved counter for HSA for Gfx8 family
    extern GPA_SQCounterGroupDesc             HWHSASQGroupsGfx8[]; ///< Array of SQ groups for HSA for Gfx8 family
    extern unsigned int                       HWHSASQIsolatedGroupsGfx8[]; ///< Array of counter groups isolated from SQ counter groups for HSA for Gfx8 family
    extern const std::set<unsigned int>       HWHSATimestampBlockIdsGfx8; ///< Timestamp block id's for HSA for Gfx8 family
    extern const std::set<unsigned int>       HWHSATimeCounterIndicesGfx8; ///< Timestamp counter indices for HSA for Gfx8 family
    extern const unsigned int                 HWHSAGroupCountGfx8; ///< Hardware Group Count for HSA for Gfx8 family
    extern const unsigned int                 HWHSAExposedCountersGroupCountGfx8; ///< Whitelist hardware counter Group Count for HSA for Gfx8 family
    extern const unsigned int                 HSAPaddedCounterGroupCountGfx8; ///< reserved counter group count for HSA for Gfx8 family
    extern const unsigned int                 HWHSASQGroupCountGfx8; ///< Hardware SQ Group Count for HSA for Gfx8 family
    extern const unsigned int                 HWHSASQIsolatedGroupCountGfx8; ///< Hardware Isolated Group Count for HSA for Gfx8 family
}; // namespace

#endif  // _GPA_HW_COUNTER_HSA_GFX8_H_
