## Copyright (c) 2019 Advanced Micro Devices, Inc. All rights reserved.
cmake_minimum_required(VERSION 3.5.1)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(HW_COUNTER_HEADERS
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx10.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Baffin.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Carrizo.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Ellesmere.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Fiji.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Iceland.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Tonga.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9_Gfx906.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9_Placeholder4.h)

set(HW_COUNTER_SRC
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx10.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Baffin.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Carrizo.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Ellesmere.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Fiji.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Iceland.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx8_Tonga.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9_Gfx906.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterGfx9_Placeholder4.cpp)

