## Copyright (c) 2019 Advanced Micro Devices, Inc. All rights reserved.
cmake_minimum_required(VERSION 3.5.1)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(HW_COUNTER_HEADERS_HSA
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterHSAGfx8.h
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterHSAGfx9.h)

set(HW_COUNTER_SRC_HSA
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterHSAGfx8.cpp
${CMAKE_CURRENT_LIST_DIR}/GPAHWCounterHSAGfx9.cpp)

